"""Explainer pages for the terms of a Hindu almanac — DIVASTRO-142.

    /learn                      the index, and /hi/learn
    /learn/what-is-panchang     what-is-tithi, what-is-nakshatra, what-is-yoga-and-karana,
    /learn/what-is-rahu-kaal    what-is-choghadiya, what-is-abhijit-muhurat, what-is-brahma-muhurta,
    ...                         what-is-pradosh-kaal, what-is-sade-sati, what-is-mangal-dosha  (+ /hi/ copies)

"What is Rahu Kaal and how is it calculated?" is asked of search engines and AI
assistants every day. They cite pages that open with the answer, show the
method, and carry FAQPage markup, so each page here is: a direct answer in the
first two sentences, the rule OUR ENGINE uses (read from app/astro/*, never
re-typed: the tables are built from the engine's own tables), a worked example
computed at render time for today in New Delhi by the very functions the
Panchang tool uses, a short descriptive "how it is used", and a FAQ.

**Hidden until reviewed.** Every sentence goes to the owner first
(docs/learn-pages-review.md, generated by `python -m app.learn_pages`). Until
ASTRO_LEARN_PAGES=1 the routes return a real 404 and the family is absent from
the sitemap, the /sitemap hub, the footer and the visit beacon's public list.

Text is learn_text.py (English and Hindi). The other six languages get the
English text under /<code>/learn, noindex, like every untranslated copy
(TRANSLATED below; see app/i18n.py).
"""

from __future__ import annotations

import datetime as dt
import functools
import json
import os
from zoneinfo import ZoneInfo

from fastapi import APIRouter, HTTPException
from fastapi.responses import HTMLResponse

from . import i18n, nakshatra_pages, seo_cities
from .astro import choghadiya as chog
from .astro import festivals
from .astro import panchang as P
from .astro.doshas import analyze_manglik
from .astro.namakshar import NAKSHATRA_LIST
from .chart_service import SIGNS
from .learn_text import CLAIMS, FIVE_LIMBS, PAGES, SLUGS, UI
from .seo_pages import BRAND, _cta, _e, _long_date, _panchang, _path, _render, _span, _time, _today

router = APIRouter()

ENV = "ASTRO_LEARN_PAGES"
# Only the languages learn_text is really written in. Any other registry code gets
# /<code>/learn with the English text, noindex, no sitemap or hreflang entry.
TRANSLATED = i18n.BASE_TRANSLATED
i18n.LOCALIZABLE_ROOTS.add("learn")

CITY = seo_cities.DEFAULT
IST = ZoneInfo(CITY.timezone)
FAQ_TYPE = "FAQPage"


def enabled() -> bool:
    """The switch. Read at call time so a test (or the owner, after a restart) can flip it."""
    return os.environ.get(ENV) == "1"


# --------------------------------------------------------------------------
# Paths, sitemap, hub, footer, beacon
# --------------------------------------------------------------------------

def page_path(slug: str | None, lang: str) -> str:
    return f"{i18n.prefix(lang)}/learn" + (f"/{slug}" if slug else "")


def _canonical_paths() -> list[str]:
    out = []
    for lang in i18n.ordered(TRANSLATED):
        out.append(page_path(None, lang))
        out += [page_path(s, lang) for s in SLUGS]
    return out


def sitemap_paths() -> list[str]:
    """The canonical URLs (index + 11 pages in en and hi), or none while hidden."""
    return _canonical_paths() if enabled() else []


def is_public_path(path: str) -> bool:
    """For analytics.is_public_page: only the canonical URLs, and only when enabled."""
    return enabled() and path in _canonical_paths()


def hub_blocks(lang: str) -> list[str]:
    """For site_hub: a link block, or [] while hidden (and for untranslated languages,
    whose copies are noindex)."""
    if not enabled() or lang not in TRANSLATED:
        return []
    ui = UI[lang]
    items = [(page_path(None, lang), ui["learn"])] + [
        (page_path(s, lang), PAGES[s][lang]["label"]) for s in SLUGS]
    lis = "".join(f'<li><a href="{_e(h)}">{_e(t)}</a></li>' for h, t in items)
    return [f'<h2>{_e(ui["learn"])}</h2>\n<ul class="links">{lis}</ul>\n']


def footer_link(lang: str) -> str:
    """For seo_pages._footer_sections: ' <a>Learn</a>' or '' while hidden."""
    if not enabled() or lang not in TRANSLATED:
        return ""
    return f' <a href="{_e(page_path(None, lang))}">{_e(UI[lang]["learn"])}</a>'


# --------------------------------------------------------------------------
# Small helpers
# --------------------------------------------------------------------------

def _ui(cl: str, key: str, **values) -> str:
    text = UI[cl][key]
    return text.format(**values) if values else text


def _min(minutes: float) -> str:
    return f"{minutes:.0f}"


def _tithi_label(index: int) -> tuple[str, str, int]:
    """0-based tithi index -> (name, paksha, number in the paksha); panchang._tithi_label's rule."""
    within = index % 15
    paksha = "Shukla" if index < 15 else "Krishna"
    name = P.TITHI_NAMES[within]
    if within == 14:
        name = "Purnima" if paksha == "Shukla" else "Amavasya"
    return name, paksha, within + 1


def _clock_span(a: dt.datetime, b: dt.datetime, day: dt.date, cl: str) -> str:
    return f"{_time(a.isoformat(), day, cl)} – {_time(b.isoformat(), day, cl)}"


def _sunrise_sunset(day: dt.date, offset: int = 0):
    return P.sun_times(day + dt.timedelta(days=offset), CITY.latitude, CITY.longitude, CITY.timezone)


def _link(href: str, text: str) -> str:
    return f'<a href="{_e(href)}">{_e(text)}</a>'


def _cell(c) -> str:
    """A table cell: plain text (escaped), or (text, href) for a link."""
    if isinstance(c, tuple):
        return _link(c[1], c[0])
    return _e(c)


def _table(head: list[str], rows: list[list]) -> str:
    th = "".join(f'<th scope="col">{_e(h)}</th>' for h in head)
    body = "".join("<tr>" + "".join(f"<td>{_cell(c)}</td>" for c in r) + "</tr>" for r in rows)
    return f'<div class="scroll"><table><tr>{th}</tr>{body}</table></div>'


def _text(c) -> str:
    return c[0] if isinstance(c, tuple) else c


# --------------------------------------------------------------------------
# Reference tables. Each is (heading key, head labels, rows); `rows` come from the
# engine's own tables. With `day` given a table may add a live column.
# --------------------------------------------------------------------------

def _t_five(cl: str):
    ui = UI[cl]
    return [("t.five.h", [ui["th.limb"], ui["th.measured"], ui["th.divisions"], ui["th.size"]],
             [list(r) for r in FIVE_LIMBS[cl]])]


def _t_tithi(cl: str):
    n, ui = i18n.names(cl), UI[cl]
    rows = []
    for i in range(30):
        name, paksha, _ = _tithi_label(i)
        rows.append([str(i + 1), n.PAKSHA.get(paksha, paksha), n.TITHI.get(name, name),
                     f"{i * 12}° – {(i + 1) * 12}°"])
    return [("t.tithi.h", [ui["th.n"], ui["th.paksha"], ui["th.tithi"], ui["th.angle"]], rows)]


def _t_nakshatra(cl: str):
    ui = UI[cl]
    rows = [[str(nk.index + 1), (nakshatra_pages._nak_label(nk, cl), nakshatra_pages.nak_path(nk, cl)),
             nakshatra_pages.span_text(nk, cl)] for nk in NAKSHATRA_LIST]
    return [("t.nak.h", [ui["th.n"], ui["th.nak"], ui["th.span"]], rows)]


def _t_yoga_karana(cl: str):
    n, ui = i18n.names(cl), UI[cl]
    yoga = [[str(i + 1), n.YOGA.get(y, y)] for i, y in enumerate(P.YOGA_NAMES)]
    kar = [["1", n.KARANA.get("Kimstughna", "Kimstughna"), ui["kind.fixed"]]]
    kar += [[f"2–57 · {i + 1}/7", n.KARANA.get(k, k), ui["kind.movable"]]
            for i, k in enumerate(P.MOVABLE_KARANAS)]
    kar += [[str(58 + i), n.KARANA.get(k, k), ui["kind.fixed"]]
            for i, k in enumerate(P.FIXED_KARANAS[:3])]
    return [("t.yoga.h", [ui["th.n"], ui["th.yoga"]], yoga),
            ("t.karana.h", [ui["th.position"], ui["th.karana"], ui["th.kind"]], kar)]


def _t_rahu(cl: str, day: dt.date | None = None):
    n, ui = i18n.names(cl), UI[cl]
    head = [ui["th.weekday"], ui["th.part"]]
    live: dict[int, str] = {}
    if day is not None:
        head.append(ui["th.in_city"].format(city=_city_name(cl)))
        for off in range(7):
            d = day + dt.timedelta(days=off)
            q = _panchang(CITY.slug, d)
            live[q["vara"]["index"]] = (f"{_span(q['muhurta']['rahu_kaal'], d, cl)} "
                                        f"({i18n.format_date(d, cl, short=True)})")
    rows = []
    for v in range(7):
        row = [n.VARA.get(P.VARA_ENGLISH[v], P.VARA_ENGLISH[v]), str(P.RAHU_SEGMENT[v] + 1)]
        if day is not None:
            row.append(live[v])
        rows.append(row)
    return [("t.rahu.h", head, rows)]


def _t_choghadiya(cl: str, day: dt.date | None = None):
    n, ui = i18n.names(cl), UI[cl]

    def nm(x):
        return n.CHOGHADIYA.get(x, x)

    names = [[nm(k), n.GRAHA.get(v["ruler"], v["ruler"]),
              n.CHOGHADIYA_QUALITY.get(v["quality"], v["quality"])]
             for k, v in chog.CHOGHADIYA_INFO.items()]
    out = [("t.chog.names.h", [ui["th.name"], ui["th.ruler"], ui["th.class"]], names)]
    for key, table in (("t.chog.day.h", chog.DAY_SEQUENCE), ("t.chog.night.h", chog.NIGHT_SEQUENCE)):
        rows = [[n.VARA.get(P.VARA_ENGLISH[v], P.VARA_ENGLISH[v]), " → ".join(nm(x) for x in table[v])]
                for v in range(7)]
        out.append((key, [ui["th.weekday"], ui["th.seq"]], rows))
    if day is not None:
        p = _panchang(CITY.slug, day)
        slots, _ = _choghadiya_slots(p)
        rows = [[f"{_time(s['start'].isoformat(), day, cl)} – {_time(s['end'].isoformat(), day, cl)}",
                 nm(s["name"]), n.CHOGHADIYA_QUALITY.get(s["quality"], s["quality"])] for s in slots]
        out.append(("t.chog.today.h", [ui["th.when"], ui["th.name"], ui["th.class"]], rows))
    return out


def _choghadiya_slots(p: dict):
    from .seo_pages import choghadiya_slots   # the Choghadiya page's own function
    return choghadiya_slots(p)


def _t_abhijit(cl: str):
    n, ui = i18n.names(cl), UI[cl]
    rows = [[n.VARA.get(P.VARA_ENGLISH[v], P.VARA_ENGLISH[v]),
             ui["no"] if v == P.ABHIJIT_EXCLUDED_VARA else ui["yes"]] for v in range(7)]
    return [("t.abhijit.h", [ui["th.weekday"], ui["th.given"]], rows)]


def _brahma(day: dt.date):
    """(yesterday's sunset, start, end, today's sunrise) of this morning's Brahma Muhurta:
    the 14th of the 15 equal muhurtas of the night that ended at today's sunrise."""
    _, sunset_prev, sunrise = _sunrise_sunset(day, -1)
    night = sunrise - sunset_prev
    return sunset_prev, sunset_prev + night * 13 / 15, sunset_prev + night * 14 / 15, sunrise


def _t_brahma(cl: str, day: dt.date | None = None):
    if day is None:
        return []
    ui = UI[cl]
    ss, start, end, sr = _brahma(day)
    t = lambda m: _time(m.isoformat(), day, cl)   # noqa: E731
    rows = [[ui["r.sunset_prev"], t(ss)],
            [ui["r.parts_1_13"], f"{t(ss)} – {t(start)}"],
            [ui["r.brahma"], f"{t(start)} – {t(end)}"],
            [ui["r.part_15"], f"{t(end)} – {t(sr)}"],
            [ui["r.sunrise"], t(sr)]]
    return [("t.brahma.h", [ui["th.name"], ui["th.when"]], rows)]


def _pradosh_specs():
    """(key, name_en, name_hi, [tithi indexes]) of every observance festivals.py tests at Pradosh."""
    seen: dict[str, tuple[str, str, list[int]]] = {}
    for spec in [*festivals.RECURRING, *festivals.FESTIVALS]:
        if spec.rule == "pradosh":
            _, _, idx = seen.setdefault(spec.key, (spec.name_en, spec.name_hi, []))
            idx.append(spec.tithi)
    return [(k, en, hi, idx) for k, (en, hi, idx) in seen.items()]


def _t_pradosh(cl: str):
    n, ui = i18n.names(cl), UI[cl]
    rows = []
    for _, en, hi, idx in _pradosh_specs():
        tithis = " · ".join(n.tithi_label(_tithi_label(i)[1], _tithi_label(i)[0]) for i in idx)
        rows.append([hi if cl == "hi" else en, tithis])
    return [("t.pradosh.h", [ui["th.obs"], ui["th.req"]], rows)]


def _t_sade(cl: str):
    ui = UI[cl]
    rows = [[nakshatra_pages._sign_name(m, cl), nakshatra_pages._sign_name((m + 11) % 12, cl),
             nakshatra_pages._sign_name(m, cl), nakshatra_pages._sign_name((m + 1) % 12, cl)]
            for m in range(12)]
    # The Saturn signs of Sade Sati for Moon sign m, in the engine's own terms.
    return [("t.sade.h", [ui["th.moon"], ui["th.s12"], ui["th.s1"], ui["th.s2"]], rows)]


def _t_mangal(cl: str):
    ui = UI[cl]
    refs = [[ui["ex.lagna"], "1.0"], [ui["ex.moon"], "0.5"], [ui["ex.venus"], "0.3"]]
    cancels = [[str(i + 1), ui[k]] for i, k in enumerate(
        ("cancel.dignified", "cancel.2", "cancel.4", "cancel.7", "cancel.8", "cancel.12",
         "cancel.jupiter", "cancel.moon"))]
    return [("t.mangal.houses.h", [ui["th.ref"], ui["th.weight"]], refs),
            ("t.mangal.cancel.h", [ui["th.n"], ui["th.cond"]], cancels)]


STATIC_TABLES = {
    "what-is-panchang": _t_five, "what-is-tithi": _t_tithi, "what-is-nakshatra": _t_nakshatra,
    "what-is-yoga-and-karana": _t_yoga_karana, "what-is-abhijit-muhurat": _t_abhijit,
    "what-is-pradosh-kaal": _t_pradosh, "what-is-sade-sati": _t_sade,
    "what-is-mangal-dosha": _t_mangal,
}


def tables_for(slug: str, cl: str, day: dt.date | None = None):
    """The page's tables (with live columns/rows when `day` is given), in page order."""
    if slug == "what-is-rahu-kaal":
        return _t_rahu(cl, day)
    if slug == "what-is-choghadiya":
        return _t_choghadiya(cl, day)
    if slug == "what-is-brahma-muhurta":
        return _t_brahma(cl, day)
    return STATIC_TABLES[slug](cl)


# --------------------------------------------------------------------------
# The worked examples (computed at render time, from the engines)
# --------------------------------------------------------------------------

def _city_name(cl: str) -> str:
    return seo_cities.city_name(CITY, cl)


def _common(day: dt.date, cl: str) -> dict:
    n = i18n.names(cl)
    p = _panchang(CITY.slug, day)
    return {"city": _city_name(cl), "weekday": n.VARA.get(p["vara"]["weekday"], p["vara"]["weekday"]),
            "date": _long_date(day, cl)}


def _limb(entry: dict, day: dt.date, cl: str, table: dict) -> tuple[str, str]:
    return table.get(entry["name"], entry["name"]), _time(entry["ends"], day, cl)


def live_values(slug: str, day: dt.date, cl: str) -> tuple[str, dict]:
    """(template key, values) of the worked example for `slug` on `day`."""
    n = i18n.names(cl)
    p = _panchang(CITY.slug, day)
    v = _common(day, cl)
    m = p["muhurta"]

    if slug == "what-is-panchang":
        t, k, y, ka = p["tithi"][0], p["nakshatra"][0], p["yoga"][0], p["karana"][0]
        v.update(tithi=n.tithi_label(t["paksha"], t["name"]), tithi_end=_time(t["ends"], day, cl))
        v["nakshatra"], v["nak_end"] = _limb(k, day, cl, n.NAKSHATRAS)
        v["yoga"], v["yoga_end"] = _limb(y, day, cl, n.YOGA)
        v["karana"], v["karana_end"] = _limb(ka, day, cl, n.KARANA)
        v["sunrise"], v["sunset"] = _time(p["sun"]["rise"], day, cl), _time(p["sun"]["set"], day, cl)
        return "live", v
    if slug == "what-is-tithi":
        t = p["tithi"][0]
        v.update(tithi=n.tithi_label(t["paksha"], t["name"]), start=_time(t["starts"], day, cl),
                 end=_time(t["ends"], day, cl))
        return "live", v
    if slug == "what-is-nakshatra":
        k = p["nakshatra"][0]
        v.update(nakshatra=n.NAKSHATRAS.get(k["name"], k["name"]), pada=str(k["pada"]),
                 end=_time(k["ends"], day, cl))
        return "live", v
    if slug == "what-is-yoga-and-karana":
        v["yoga"], v["yoga_end"] = _limb(p["yoga"][0], day, cl, n.YOGA)
        v["karana"], v["karana_end"] = _limb(p["karana"][0], day, cl, n.KARANA)
        return "live", v
    if slug == "what-is-rahu-kaal":
        r = m["rahu_kaal"]
        v.update(rahu=_span(r, day, cl), part=str(r["segment"]), minutes=_min(r["duration_minutes"]),
                 sunrise=_time(p["sun"]["rise"], day, cl), sunset=_time(p["sun"]["set"], day, cl))
        return "live", v
    if slug == "what-is-choghadiya":
        day_slots, _ = _choghadiya_slots(p)
        first = day_slots[0]
        v.update(first=n.CHOGHADIYA.get(first["name"], first["name"]),
                 first_when=_clock_span(first["start"], first["end"], day, cl),
                 sunrise=_time(p["sun"]["rise"], day, cl), sunset=_time(p["sun"]["set"], day, cl),
                 minutes=_min((first["end"] - first["start"]).total_seconds() / 60))
        return "live", v
    if slug == "what-is-abhijit-muhurat":
        a = m["abhijit"]
        if a:
            v.update(abhijit=_span(a, day, cl), minutes=_min(a["duration_minutes"]),
                     sunrise=_time(p["sun"]["rise"], day, cl), sunset=_time(p["sun"]["set"], day, cl))
            return "live", v
        d2 = day + dt.timedelta(days=1)
        a2 = _panchang(CITY.slug, d2)["muhurta"]["abhijit"]
        v.update(date2=_long_date(d2, cl), abhijit2=_span(a2, d2, cl),
                 minutes2=_min(a2["duration_minutes"]))
        return "live_none", v
    if slug == "what-is-brahma-muhurta":
        ss, start, end, sr = _brahma(day)
        v.update(sunset_prev=_time(ss.isoformat(), day, cl), sunrise=_time(sr.isoformat(), day, cl),
                 brahma=_clock_span(start, end, day, cl), minutes=_min((end - start).total_seconds() / 60))
        return "live", v
    if slug == "what-is-pradosh-kaal":
        _, sunset, next_sunrise = _sunrise_sunset(day)
        night = next_sunrise - sunset
        end = sunset + night * 3 / 15
        v.update(sunset=_time(sunset.isoformat(), day, cl), pradosh=_clock_span(sunset, end, day, cl),
                 minutes=_min((end - sunset).total_seconds() / 60),
                 dating=_clock_span(sunset, sunset + dt.timedelta(minutes=96), day, cl))
        return "live", v
    if slug == "what-is-sade-sati":
        saturn_idx, retro = saturn_now(day)
        signs = [nakshatra_pages._sign_name((saturn_idx + d) % 12, cl) for d in (-1, 0, 1)]
        v.update(saturn=nakshatra_pages._sign_name(saturn_idx, cl),
                 motion=UI[cl]["motion.retro" if retro else "motion.direct"],
                 signs=f"{signs[0]}, {signs[1]} {UI[cl]['and']} {signs[2]}")
        return "live", v
    if slug == "what-is-mangal-dosha":
        return "live", v
    raise KeyError(slug)


@functools.lru_cache(maxsize=8)
def saturn_now(day: dt.date) -> tuple[int, bool]:
    """(Saturn's sidereal sign index, retrograde?) at midnight IST on `day`, from the same
    function the Kundali's Sade Sati panel uses (one year's window keeps it cheap)."""
    r = P.sade_sati_for_moon_sign(0, dt.datetime(day.year, day.month, day.day, tzinfo=IST),
                                  timezone=CITY.timezone, window_years=1.0)
    return SIGNS.index(r["saturn"]["sign"]), bool(r["saturn"]["retrograde"])


# The two illustrative charts for the Mangal Dosha page. Planets that do not take part in the
# rule are parked where they cannot aspect or join Mars.
MANGAL_CHARTS = (
    {"lagna": "Aries", "Mars": "Libra", "Moon": "Taurus", "Venus": "Cancer", "Jupiter": "Leo"},
    {"lagna": "Cancer", "Mars": "Capricorn", "Moon": "Leo", "Venus": "Gemini", "Jupiter": "Gemini"},
)
_PARKED = {"Sun": "Sagittarius", "Mercury": "Scorpio", "Saturn": "Aquarius"}
_CANCEL_KEYS = (("dignified", "cancel.dignified"), ("2nd house", "cancel.2"),
                ("4th house", "cancel.4"), ("7th house", "cancel.7"), ("8th house", "cancel.8"),
                ("12th house", "cancel.12"), ("Guru-Mangala", "cancel.jupiter"),
                ("Chandra-Mangala", "cancel.moon"))


class _Session:
    def __init__(self, bundle: dict):
        self.bundle = bundle


def mangal_session(chart: dict) -> _Session:
    """A minimal sidereal chart bundle for analyze_manglik: Lagna, seven grahas, whole-sign houses."""
    placed = {**_PARKED, **{k: v for k, v in chart.items() if k != "lagna"}}
    objects = {"ASC": {"sign": chart["lagna"], "longitude": SIGNS.index(chart["lagna"]) * 30 + 15.0}}
    for graha, sign in placed.items():
        objects[graha] = {"sign": sign, "longitude": SIGNS.index(sign) * 30 + 15.0,
                          "retrograde": False}
    first = SIGNS.index(chart["lagna"])
    return _Session({"meta": {"zodiac": "sidereal"}, "objects": objects,
                     "houses": {"signs": [SIGNS[(first + i) % 12] for i in range(12)]}})


@functools.lru_cache(maxsize=1)
def mangal_results() -> tuple[dict, ...]:
    return tuple(analyze_manglik(mangal_session(c)) for c in MANGAL_CHARTS)


def cancel_key(message: str) -> str | None:
    return next((key for needle, key in _CANCEL_KEYS if needle in message), None)


def _mangal_examples(cl: str) -> str:
    ui, n = UI[cl], i18n.names(cl)
    rows = []
    for k, (chart, res) in enumerate(zip(MANGAL_CHARTS, mangal_results()), 1):
        sg = lambda s: n.RASHI.get(s, s)   # noqa: E731
        setup = "; ".join(f"{ui['ex.' + g.lower()]}: {sg(chart[g] if g != 'Lagna' else chart['lagna'])}"
                          for g in ("Lagna", "Mars", "Moon", "Venus", "Jupiter"))
        h = res["houses"]
        lines = [_e(ui["ex.houses"].format(lagna=h["from_lagna"], moon=h["from_moon"],
                                           venus=h["from_venus"]))]
        if res["is_manglik"]:
            lines.append(_e(ui["ex.manglik"].format(score=f"{res['score']:.1f}")))
        elif res["is_cancelled"]:
            lines.append(_e(ui["ex.cancelled"]))
            lines.append("<ul>" + "".join(
                f"<li>{_e(ui[cancel_key(c)] if cancel_key(c) else c)}</li>"
                for c in res["cancellations"]) + "</ul>")
        else:
            lines.append(_e(ui["ex.clear"]))
        rows.append(f"<tr><td><strong>{_e(ui['ex.label'].format(k=k))}</strong><br>{_e(setup)}</td>"
                    f"<td>{'<br>'.join(lines)}</td></tr>")
    head = f'<tr><th scope="col">{_e(ui["th.chart"])}</th><th scope="col">{_e(ui["th.result"])}</th></tr>'
    return f'<h2>{_e(ui["t.mangal.example.h"])}</h2><div class="scroll"><table>{head}{"".join(rows)}</table></div>'


# --------------------------------------------------------------------------
# Page assembly
# --------------------------------------------------------------------------

TOOLS = {   # slug -> (tool path keys for the "Try it" block, CTA tool for the app button)
    "what-is-panchang": (("panchang",), "panchang"),
    "what-is-tithi": (("panchang", "vrat"), "panchang"),
    "what-is-nakshatra": (("nakshatra", "panchang"), "free-kundali"),
    "what-is-yoga-and-karana": (("panchang",), "panchang"),
    "what-is-rahu-kaal": (("rahu-kaal", "panchang"), "rahu-kaal"),
    "what-is-choghadiya": (("choghadiya", "panchang"), "choghadiya"),
    "what-is-abhijit-muhurat": (("panchang", "rahu-kaal"), "panchang"),
    "what-is-brahma-muhurta": (("panchang",), "panchang"),
    "what-is-pradosh-kaal": (("panchang", "vrat"), "panchang"),
    "what-is-sade-sati": (("free-kundali",), "free-kundali"),
    "what-is-mangal-dosha": (("free-kundali", "kundali-milan"), "free-kundali"),
}
TOP_CITIES = 8


def _tool_href(key: str, cl: str) -> str:
    pre = i18n.prefix(cl)
    if key in ("panchang", "rahu-kaal", "choghadiya"):
        return _path(key, CITY, cl)
    if key == "vrat":
        return f"{pre}/vrat-tyohar"
    if key == "nakshatra":
        return nakshatra_pages.nak_path(None, cl)
    return f"{pre}/{key}"


_TOOL_UI = {"panchang": "tool.panchang", "rahu-kaal": "tool.rahu-kaal", "choghadiya": "tool.choghadiya",
            "vrat": "tool.vrat", "nakshatra": "tool.nakshatra", "free-kundali": "tool.kundali",
            "kundali-milan": "tool.milan"}


def _related(slug: str, cl: str) -> str:
    ui = UI[cl]
    keys, cta_tool = TOOLS[slug]
    items = [(_tool_href(k, cl), ui[_TOOL_UI[k]]) for k in keys]
    items.append((i18n.prefix(cl) + "/sitemap", ui["tool.sitemap"]))
    out = [f'<h2>{_e(ui["h.tool"])}</h2>',
           _cta(cta_tool, ui[_TOOL_UI[cta_tool]], cl),
           '<ul class="links">' + "".join(f"<li>{_link(h, t)}</li>" for h, t in items) + "</ul>"]
    for tool in ("panchang", *(k for k in keys if k in ("rahu-kaal", "choghadiya"))):
        cities = seo_cities.CITIES[:TOP_CITIES]
        out.append('<ul class="links">' + "".join(
            "<li>" + _link(_path(tool, c, cl), ui["tool.in_city"].format(
                tool=ui[_TOOL_UI[tool]], city=seo_cities.city_name(c, cl))) + "</li>"
            for c in cities) + "</ul>")
    out.append(f'<h2>{_e(ui["h.more"])}</h2><ul class="links">' + "".join(
        f"<li>{_link(page_path(s, cl), PAGES[s][cl]['label'])}</li>" for s in SLUGS if s != slug)
        + f"<li>{_link(page_path(None, cl), ui['learn'])}</li></ul>")
    return "\n".join(out)


def _faq(items) -> tuple[str, dict]:
    html_part = "".join(f"<h3>{_e(q)}</h3><p>{_e(a)}</p>" for q, a in items)
    ld = {"@type": FAQ_TYPE, "mainEntity": [
        {"@type": "Question", "name": q, "acceptedAnswer": {"@type": "Answer", "text": a}}
        for q, a in items]}
    return f'<div class="faq">{html_part}</div>', ld


def _tool_name_for_note(slug: str, cl: str) -> str:
    return UI[cl][_TOOL_UI[TOOLS[slug][0][0]]]


@functools.lru_cache(maxsize=64)
def _page_parts(slug: str, cl: str, day: dt.date) -> tuple[str, str, str, dict]:
    """(title, description, body, FAQPage JSON-LD) in content language `cl`."""
    t, ui = PAGES[slug][cl], UI[cl]
    key, values = live_values(slug, day, cl)
    live = _e(t[key].format(**values))
    if slug == "what-is-tithi":
        p = _panchang(CITY.slug, day)
        if len(p["tithi"]) > 1:
            n, nxt = i18n.names(cl), p["tithi"][1]
            live += _e(t["live2"].format(next=n.tithi_label(nxt["paksha"], nxt["name"]),
                                         next_end=_time(nxt["ends"], day, cl)))
    paragraphs = "".join(f"<p>{_e(x)}</p>" for x in t["method"])
    convention = (f'<p><strong>{_e(ui["conv"])}.</strong> {_e(t["convention"])}</p>'
                  if t.get("convention") else "")
    note = t.get("live_note", ui["live.note"]).format(tool=_tool_name_for_note(slug, cl))
    note_html = f"<p><small>{_e(note)}</small></p>" if note else ""
    tables = "".join(
        f'<h2>{_e(ui[hk].format(city=_city_name(cl)))}</h2>{_table(head, rows)}'
        for hk, head, rows in tables_for(slug, cl, day))
    examples = _mangal_examples(cl) if slug == "what-is-mangal-dosha" else ""
    faq_html, faq_ld = _faq(t["faq"])
    body = f"""
<h1>{_e(t["h1"])}</h1>
<div class="box"><p>{_e(t["answer"])}</p></div>
<h2>{_e(ui["h.method"])}</h2>
{paragraphs}
{convention}
<h2>{_e(t["live_h"] or ui["h.live"].format(city=_city_name(cl)))}</h2>
<div class="box"><p>{live}</p>{note_html}</div>
{examples}{tables}
<h2>{_e(ui["h.use"])}</h2>
{"".join(f"<p>{_e(x)}</p>" for x in t["use"])}
<h2>{_e(ui["h.faq"])}</h2>
{faq_html}
{_related(slug, cl)}
<p><small>{_e(ui["disclaimer"])}</small></p>"""
    return f"{t['title']} | {BRAND}", t["desc"], body, faq_ld


@functools.lru_cache(maxsize=8)
def _index_parts(cl: str) -> tuple[str, str, str]:
    ui = UI[cl]
    items = "".join(
        f'<h2>{_link(page_path(s, cl), PAGES[s][cl]["label"])}</h2><p>{_e(PAGES[s][cl]["blurb"])}</p>'
        for s in SLUGS)
    body = f'<h1>{_e(ui["index.h1"])}</h1>\n<p>{_e(ui["index.intro"])}</p>\n{items}\n<p><small>{_e(ui["disclaimer"])}</small></p>'
    return f"{ui['index.title']} | {BRAND}", ui["index.desc"], body


def _content_lang(lang: str) -> str:
    return lang if lang in TRANSLATED else "en"


def render_index(lang: str, status: int = 200) -> HTMLResponse:
    cl = _content_lang(lang)
    title, desc, body = _index_parts(cl)
    return _render(title=title, description=desc, path=page_path(None, lang),
                   crumbs=[(UI[cl]["learn"], page_path(None, lang))], body=body, lang=lang,
                   alt="twin" if status == 200 else None, status=status,
                   cache=status == 200, translated=TRANSLATED)


def render_page(slug: str, lang: str) -> HTMLResponse:
    cl = _content_lang(lang)
    title, desc, body, faq_ld = _page_parts(slug, cl, _today())
    return _render(title=title, description=desc, path=page_path(slug, lang),
                   crumbs=[(UI[cl]["learn"], page_path(None, lang)),
                           (PAGES[slug][cl]["label"], page_path(slug, lang))],
                   body=body, lang=lang, alt="twin", extra_ld=(faq_ld,), translated=TRANSLATED)


def _gate() -> None:
    if not enabled():
        raise HTTPException(status_code=404, detail="Not Found")


def _serve(slug: str | None, lang: str) -> HTMLResponse:
    _gate()
    if slug is None:
        return render_index(lang)
    if slug not in PAGES:
        return render_index(lang, status=404)    # a real 404 that still offers the pages
    return render_page(slug, lang)


@router.get("/learn", response_class=HTMLResponse)
def learn_index() -> HTMLResponse:
    return _serve(None, "en")


@router.get("/hi/learn", response_class=HTMLResponse)
def learn_index_hi() -> HTMLResponse:
    return _serve(None, "hi")


@router.get("/learn/{slug}", response_class=HTMLResponse)
def learn_page(slug: str) -> HTMLResponse:
    return _serve(slug, "en")


@router.get("/hi/learn/{slug}", response_class=HTMLResponse)
def learn_page_hi(slug: str) -> HTMLResponse:
    return _serve(slug, "hi")


@router.get("/{lang:xlang}/learn", response_class=HTMLResponse)
def learn_index_lang(lang: str) -> HTMLResponse:
    return _serve(None, lang)


@router.get("/{lang:xlang}/learn/{slug}", response_class=HTMLResponse)
def learn_page_lang(lang: str, slug: str) -> HTMLResponse:
    return _serve(slug, lang)


# --------------------------------------------------------------------------
# The owner's review document (docs/learn-pages-review.md)
# --------------------------------------------------------------------------

def _md_table(head: list[str], rows: list[list]) -> str:
    esc = lambda c: str(_text(c)).replace("|", "\\|")   # noqa: E731
    return "\n".join(["| " + " | ".join(esc(h) for h in head) + " |",
                      "|" + "|".join("---" for _ in head) + "|",
                      *("| " + " | ".join(esc(c) for c in r) + " |" for r in rows)])


def review_markdown() -> str:
    """Everything the owner has to read, verbatim from learn_text and the engine's tables.
    Contains no date and no live value, so tests/test_learn_pages.py can pin it to the code."""
    out = [
        "# /learn pages: owner review",
        "",
        "**NEEDS OWNER REVIEW. The pages are hidden (404, not in the sitemap, hub, footers or the "
        "beacon's public list) until `ASTRO_LEARN_PAGES=1` is set on the server and the app restarted.**",
        "",
        "Generated by `python -m app.learn_pages > docs/learn-pages-review.md`; "
        "`tests/test_learn_pages.py` fails if this file drifts from the code, so what you read is "
        "what ships. English text is `app/learn_text.py` (PAGES, UI); the Hindi is beside it. "
        "Tables that follow are the rule tables as the page renders them; the live worked example "
        "(today, New Delhi) is computed by the engine at render time and is not listed here.",
        "",
        "## Please look at these first",
        "",
        "1. **Brahma Muhurta is not an engine feature.** The engine has only the label; this page "
        "defines it as the 14th of the 15 equal muhurtas of the night (same division "
        "`festivals.Day.night_muhurta` uses for Nishita Kaal). See its page below.",
        "2. **Mangal Dosha: two implementations.** `app/astro/doshas.py` (the Kundali check, "
        "described on the page) and `app/astro/matching.py mangal_dosha()` (the Kundali Milan tool) "
        "differ in detail: own-sign set, per-house weights, severity grading, and how Jupiter is "
        "treated. The page says so in one sentence.",
        "3. **Mangal Dosha's worked example is not live.** It runs the engine on two stated "
        "illustrative charts (not real people), because a chart for 'now' would read as 'today's sky "
        "is Manglik'.",
        "4. **Abhijit and Rahu Kaal 'traditions differ' sentences** are generic statements that the "
        "engine follows one convention; they name no other almanac.",
        "5. Regional languages (kn te ta ml bn or) serve the English text, noindex, on "
        "`/<code>/learn/...`; they are not in the sitemap and carry no hreflang.",
        "",
    ]
    for slug in SLUGS:
        en, hi = PAGES[slug]["en"], PAGES[slug]["hi"]
        out += [f"## {slug}", "", f"URL: `/learn/{slug}` and `/hi/learn/{slug}`", "",
                "**NEEDS OWNER REVIEW**", "",
                f"- Title: {en['title']} | {BRAND}",
                f"- H1: {en['h1']}",
                f"- Meta description: {en['desc']}", "",
                "### Direct answer (verbatim, English)", "", f"> {en['answer']}", "",
                "### How it is calculated (verbatim, English)", ""]
        out += [f"{para}\n" for para in en["method"]]
        if en.get("convention"):
            out += [f"**{UI['en']['conv']}.** {en['convention']}", ""]
        for hk, head, rows in tables_for(slug, "en"):
            out += [f"### Rule table: {UI['en'][hk].format(city='New Delhi')}", "", _md_table(head, rows), ""]
        if slug == "what-is-mangal-dosha":
            out += ["### Worked example (illustrative charts, run through `analyze_manglik`)", ""]
            for chart, res in zip(MANGAL_CHARTS, mangal_results()):
                out += [f"- {chart}: manglik={res['is_manglik']}, cancelled={res['is_cancelled']}, "
                        f"score={res['score']}, houses={res['houses']}, "
                        f"cancellations={res['cancellations']}"]
            out += [""]
        out += ["### How it is used (verbatim, English)", ""]
        out += [f"{para}\n" for para in en["use"]]
        out += ["### Common questions (verbatim, English; also the FAQPage JSON-LD)", ""]
        out += [f"- **{q}** {a}" for q, a in en["faq"]]
        out += ["", "### Every factual claim, and where it comes from", "",
                _md_table(["Claim", "Engine function or file"], [list(c) for c in CLAIMS[slug]]), "",
                "### Hindi (verbatim, for the Hindi reviewer)", "",
                f"- H1: {hi['h1']}", f"- Meta description: {hi['desc']}", "",
                f"> {hi['answer']}", ""]
        out += [f"{para}\n" for para in hi["method"]]
        if hi.get("convention"):
            out += [f"**{UI['hi']['conv']}.** {hi['convention']}", ""]
        out += [f"{para}\n" for para in hi["use"]]
        out += [f"- **{q}** {a}" for q, a in hi["faq"]]
        out += ["", "---", ""]
    return "\n".join(out).rstrip() + "\n"


if __name__ == "__main__":   # python -m app.learn_pages > docs/learn-pages-review.md
    import sys
    sys.stdout.write(review_markdown())
