"""Short trait descriptions for the nakshatra and rashi pages (DIVASTRO-115).

Written for the public pages: 80–150 words in English, the same substance in
Hindi, respectful and never fear-based — no predictions of loss, illness or
"bad" stars, no promises. The gist follows the traditional character of each
nakshatra (its deity and symbol) and of each sign (its lord, element and
quality) as the standard jyotisha texts describe them; they are tendencies
people born with the Moon there often recognise, not verdicts. The test
checks the word counts, the slugs and a fear-word list.
"""

from __future__ import annotations

NAKSHATRA_TRAITS: dict[str, dict[str, str]] = {
    "ashwini": {
        "en": "Ashwini is the first nakshatra, ruled by the Ashwini Kumaras, the twin healers of the gods, and symbolised by a horse's head. People with the Moon here are often quick, energetic and eager to begin things — the first to help, the first to try something new. Tradition links Ashwini with healing, speed and fresh starts, so many feel drawn to medicine, sport, travel or any work that needs swift, practical action. The gift of this nakshatra is initiative and a youthful optimism; the lesson is patience, finishing what was started with the same enthusiasm with which it began.",
        "hi": "अश्विनी पहला नक्षत्र है, जिसके देवता देवताओं के वैद्य अश्विनी कुमार हैं और प्रतीक अश्व का मुख है। इस नक्षत्र में चंद्रमा वाले लोग प्रायः फुर्तीले, ऊर्जावान और नई शुरुआत के लिए उत्सुक होते हैं — मदद में सबसे आगे, कुछ नया करने में सबसे पहले। परंपरा अश्विनी को उपचार, गति और नए आरंभ से जोड़ती है, इसलिए कई लोगों का झुकाव चिकित्सा, खेल, यात्रा या ऐसे काम की ओर होता है जिसमें शीघ्र और व्यावहारिक कदम चाहिए। इस नक्षत्र का वरदान पहल और युवा आशावाद है; इसकी सीख धैर्य है — जो काम जिस उत्साह से शुरू हो, उसी उत्साह से पूरा भी हो।",
    },
    "bharani": {
        "en": "Bharani is ruled by Yama, the lord of dharma, and its symbol is the yoni, the womb that carries and protects new life. People with the Moon here often have strong will, deep feelings and a serious sense of responsibility. They tend to carry their commitments through to the end and are not easily swayed. Tradition sees Bharani as the nakshatra of bearing and nurturing — holding something until it is ready to be born — so creativity, family, art and work that asks for endurance suit it well. Its strength is steadfastness; its lesson is balancing desire with restraint and kindness.",
        "hi": "भरणी नक्षत्र के देवता धर्मराज यम हैं और इसका प्रतीक योनि है — वह गर्भ जो नए जीवन को धारण और सुरक्षित करता है। इस नक्षत्र में चंद्रमा वाले लोगों में प्रायः दृढ़ इच्छाशक्ति, गहरी भावनाएँ और ज़िम्मेदारी का गंभीर भाव होता है। वे अपने वचन अंत तक निभाते हैं और आसानी से डिगते नहीं। परंपरा भरणी को धारण और पोषण का नक्षत्र मानती है — किसी चीज़ को तब तक सँभालना जब तक वह जन्म लेने को तैयार न हो — इसलिए रचनात्मकता, परिवार, कला और धैर्य माँगने वाले काम इसके अनुकूल हैं। इसकी शक्ति स्थिरता है; इसकी सीख इच्छा और संयम में संतुलन रखना है।",
    },
    "krittika": {
        "en": "Krittika is ruled by Agni, the sacred fire, and symbolised by a razor or a flame. Fire purifies and cuts through confusion, and people with the Moon here are often direct, principled and sharp in judgement. They can be protective of those they love and are willing to say what needs to be said. Krittika is also the nakshatra of the six mothers who nursed Kartikeya, so beneath the sharpness there is real warmth and care. Teaching, cooking, leadership and any work that needs clarity suit it. Its lesson is to let the fire warm and guide rather than burn.",
        "hi": "कृत्तिका नक्षत्र के देवता पवित्र अग्नि हैं और इसका प्रतीक छुरा या अग्निशिखा है। अग्नि शुद्ध करती है और भ्रम को काटती है, और इस नक्षत्र में चंद्रमा वाले लोग प्रायः स्पष्टवादी, सिद्धांतवादी और तीक्ष्ण बुद्धि वाले होते हैं। वे अपनों की रक्षा करते हैं और जो कहना ज़रूरी हो, कह देते हैं। कृत्तिका उन छह माताओं का भी नक्षत्र है जिन्होंने कार्तिकेय का पालन किया, इसलिए तीखेपन के नीचे सच्ची ममता और स्नेह होता है। शिक्षण, रसोई, नेतृत्व और स्पष्टता माँगने वाले काम इसके अनुकूल हैं। इसकी सीख है कि अग्नि जलाए नहीं, बल्कि गर्माहट और मार्ग दे।",
    },
    "rohini": {
        "en": "Rohini is ruled by Brahma, the creator, and symbolised by a chariot or ox-cart. It is said to be the Moon's favourite nakshatra, and people with the Moon here are often warm, attractive, artistic and fond of comfort and beauty. They have a gift for making things grow — gardens, homes, businesses and relationships. Tradition associates Rohini with fertility, abundance and steady progress, so agriculture, the arts, design, food and hospitality suit it well. Its nature is gentle and settled; its lesson is to enjoy what is beautiful without holding on too tightly to it.",
        "hi": "रोहिणी नक्षत्र के देवता सृष्टिकर्ता ब्रह्मा हैं और इसका प्रतीक रथ या बैलगाड़ी है। इसे चंद्रमा का सबसे प्रिय नक्षत्र कहा गया है, और इसमें चंद्रमा वाले लोग प्रायः स्नेही, आकर्षक, कलाप्रिय और सुख-सौंदर्य के प्रेमी होते हैं। उनमें चीज़ों को बढ़ाने का गुण होता है — बाग़, घर, व्यापार और रिश्ते, सब उनके हाथ में फलते-फूलते हैं। परंपरा रोहिणी को उर्वरता, समृद्धि और स्थिर प्रगति से जोड़ती है, इसलिए कृषि, कला, डिज़ाइन, भोजन और आतिथ्य इसके अनुकूल हैं। इसका स्वभाव कोमल और स्थिर है; इसकी सीख है सुंदरता का आनंद लेना, पर उससे बहुत कसकर न बँधना।",
    },
    "mrigashira": {
        "en": "Mrigashira is ruled by Soma, the Moon, and its symbol is a deer's head — the deer that is always alert, curious and searching. People with the Moon here are often gentle, inquisitive and fond of learning, travel and conversation. They enjoy exploring ideas and places and rarely stop asking questions. Tradition sees Mrigashira as the seeker's nakshatra, which suits research, writing, teaching, trade and any work that rewards curiosity. Its charm is a light, friendly mind; its lesson is to settle on what has been found, so that the search leads somewhere rather than becoming restlessness.",
        "hi": "मृगशिरा नक्षत्र के देवता सोम (चंद्र) हैं और इसका प्रतीक मृग का मुख है — वह हिरण जो सदा सजग, जिज्ञासु और खोज में रहता है। इस नक्षत्र में चंद्रमा वाले लोग प्रायः कोमल, जिज्ञासु और पढ़ने, घूमने व बातचीत के शौक़ीन होते हैं। उन्हें नए विचारों और स्थानों को जानना अच्छा लगता है और वे प्रश्न पूछना कम ही छोड़ते हैं। परंपरा मृगशिरा को खोजी का नक्षत्र मानती है, इसलिए शोध, लेखन, शिक्षण, व्यापार और जिज्ञासा को पुरस्कृत करने वाले काम इसके अनुकूल हैं। इसका आकर्षण हल्का और मैत्रीपूर्ण मन है; इसकी सीख है जो मिल गया उस पर टिकना, ताकि खोज बेचैनी न बने।",
    },
    "ardra": {
        "en": "Ardra is ruled by Rudra, the storm form of Shiva, and symbolised by a teardrop or a diamond. As a storm clears the air and brings rain, people with the Moon here often have a strong, searching intellect and the ability to see through things to the truth. They can feel deeply and are not afraid of change. Tradition links Ardra with renewal after difficulty, so research, technology, writing, counselling and problem-solving suit it well. Its gift is honesty and a sharp mind; its lesson is to let feelings pass like the rain, leaving the ground greener.",
        "hi": "आर्द्रा नक्षत्र के देवता रुद्र हैं — शिव का तूफ़ानी रूप — और इसका प्रतीक अश्रुबिंदु या हीरा है। जैसे तूफ़ान हवा को साफ़ कर वर्षा लाता है, वैसे ही इस नक्षत्र में चंद्रमा वाले लोगों में प्रायः तेज़, खोजी बुद्धि और चीज़ों के भीतर का सत्य देखने की क्षमता होती है। वे गहराई से महसूस करते हैं और परिवर्तन से नहीं डरते। परंपरा आर्द्रा को कठिनाई के बाद नवीनीकरण से जोड़ती है, इसलिए शोध, तकनीक, लेखन, परामर्श और समस्या-समाधान इसके अनुकूल हैं। इसका वरदान सच्चाई और तीक्ष्ण बुद्धि है; इसकी सीख है भावनाओं को वर्षा की तरह बह जाने देना, ताकि धरती और हरी हो।",
    },
    "punarvasu": {
        "en": "Punarvasu is ruled by Aditi, the boundless mother of the gods, and symbolised by a bow and quiver. Its name means \"return of the light\", and people with the Moon here are often optimistic, generous and able to begin again after any setback. They tend to be content with simple things, good-humoured and caring towards family and guests. Tradition sees Punarvasu as a nakshatra of renewal and homecoming, suited to teaching, counselling, writing, travel and caring work. Its blessing is a hopeful, forgiving heart; its lesson is to aim the arrow — to choose a direction and stay with it.",
        "hi": "पुनर्वसु नक्षत्र की देवी देवमाता अदिति हैं और इसका प्रतीक धनुष और तूणीर है। इसके नाम का अर्थ है \"प्रकाश का लौटना\", और इसमें चंद्रमा वाले लोग प्रायः आशावादी, उदार और किसी भी रुकावट के बाद फिर से शुरू करने वाले होते हैं। वे सादगी में संतुष्ट, हँसमुख और परिवार व अतिथियों के प्रति स्नेही होते हैं। परंपरा पुनर्वसु को नवीनीकरण और घर-वापसी का नक्षत्र मानती है, इसलिए शिक्षण, परामर्श, लेखन, यात्रा और सेवा के काम इसके अनुकूल हैं। इसका आशीर्वाद आशा और क्षमा से भरा हृदय है; इसकी सीख है तीर को लक्ष्य देना — दिशा चुनना और उस पर टिके रहना।",
    },
    "pushya": {
        "en": "Pushya is ruled by Brihaspati, the guru of the gods, and symbolised by a cow's udder or a lotus — images of nourishment. It is counted among the most auspicious nakshatras, and people with the Moon here are often caring, dependable, devoted and generous with their time. They like to support others, keep traditions and build something lasting. Tradition links Pushya with nourishment and wisdom, so teaching, counselling, food, social service, finance and spiritual work suit it well. Its gift is a steady, protective kindness; its lesson is to nourish oneself as faithfully as one nourishes others.",
        "hi": "पुष्य नक्षत्र के देवता देवगुरु बृहस्पति हैं और इसका प्रतीक गाय का थन या कमल है — पोषण के प्रतीक। इसे सबसे शुभ नक्षत्रों में गिना जाता है, और इसमें चंद्रमा वाले लोग प्रायः देखभाल करने वाले, भरोसेमंद, श्रद्धावान और समय देने में उदार होते हैं। उन्हें दूसरों का सहारा बनना, परंपराएँ निभाना और कुछ स्थायी बनाना अच्छा लगता है। परंपरा पुष्य को पोषण और ज्ञान से जोड़ती है, इसलिए शिक्षण, परामर्श, भोजन, समाज-सेवा, वित्त और आध्यात्मिक कार्य इसके अनुकूल हैं। इसका वरदान स्थिर, रक्षा करने वाली करुणा है; इसकी सीख है स्वयं का भी उतना ही ध्यान रखना जितना दूसरों का।",
    },
    "ashlesha": {
        "en": "Ashlesha is ruled by the Nagas, the serpent deities, and symbolised by a coiled serpent — an image of kundalini, hidden energy and deep wisdom. People with the Moon here are often perceptive, intelligent and good at understanding what others leave unsaid. They can be persuasive and strategic, with a strong instinct for self-protection. Tradition links Ashlesha with insight and with the healing knowledge of herbs, so psychology, research, medicine, writing and negotiation suit it well. Its gift is penetrating understanding; its lesson is to use that insight to embrace and heal, the way the serpent's coil protects.",
        "hi": "आश्लेषा नक्षत्र के देवता नाग देवता हैं और इसका प्रतीक कुंडली मारे सर्प है — कुंडलिनी, छिपी ऊर्जा और गहरे ज्ञान का प्रतीक। इस नक्षत्र में चंद्रमा वाले लोग प्रायः पारखी, बुद्धिमान और अनकही बातों को समझने में कुशल होते हैं। वे प्रभावशाली और रणनीतिक हो सकते हैं, और अपनी रक्षा की उनमें स्वाभाविक समझ होती है। परंपरा आश्लेषा को अंतर्दृष्टि और औषधियों के ज्ञान से जोड़ती है, इसलिए मनोविज्ञान, शोध, चिकित्सा, लेखन और वार्ता इसके अनुकूल हैं। इसका वरदान गहरी समझ है; इसकी सीख है उस समझ से दूसरों को अपनाना और सँवारना, जैसे सर्प की कुंडली रक्षा करती है।",
    },
    "magha": {
        "en": "Magha is ruled by the Pitris, the ancestors, and symbolised by a royal throne. People with the Moon here often carry a natural dignity, a respect for family and tradition, and a wish to live up to the name they were given. They can be generous leaders who take responsibility for their people. Tradition links Magha with lineage, honour and authority, so leadership, administration, history, law and work that preserves heritage suit it well. Its gift is nobility of heart; its lesson is to wear the crown lightly — to lead through service and to honour the ancestors through good deeds.",
        "hi": "मघा नक्षत्र के देवता पितृ (पूर्वज) हैं और इसका प्रतीक राजसिंहासन है। इस नक्षत्र में चंद्रमा वाले लोगों में प्रायः स्वाभाविक गरिमा, परिवार और परंपरा के प्रति सम्मान, और अपने कुल का नाम ऊँचा रखने की इच्छा होती है। वे उदार नेता हो सकते हैं जो अपने लोगों की ज़िम्मेदारी लेते हैं। परंपरा मघा को वंश, सम्मान और अधिकार से जोड़ती है, इसलिए नेतृत्व, प्रशासन, इतिहास, क़ानून और विरासत सँभालने वाले काम इसके अनुकूल हैं। इसका वरदान हृदय की उदारता है; इसकी सीख है मुकुट को हल्के से धारण करना — सेवा से नेतृत्व करना और अच्छे कर्मों से पूर्वजों का सम्मान करना।",
    },
    "purva-phalguni": {
        "en": "Purva Phalguni is ruled by Bhaga, the god of fortune and marital happiness, and symbolised by the front legs of a bed — an image of rest and enjoyment. People with the Moon here are often warm, charming, creative and fond of celebration, music and good company. They bring people together and know how to relax and enjoy what they have earned. Tradition links Purva Phalguni with love, the arts and leisure, so entertainment, design, hospitality and relationship-centred work suit it well. Its gift is joy that is easily shared; its lesson is balance between pleasure and duty.",
        "hi": "पूर्वा फाल्गुनी नक्षत्र के देवता सौभाग्य और दांपत्य सुख के देव भग हैं और इसका प्रतीक पलंग के अगले पाये हैं — विश्राम और आनंद का प्रतीक। इस नक्षत्र में चंद्रमा वाले लोग प्रायः स्नेही, आकर्षक, रचनात्मक और उत्सव, संगीत व अच्छी संगति के प्रेमी होते हैं। वे लोगों को जोड़ते हैं और अपनी मेहनत की कमाई का आनंद लेना जानते हैं। परंपरा पूर्वा फाल्गुनी को प्रेम, कला और विश्राम से जोड़ती है, इसलिए मनोरंजन, डिज़ाइन, आतिथ्य और संबंधों पर आधारित काम इसके अनुकूल हैं। इसका वरदान बाँटा जाने वाला आनंद है; इसकी सीख है सुख और कर्तव्य में संतुलन।",
    },
    "uttara-phalguni": {
        "en": "Uttara Phalguni is ruled by Aryaman, the god of friendship, contracts and marriage vows, and symbolised by the back legs of a bed. Where its twin Purva Phalguni enjoys, Uttara Phalguni commits. People with the Moon here are often reliable, helpful, fair-minded and loyal to friends and partners. They keep their word and like to be of real use to others. Tradition links this nakshatra with patronage and lasting partnerships, so management, public service, counselling, law and charitable work suit it well. Its gift is dependable kindness; its lesson is to accept help as gracefully as it is given.",
        "hi": "उत्तरा फाल्गुनी नक्षत्र के देवता मित्रता, अनुबंध और विवाह-वचन के देव अर्यमा हैं और इसका प्रतीक पलंग के पिछले पाये हैं। जहाँ इसकी जुड़वाँ पूर्वा फाल्गुनी आनंद लेती है, वहीं उत्तरा फाल्गुनी वचन निभाती है। इस नक्षत्र में चंद्रमा वाले लोग प्रायः भरोसेमंद, मददगार, न्यायप्रिय और मित्रों व जीवनसाथी के प्रति निष्ठावान होते हैं। वे अपनी बात पर टिकते हैं और दूसरों के सच्चे काम आना चाहते हैं। परंपरा इस नक्षत्र को संरक्षण और स्थायी साझेदारी से जोड़ती है, इसलिए प्रबंधन, लोक-सेवा, परामर्श, क़ानून और परोपकार के काम इसके अनुकूल हैं। इसका वरदान भरोसेमंद दयालुता है; इसकी सीख है मदद लेना भी उतनी ही सहजता से जितनी सहजता से दी जाती है।",
    },
    "hasta": {
        "en": "Hasta is ruled by Savitr, the radiant Sun, and symbolised by a hand. People with the Moon here are often skilful, practical, witty and clever with their hands as well as their minds. They like to get things done and can turn an idea into something real. Tradition links Hasta with craftsmanship, healing touch and resourcefulness, so crafts, the arts, surgery, massage, writing, trade and any skilled trade suit it well. Its gift is the ability to make and to mend; its lesson is to hold things with an open hand, trusting that effort brings its own rewards.",
        "hi": "हस्त नक्षत्र के देवता तेजस्वी सविता (सूर्य) हैं और इसका प्रतीक हाथ है। इस नक्षत्र में चंद्रमा वाले लोग प्रायः कुशल, व्यावहारिक, हाज़िरजवाब और हाथ व दिमाग़ दोनों से चतुर होते हैं। उन्हें काम पूरा करना अच्छा लगता है और वे विचार को साकार कर सकते हैं। परंपरा हस्त को कारीगरी, उपचार के स्पर्श और साधन-संपन्नता से जोड़ती है, इसलिए शिल्प, कला, शल्य-चिकित्सा, मालिश, लेखन, व्यापार और कोई भी कौशल वाला काम इसके अनुकूल है। इसका वरदान बनाने और सँवारने की क्षमता है; इसकी सीख है चीज़ों को खुले हाथ से थामना, यह भरोसा रखते हुए कि मेहनत अपना फल स्वयं लाती है।",
    },
    "chitra": {
        "en": "Chitra is ruled by Tvashtr, also known as Vishwakarma, the divine architect, and symbolised by a bright jewel. Its name means \"brilliant\" or \"picture\", and people with the Moon here often have a strong sense of beauty, design and form. They enjoy creating things that are both useful and attractive, and they notice detail. Tradition links Chitra with architecture, the arts and craftsmanship, so design, engineering, fashion, jewellery, photography and planning suit it well. Its gift is the eye of an artist and the hand of a builder; its lesson is to value inner beauty as much as outer polish.",
        "hi": "चित्रा नक्षत्र के देवता दिव्य शिल्पी त्वष्टा (विश्वकर्मा) हैं और इसका प्रतीक चमकता रत्न है। इसके नाम का अर्थ है \"उज्ज्वल\" या \"चित्र\", और इसमें चंद्रमा वाले लोगों में प्रायः सौंदर्य, बनावट और रूप की गहरी समझ होती है। उन्हें ऐसी चीज़ें बनाना अच्छा लगता है जो उपयोगी भी हों और सुंदर भी, और वे बारीकियों पर ध्यान देते हैं। परंपरा चित्रा को वास्तुकला, कला और कारीगरी से जोड़ती है, इसलिए डिज़ाइन, इंजीनियरिंग, फ़ैशन, आभूषण, फ़ोटोग्राफ़ी और योजना के काम इसके अनुकूल हैं। इसका वरदान कलाकार की आँख और निर्माता का हाथ है; इसकी सीख है भीतर की सुंदरता को भी उतना ही महत्व देना जितना बाहरी चमक को।",
    },
    "swati": {
        "en": "Swati is ruled by Vayu, the wind, and symbolised by a young shoot swaying in the breeze — flexible, independent and able to bend without breaking. People with the Moon here often value freedom, fairness and their own way of doing things. They are usually diplomatic, courteous and good at business and negotiation. Tradition links Swati with trade, travel and self-reliance, so commerce, law, diplomacy, communication and independent work suit it well. Its gift is adaptability and a gentle, balanced manner; its lesson is to put down roots, so that the young shoot can grow into a strong tree.",
        "hi": "स्वाति नक्षत्र के देवता वायु देव हैं और इसका प्रतीक हवा में लहराता अंकुर है — लचीला, स्वतंत्र और टूटे बिना झुकने वाला। इस नक्षत्र में चंद्रमा वाले लोग प्रायः स्वतंत्रता, न्याय और अपने ढंग से काम करने को महत्व देते हैं। वे सामान्यतः कूटनीतिक, शिष्ट और व्यापार व बातचीत में कुशल होते हैं। परंपरा स्वाति को व्यापार, यात्रा और आत्मनिर्भरता से जोड़ती है, इसलिए वाणिज्य, क़ानून, कूटनीति, संचार और स्वतंत्र काम इसके अनुकूल हैं। इसका वरदान अनुकूलन क्षमता और कोमल, संतुलित व्यवहार है; इसकी सीख है जड़ें जमाना, ताकि नन्हा अंकुर मज़बूत वृक्ष बन सके।",
    },
    "vishakha": {
        "en": "Vishakha is ruled by Indra and Agni together, and symbolised by a triumphal arch decorated with leaves. People with the Moon here are often purposeful, ambitious and determined to reach the goal they have set. They have energy, conviction and the patience to keep going over a long road. Tradition calls Vishakha the nakshatra of purpose, so leadership, research, politics, sales, teaching and any long-term mission suit it well. Its gift is focus and the ability to inspire others towards a shared aim; its lesson is to enjoy the journey, not only the arch at its end.",
        "hi": "विशाखा नक्षत्र के देवता इन्द्र और अग्नि (इन्द्राग्नि) हैं और इसका प्रतीक पत्तों से सजा तोरण द्वार है। इस नक्षत्र में चंद्रमा वाले लोग प्रायः उद्देश्यपूर्ण, महत्वाकांक्षी और अपने तय किए लक्ष्य तक पहुँचने के लिए दृढ़ होते हैं। उनमें ऊर्जा, विश्वास और लंबी राह पर चलते रहने का धैर्य होता है। परंपरा विशाखा को उद्देश्य का नक्षत्र कहती है, इसलिए नेतृत्व, शोध, राजनीति, बिक्री, शिक्षण और कोई भी दीर्घकालीन लक्ष्य इसके अनुकूल है। इसका वरदान एकाग्रता और दूसरों को साझा लक्ष्य की ओर प्रेरित करने की क्षमता है; इसकी सीख है केवल अंत के तोरण का नहीं, पूरी यात्रा का आनंद लेना।",
    },
    "anuradha": {
        "en": "Anuradha is ruled by Mitra, the god of friendship and cooperation, and symbolised by a lotus that blooms out of muddy water. People with the Moon here are often loyal friends, devoted to their ideals and able to keep going with quiet faith in difficult places. They are good at bringing people together in groups and organisations. Tradition links Anuradha with friendship, devotion and success away from home, so teamwork, organisation, counselling, travel and spiritual practice suit it well. Its gift is the ability to blossom anywhere; its lesson is to be as gentle with oneself as with friends.",
        "hi": "अनुराधा नक्षत्र के देवता मित्रता और सहयोग के देव मित्र हैं और इसका प्रतीक कीचड़ में खिलने वाला कमल है। इस नक्षत्र में चंद्रमा वाले लोग प्रायः निष्ठावान मित्र, अपने आदर्शों के प्रति समर्पित और कठिन जगहों पर भी शांत श्रद्धा से आगे बढ़ने वाले होते हैं। वे लोगों को समूहों और संस्थाओं में जोड़ने में कुशल होते हैं। परंपरा अनुराधा को मित्रता, भक्ति और घर से दूर सफलता से जोड़ती है, इसलिए टीम-कार्य, संगठन, परामर्श, यात्रा और आध्यात्मिक साधना इसके अनुकूल हैं। इसका वरदान कहीं भी खिल उठने की क्षमता है; इसकी सीख है स्वयं के प्रति भी उतना ही कोमल रहना जितना मित्रों के प्रति।",
    },
    "jyeshtha": {
        "en": "Jyeshtha is ruled by Indra, king of the gods, and symbolised by a circular amulet or earring. Its name means \"the eldest\", and people with the Moon here often take on responsibility early, protect those around them and carry a quiet authority. They are resourceful, perceptive and capable under pressure. Tradition links Jyeshtha with seniority and protection, so leadership, management, administration, security and any role that looks after others suit it well. Its gift is courage and capability; its lesson is to lead with humility and to let others share the load rather than carrying everything alone.",
        "hi": "ज्येष्ठा नक्षत्र के देवता देवराज इन्द्र हैं और इसका प्रतीक गोल कुंडल या ताबीज़ है। इसके नाम का अर्थ है \"सबसे बड़ा\", और इसमें चंद्रमा वाले लोग प्रायः जल्दी ज़िम्मेदारी उठाते हैं, आसपास के लोगों की रक्षा करते हैं और उनमें शांत अधिकार-भाव होता है। वे साधन-संपन्न, पारखी और दबाव में भी सक्षम होते हैं। परंपरा ज्येष्ठा को वरिष्ठता और संरक्षण से जोड़ती है, इसलिए नेतृत्व, प्रबंधन, प्रशासन, सुरक्षा और दूसरों की देखभाल वाली भूमिकाएँ इसके अनुकूल हैं। इसका वरदान साहस और योग्यता है; इसकी सीख है विनम्रता से नेतृत्व करना और सारा भार अकेले उठाने के बजाय दूसरों को भी साथ लेना।",
    },
    "mula": {
        "en": "Mula is ruled by Nirriti and symbolised by a bunch of roots. Its name means \"the root\", and people with the Moon here are often drawn to get to the bottom of things — to find the origin of a question, an idea or a tradition. They can be independent, philosophical and unafraid to start again from first principles. Tradition links Mula with investigation and with letting go of what is no longer needed, so research, medicine, philosophy, botany and spiritual inquiry suit it well. Its gift is depth; its lesson is that clearing old ground makes room for new growth.",
        "hi": "मूल नक्षत्र की देवी निऋति हैं और इसका प्रतीक जड़ों का गुच्छा है। इसके नाम का अर्थ है \"जड़\", और इसमें चंद्रमा वाले लोग प्रायः चीज़ों की तह तक जाना चाहते हैं — किसी प्रश्न, विचार या परंपरा का मूल खोजना। वे स्वतंत्र, दार्शनिक और मूल सिद्धांतों से फिर शुरू करने में निडर हो सकते हैं। परंपरा मूल को खोज और अनावश्यक को छोड़ने से जोड़ती है, इसलिए शोध, चिकित्सा, दर्शन, वनस्पति-विज्ञान और आध्यात्मिक जिज्ञासा इसके अनुकूल हैं। इसका वरदान गहराई है; इसकी सीख है कि पुरानी ज़मीन साफ़ करने से नए अंकुर के लिए जगह बनती है।",
    },
    "purva-ashadha": {
        "en": "Purva Ashadha is ruled by Apas, the cosmic waters, and symbolised by a winnowing fan or an elephant tusk. Its name means \"the early invincible\", and people with the Moon here are often confident, persuasive and full of conviction. Like water, they can be gentle and yet wear down any obstacle in time. Tradition links Purva Ashadha with purification and with victory won through persistence, so teaching, law, debate, the arts, shipping and anything to do with water suit it well. Its gift is optimism and inner strength; its lesson is to stay open to other views while holding firm to its own.",
        "hi": "पूर्वाषाढ़ा नक्षत्र के देवता आपः (जल देवता) हैं और इसका प्रतीक सूप (पंखा) या हाथी दाँत है। इसके नाम का अर्थ है \"पहला अजेय\", और इसमें चंद्रमा वाले लोग प्रायः आत्मविश्वासी, प्रभावशाली और दृढ़ विश्वास वाले होते हैं। जल की तरह वे कोमल होकर भी समय के साथ हर बाधा को घिस देते हैं। परंपरा पूर्वाषाढ़ा को शुद्धि और लगन से मिली विजय से जोड़ती है, इसलिए शिक्षण, क़ानून, वाद-विवाद, कला, जहाज़रानी और जल से जुड़े काम इसके अनुकूल हैं। इसका वरदान आशावाद और भीतरी शक्ति है; इसकी सीख है अपनी बात पर दृढ़ रहते हुए दूसरों के विचारों के लिए भी खुले रहना।",
    },
    "uttara-ashadha": {
        "en": "Uttara Ashadha is ruled by the Vishvedevas, the universal gods, and symbolised by an elephant tusk. Its name means \"the later invincible\" — the victory that lasts because it was earned honestly. People with the Moon here are often principled, patient, responsible and respected for their integrity. They take the long view and finish what they commit to. Tradition links Uttara Ashadha with righteous leadership, so government, management, law, teaching and social causes suit it well. Its gift is steady, ethical strength; its lesson is to keep a little lightness and warmth alongside the seriousness of duty.",
        "hi": "उत्तराषाढ़ा नक्षत्र के देवता विश्वेदेव हैं और इसका प्रतीक हाथी दाँत है। इसके नाम का अर्थ है \"बाद का अजेय\" — वह विजय जो टिकती है क्योंकि ईमानदारी से अर्जित की गई। इस नक्षत्र में चंद्रमा वाले लोग प्रायः सिद्धांतवादी, धैर्यवान, ज़िम्मेदार और अपनी ईमानदारी के लिए सम्मानित होते हैं। वे दूर की सोचते हैं और जो वचन देते हैं उसे पूरा करते हैं। परंपरा उत्तराषाढ़ा को धर्मपूर्ण नेतृत्व से जोड़ती है, इसलिए शासन, प्रबंधन, क़ानून, शिक्षण और सामाजिक कार्य इसके अनुकूल हैं। इसका वरदान स्थिर, नैतिक शक्ति है; इसकी सीख है कर्तव्य की गंभीरता के साथ थोड़ा हल्कापन और स्नेह भी बनाए रखना।",
    },
    "shravana": {
        "en": "Shravana is ruled by Vishnu, the preserver, and symbolised by an ear or three footprints. Its name means \"hearing\", and people with the Moon here are often good listeners, eager learners and keepers of knowledge and tradition. They learn by listening and pass on what they have learned. Tradition links Shravana with wisdom gained through study and with connecting people, so teaching, counselling, media, languages, music and travel suit it well. Its gift is attentive understanding and a wish to be useful; its lesson is to listen to one's own inner voice as carefully as to others.",
        "hi": "श्रवण नक्षत्र के देवता पालनकर्ता भगवान विष्णु हैं और इसका प्रतीक कान या तीन पदचिह्न है। इसके नाम का अर्थ है \"सुनना\", और इसमें चंद्रमा वाले लोग प्रायः अच्छे श्रोता, सीखने के उत्सुक और ज्ञान व परंपरा के संरक्षक होते हैं। वे सुनकर सीखते हैं और सीखा हुआ आगे बाँटते हैं। परंपरा श्रवण को अध्ययन से मिले ज्ञान और लोगों को जोड़ने से जोड़ती है, इसलिए शिक्षण, परामर्श, मीडिया, भाषाएँ, संगीत और यात्रा इसके अनुकूल हैं। इसका वरदान ध्यान से समझना और उपयोगी बनने की इच्छा है; इसकी सीख है अपनी भीतरी आवाज़ को भी उतने ही ध्यान से सुनना जितना दूसरों को।",
    },
    "dhanishta": {
        "en": "Dhanishta is ruled by the eight Vasus, gods of abundance, and symbolised by a drum. Its name means \"the wealthiest\", and people with the Moon here often have rhythm, energy and a talent for music, dance or teamwork. They are generous, sociable and able to keep a group moving together. Tradition links Dhanishta with prosperity and with sound, so music, performance, sport, property, finance and community work suit it well. Its gift is the ability to set the beat that others follow; its lesson is to listen as well as play, leaving space for others' rhythms.",
        "hi": "धनिष्ठा नक्षत्र के देवता समृद्धि के देव अष्ट वसु हैं और इसका प्रतीक मृदंग (ढोल) है। इसके नाम का अर्थ है \"सबसे धनवान\", और इसमें चंद्रमा वाले लोगों में प्रायः लय, ऊर्जा और संगीत, नृत्य या टीम-कार्य की प्रतिभा होती है। वे उदार, मिलनसार और समूह को साथ लेकर चलने वाले होते हैं। परंपरा धनिष्ठा को समृद्धि और ध्वनि से जोड़ती है, इसलिए संगीत, प्रदर्शन-कला, खेल, संपत्ति, वित्त और सामुदायिक कार्य इसके अनुकूल हैं। इसका वरदान वह ताल देना है जिस पर दूसरे चलें; इसकी सीख है बजाने के साथ सुनना भी, ताकि दूसरों की लय के लिए भी जगह रहे।",
    },
    "shatabhisha": {
        "en": "Shatabhisha is ruled by Varuna, lord of the cosmic waters and of truth, and symbolised by an empty circle. Its name means \"a hundred healers\", and people with the Moon here are often independent thinkers, private, truthful and drawn to understanding how things really work. They can see patterns others miss. Tradition links Shatabhisha with healing and with the search for hidden truth, so medicine, research, science, technology, astronomy and alternative healing suit it well. Its gift is clear, original insight; its lesson is to let others into the circle, sharing what is understood with warmth.",
        "hi": "शतभिषा नक्षत्र के देवता जल और सत्य के स्वामी वरुण देव हैं और इसका प्रतीक रिक्त वृत्त है। इसके नाम का अर्थ है \"सौ वैद्य\", और इसमें चंद्रमा वाले लोग प्रायः स्वतंत्र विचारक, एकांतप्रिय, सत्यवादी और चीज़ों के वास्तविक रहस्य को समझने के इच्छुक होते हैं। वे ऐसे पैटर्न देख लेते हैं जो दूसरों से छूट जाते हैं। परंपरा शतभिषा को उपचार और छिपे सत्य की खोज से जोड़ती है, इसलिए चिकित्सा, शोध, विज्ञान, तकनीक, खगोल और वैकल्पिक उपचार इसके अनुकूल हैं। इसका वरदान स्पष्ट, मौलिक अंतर्दृष्टि है; इसकी सीख है दूसरों को भी उस वृत्त में आने देना और अपनी समझ स्नेह से बाँटना।",
    },
    "purva-bhadrapada": {
        "en": "Purva Bhadrapada is ruled by Aja Ekapada, the one-footed form of Shiva, and symbolised by swords or the front legs of a cot. People with the Moon here are often idealistic, intense and willing to give themselves fully to a cause they believe in. They can be eloquent, generous and deeply spiritual. Tradition links Purva Bhadrapada with transformation and with the fire of tapas — sincere effort for a higher aim — so social reform, philosophy, writing, research and spiritual life suit it well. Its gift is passionate commitment; its lesson is to temper intensity with patience and calm.",
        "hi": "पूर्व भाद्रपद नक्षत्र के देवता अज एकपाद (शिव का एकपाद रूप) हैं और इसका प्रतीक तलवार या खाट के अगले पाये हैं। इस नक्षत्र में चंद्रमा वाले लोग प्रायः आदर्शवादी, तीव्र और जिस उद्देश्य में विश्वास करते हैं उसके लिए पूरी तरह समर्पित होने वाले होते हैं। वे वाक्पटु, उदार और गहरे आध्यात्मिक हो सकते हैं। परंपरा पूर्व भाद्रपद को परिवर्तन और तप की अग्नि — ऊँचे लक्ष्य के लिए सच्चे प्रयास — से जोड़ती है, इसलिए समाज-सुधार, दर्शन, लेखन, शोध और आध्यात्मिक जीवन इसके अनुकूल हैं। इसका वरदान उत्कट समर्पण है; इसकी सीख है तीव्रता को धैर्य और शांति से संतुलित करना।",
    },
    "uttara-bhadrapada": {
        "en": "Uttara Bhadrapada is ruled by Ahir Budhnya, the serpent of the deep waters, and symbolised by the back legs of a cot or twins. Where Purva Bhadrapada burns, Uttara Bhadrapada settles into calm depth. People with the Moon here are often wise, patient, composed and compassionate, with self-control and a gift for counsel. They tend to think before they speak and are steady in difficult times. Tradition links this nakshatra with depth, renunciation and kindness, so counselling, charity, teaching, research and spiritual practice suit it well. Its gift is serene wisdom; its lesson is to share it actively, not only privately.",
        "hi": "उत्तर भाद्रपद नक्षत्र के देवता अहिर्बुध्न्य (गहरे जल के नाग) हैं और इसका प्रतीक खाट के पिछले पाये या जुड़वाँ हैं। जहाँ पूर्व भाद्रपद में अग्नि है, वहीं उत्तर भाद्रपद शांत गहराई में स्थिर होता है। इस नक्षत्र में चंद्रमा वाले लोग प्रायः ज्ञानी, धैर्यवान, संयमी और करुणामय होते हैं, और उनमें आत्म-नियंत्रण व अच्छी सलाह देने का गुण होता है। वे बोलने से पहले सोचते हैं और कठिन समय में स्थिर रहते हैं। परंपरा इस नक्षत्र को गहराई, त्याग और दयालुता से जोड़ती है, इसलिए परामर्श, दान, शिक्षण, शोध और आध्यात्मिक साधना इसके अनुकूल हैं। इसका वरदान शांत ज्ञान है; इसकी सीख है उसे केवल मन में न रखकर सक्रियता से बाँटना।",
    },
    "revati": {
        "en": "Revati, the last nakshatra, is ruled by Pushan, the nourisher who guides travellers and protects herds on their way, and symbolised by a fish. People with the Moon here are often gentle, kind, imaginative and protective of the weak, with a love of animals, art and music. They make good companions on any journey and help others reach their destination safely. Tradition links Revati with safe journeys, prosperity and completion, so caring work, the arts, travel, hospitality and spiritual life suit it well. Its gift is compassion and faith; its lesson is to care for oneself while caring for everyone else.",
        "hi": "रेवती अंतिम नक्षत्र है, जिसके देवता पूषा हैं — पोषण करने वाले, यात्रियों के मार्गदर्शक और राह में पशुओं के रक्षक — और इसका प्रतीक मछली है। इस नक्षत्र में चंद्रमा वाले लोग प्रायः कोमल, दयालु, कल्पनाशील और निर्बलों के रक्षक होते हैं, जिन्हें पशु, कला और संगीत प्रिय होते हैं। वे किसी भी यात्रा के अच्छे साथी होते हैं और दूसरों को सुरक्षित मंज़िल तक पहुँचने में मदद करते हैं। परंपरा रेवती को सुरक्षित यात्रा, समृद्धि और पूर्णता से जोड़ती है, इसलिए सेवा, कला, यात्रा, आतिथ्य और आध्यात्मिक जीवन इसके अनुकूल हैं। इसका वरदान करुणा और श्रद्धा है; इसकी सीख है सबका ध्यान रखते हुए स्वयं का भी ध्यान रखना।",
    },
}

RASHI_TRAITS: dict[str, dict[str, str]] = {
    "mesh": {
        "en": "Mesh (Aries) is the first rashi, a movable fire sign ruled by Mars. People with the Moon in Mesh are often energetic, direct, courageous and quick to act — natural starters who enjoy a challenge and like to lead from the front. They are honest about their feelings and recover quickly from setbacks. Their emotional life is warm and spontaneous, and they bring enthusiasm wherever they go. Work that rewards initiative — sport, the armed forces, engineering, entrepreneurship, surgery — often suits them. Their growth lies in patience and in listening before acting, so that their courage is matched by care for others.",
        "hi": "मेष पहली राशि है — मंगल के स्वामित्व वाली चर अग्नि राशि। मेष राशि (चंद्र राशि) वाले लोग प्रायः ऊर्जावान, स्पष्टवादी, साहसी और तुरंत कदम उठाने वाले होते हैं — स्वाभाविक रूप से शुरुआत करने वाले, जिन्हें चुनौती पसंद है और जो आगे रहकर नेतृत्व करते हैं। वे अपनी भावनाओं के प्रति ईमानदार होते हैं और रुकावटों से जल्दी उबर जाते हैं। उनका भावनात्मक जीवन गर्मजोशी और सहजता से भरा होता है, और वे जहाँ जाते हैं उत्साह ले जाते हैं। पहल को पुरस्कृत करने वाले काम — खेल, सेना, इंजीनियरिंग, उद्यम, शल्य-चिकित्सा — प्रायः उनके अनुकूल होते हैं। उनका विकास धैर्य में और कदम उठाने से पहले सुनने में है, ताकि उनके साहस के साथ दूसरों की परवाह भी हो।",
    },
    "vrishabh": {
        "en": "Vrishabh (Taurus) is a fixed earth sign ruled by Venus, and the Moon is exalted here. People with the Moon in Vrishabh are often calm, patient, loyal and steady, with a love of comfort, good food, music and beautiful things. They build slowly and surely, and what they build tends to last. Emotionally they are dependable and affectionate, preferring security to drama. Finance, agriculture, the arts, food, design and any work that rewards persistence often suit them. Their growth lies in flexibility — welcoming change when it comes, and holding possessions and opinions a little more lightly.",
        "hi": "वृषभ स्थिर पृथ्वी राशि है, जिसके स्वामी शुक्र हैं, और इसमें चंद्रमा उच्च का होता है। वृषभ चंद्र राशि वाले लोग प्रायः शांत, धैर्यवान, निष्ठावान और स्थिर होते हैं, और उन्हें सुख-सुविधा, अच्छा भोजन, संगीत और सुंदर चीज़ें प्रिय होती हैं। वे धीरे-धीरे पर पक्का बनाते हैं, और जो बनाते हैं वह टिकता है। भावनात्मक रूप से वे भरोसेमंद और स्नेही होते हैं, और नाटकीयता से अधिक सुरक्षा पसंद करते हैं। वित्त, कृषि, कला, भोजन, डिज़ाइन और लगन माँगने वाले काम प्रायः उनके अनुकूल होते हैं। उनका विकास लचीलेपन में है — परिवर्तन आने पर उसका स्वागत करना, और वस्तुओं व विचारों को थोड़ा हल्के से थामना।",
    },
    "mithun": {
        "en": "Mithun (Gemini) is a dual air sign ruled by Mercury. People with the Moon in Mithun are often curious, witty, talkative and quick to learn, with many interests and a gift for connecting ideas and people. They enjoy conversation, reading, travel and anything that keeps the mind busy. Emotionally they need variety and a partner who is also a friend they can talk to. Writing, teaching, media, sales, technology and trade often suit them. Their growth lies in depth and focus — choosing a few things and seeing them through — and in giving their own feelings the attention they give to ideas.",
        "hi": "मिथुन बुध के स्वामित्व वाली द्विस्वभाव वायु राशि है। मिथुन चंद्र राशि वाले लोग प्रायः जिज्ञासु, हाज़िरजवाब, बातूनी और जल्दी सीखने वाले होते हैं, जिनकी अनेक रुचियाँ होती हैं और जो विचारों व लोगों को जोड़ने में कुशल होते हैं। उन्हें बातचीत, पढ़ना, यात्रा और मन को व्यस्त रखने वाली हर चीज़ अच्छी लगती है। भावनात्मक रूप से उन्हें विविधता और ऐसा साथी चाहिए जो मित्र भी हो, जिससे वे खुलकर बात कर सकें। लेखन, शिक्षण, मीडिया, बिक्री, तकनीक और व्यापार प्रायः उनके अनुकूल होते हैं। उनका विकास गहराई और एकाग्रता में है — कुछ चीज़ें चुनकर उन्हें पूरा करना — और अपनी भावनाओं को भी उतना ध्यान देना जितना विचारों को।",
    },
    "kark": {
        "en": "Kark (Cancer) is a movable water sign ruled by the Moon itself, so the Moon is at home here. People with the Moon in Kark are often caring, sensitive, intuitive and devoted to family and home. They remember kindness, protect those they love and create warmth wherever they live. Their moods can change like the tides, but their loyalty runs deep. Nursing, teaching, hospitality, food, real estate, counselling and public service often suit them. Their growth lies in trusting their own strength, letting go of old hurts and allowing others to care for them in return.",
        "hi": "कर्क चर जल राशि है, जिसके स्वामी स्वयं चंद्रमा हैं, इसलिए यहाँ चंद्रमा अपने घर में होता है। कर्क चंद्र राशि वाले लोग प्रायः देखभाल करने वाले, संवेदनशील, अंतर्ज्ञानी और परिवार व घर के प्रति समर्पित होते हैं। वे भलाई को याद रखते हैं, अपनों की रक्षा करते हैं और जहाँ रहते हैं वहाँ अपनापन भर देते हैं। उनका मन ज्वार-भाटे की तरह बदल सकता है, पर उनकी निष्ठा गहरी होती है। नर्सिंग, शिक्षण, आतिथ्य, भोजन, संपत्ति, परामर्श और लोक-सेवा प्रायः उनके अनुकूल होते हैं। उनका विकास अपनी शक्ति पर भरोसा करने, पुरानी चोटों को छोड़ने और दूसरों को भी अपनी देखभाल करने देने में है।",
    },
    "simha": {
        "en": "Simha (Leo) is a fixed fire sign ruled by the Sun. People with the Moon in Simha are often generous, dignified, confident and warm-hearted, with a natural sense of leadership and a love of recognition. They are loyal to those who trust them and protective of their family and friends. Emotionally they are proud and open-hearted, and they shine when appreciated. Leadership, administration, politics, the performing arts, teaching and government service often suit them. Their growth lies in humility — letting others share the stage, and finding confidence from within rather than from applause.",
        "hi": "सिंह सूर्य के स्वामित्व वाली स्थिर अग्नि राशि है। सिंह चंद्र राशि वाले लोग प्रायः उदार, गरिमामय, आत्मविश्वासी और खुले दिल के होते हैं, उनमें स्वाभाविक नेतृत्व होता है और उन्हें सम्मान अच्छा लगता है। जो उन पर भरोसा करें, उनके प्रति वे निष्ठावान होते हैं और परिवार व मित्रों की रक्षा करते हैं। भावनात्मक रूप से वे स्वाभिमानी और उदार हृदय होते हैं, और सराहना मिलने पर खिल उठते हैं। नेतृत्व, प्रशासन, राजनीति, प्रदर्शन-कला, शिक्षण और सरकारी सेवा प्रायः उनके अनुकूल होते हैं। उनका विकास विनम्रता में है — दूसरों को भी मंच पर जगह देना, और तालियों से नहीं, भीतर से आत्मविश्वास पाना।",
    },
    "kanya": {
        "en": "Kanya (Virgo) is a dual earth sign ruled by Mercury. People with the Moon in Kanya are often practical, analytical, modest and helpful, with an eye for detail and a wish to make things work properly. They show care through service — fixing, organising and looking after the small things others overlook. Emotionally they can be reserved, but they are deeply dependable. Medicine, accounting, research, editing, nutrition, teaching and any precise craft often suit them. Their growth lies in self-acceptance: being as kind to their own imperfections as they are patient with other people's needs.",
        "hi": "कन्या बुध के स्वामित्व वाली द्विस्वभाव पृथ्वी राशि है। कन्या चंद्र राशि वाले लोग प्रायः व्यावहारिक, विश्लेषणशील, विनम्र और मददगार होते हैं, बारीकियों पर उनकी नज़र रहती है और वे चाहते हैं कि हर काम ठीक से हो। वे सेवा से अपनी परवाह दिखाते हैं — सुधारना, व्यवस्थित करना और उन छोटी बातों का ध्यान रखना जो दूसरे भूल जाते हैं। भावनात्मक रूप से वे संकोची हो सकते हैं, पर बहुत भरोसेमंद होते हैं। चिकित्सा, लेखा, शोध, संपादन, पोषण, शिक्षण और कोई भी सटीक कौशल प्रायः उनके अनुकूल होता है। उनका विकास आत्म-स्वीकृति में है: अपनी कमियों के प्रति भी उतना ही दयालु होना जितना वे दूसरों की ज़रूरतों के प्रति धैर्यवान होते हैं।",
    },
    "tula": {
        "en": "Tula (Libra) is a movable air sign ruled by Venus, symbolised by the scales. People with the Moon in Tula are often gracious, fair-minded, sociable and diplomatic, with a strong sense of beauty and justice. They value harmony in relationships and are good at seeing both sides of a question. Emotionally they need partnership and feel most at ease when things around them are balanced. Law, diplomacy, design, fashion, the arts, counselling and business partnerships often suit them. Their growth lies in decisiveness — trusting their own judgement and accepting that a little disagreement can be healthy.",
        "hi": "तुला शुक्र के स्वामित्व वाली चर वायु राशि है, जिसका प्रतीक तराज़ू है। तुला चंद्र राशि वाले लोग प्रायः शालीन, न्यायप्रिय, मिलनसार और कूटनीतिक होते हैं, जिनमें सौंदर्य और न्याय की गहरी समझ होती है। वे रिश्तों में सामंजस्य को महत्व देते हैं और किसी भी प्रश्न के दोनों पक्ष देख पाते हैं। भावनात्मक रूप से उन्हें साथी की ज़रूरत होती है और जब आसपास संतुलन हो तब वे सबसे सहज रहते हैं। क़ानून, कूटनीति, डिज़ाइन, फ़ैशन, कला, परामर्श और व्यापारिक साझेदारी प्रायः उनके अनुकूल होते हैं। उनका विकास निर्णय-क्षमता में है — अपने विवेक पर भरोसा करना, और यह मानना कि थोड़ी असहमति भी स्वस्थ हो सकती है।",
    },
    "vrishchik": {
        "en": "Vrishchik (Scorpio) is a fixed water sign ruled by Mars. People with the Moon in Vrishchik are often intense, perceptive, determined and deeply loyal, with feelings that run far below the surface. They are not satisfied with appearances and want to understand what is really going on. Once they commit — to a person, a cause or a goal — they rarely let go. Research, investigation, medicine, psychology, finance and crisis work often suit them. Their growth lies in trust and forgiveness: letting others in, and allowing old feelings to transform rather than be held.",
        "hi": "वृश्चिक मंगल के स्वामित्व वाली स्थिर जल राशि है। वृश्चिक चंद्र राशि वाले लोग प्रायः गहन, पारखी, दृढ़निश्चयी और गहरे निष्ठावान होते हैं, जिनकी भावनाएँ सतह से बहुत नीचे बहती हैं। वे दिखावे से संतुष्ट नहीं होते और जानना चाहते हैं कि वास्तव में क्या हो रहा है। एक बार किसी व्यक्ति, उद्देश्य या लक्ष्य से जुड़ जाएँ तो शायद ही छोड़ते हैं। शोध, जाँच-पड़ताल, चिकित्सा, मनोविज्ञान, वित्त और संकट-प्रबंधन प्रायः उनके अनुकूल होते हैं। उनका विकास भरोसे और क्षमा में है: दूसरों को भीतर आने देना, और पुरानी भावनाओं को पकड़े रहने के बजाय बदलने देना।",
    },
    "dhanu": {
        "en": "Dhanu (Sagittarius) is a dual fire sign ruled by Jupiter, symbolised by the archer. People with the Moon in Dhanu are often optimistic, honest, generous and philosophical, with a love of learning, travel and freedom. They look for meaning in life and enjoy sharing what they have learned. Emotionally they are open and cheerful, and they need room to grow. Teaching, law, religion and philosophy, publishing, travel and sport often suit them. Their growth lies in following through — giving the same attention to the details of daily life that they give to big ideas and distant horizons.",
        "hi": "धनु गुरु के स्वामित्व वाली द्विस्वभाव अग्नि राशि है, जिसका प्रतीक धनुर्धर है। धनु चंद्र राशि वाले लोग प्रायः आशावादी, ईमानदार, उदार और दार्शनिक होते हैं, जिन्हें ज्ञान, यात्रा और स्वतंत्रता प्रिय होती है। वे जीवन में अर्थ खोजते हैं और जो सीखा है उसे बाँटना पसंद करते हैं। भावनात्मक रूप से वे खुले और प्रसन्नचित्त होते हैं, और उन्हें बढ़ने के लिए खुली जगह चाहिए। शिक्षण, क़ानून, धर्म और दर्शन, प्रकाशन, यात्रा और खेल प्रायः उनके अनुकूल होते हैं। उनका विकास काम को पूरा करने में है — रोज़मर्रा की बारीकियों को भी उतना ही ध्यान देना जितना बड़े विचारों और दूर के क्षितिज को।",
    },
    "makar": {
        "en": "Makar (Capricorn) is a movable earth sign ruled by Saturn. People with the Moon in Makar are often responsible, disciplined, practical and ambitious in a patient, long-term way. They take duty seriously, work steadily and earn respect over time. Emotionally they can seem reserved, but they show love through reliability and quiet support. Administration, management, engineering, government service, finance and any field that rewards perseverance often suit them. Their growth lies in warmth and rest — allowing themselves joy along the way, and remembering that their worth is not measured only by achievement.",
        "hi": "मकर शनि के स्वामित्व वाली चर पृथ्वी राशि है। मकर चंद्र राशि वाले लोग प्रायः ज़िम्मेदार, अनुशासित, व्यावहारिक और धैर्य के साथ दूरगामी महत्वाकांक्षा वाले होते हैं। वे कर्तव्य को गंभीरता से लेते हैं, लगातार मेहनत करते हैं और समय के साथ सम्मान कमाते हैं। भावनात्मक रूप से वे संकोची लग सकते हैं, पर वे भरोसे और चुपचाप साथ देकर अपना स्नेह दिखाते हैं। प्रशासन, प्रबंधन, इंजीनियरिंग, सरकारी सेवा, वित्त और लगन को पुरस्कृत करने वाला हर क्षेत्र प्रायः उनके अनुकूल होता है। उनका विकास गर्मजोशी और विश्राम में है — रास्ते में आनंद लेने देना, और यह याद रखना कि उनका मूल्य केवल उपलब्धियों से नहीं मापा जाता।",
    },
    "kumbh": {
        "en": "Kumbh (Aquarius) is a fixed air sign ruled by Saturn, symbolised by the water-bearer who pours knowledge out for all. People with the Moon in Kumbh are often independent, humanitarian, inventive and loyal to friends and ideals. They think about the wider community and enjoy new ideas, science and reform. Emotionally they value friendship and freedom, and they show care through principle and action. Science, technology, social work, research, education and community organisations often suit them. Their growth lies in closeness — letting their warmth show to individuals as well as to humanity as a whole.",
        "hi": "कुंभ शनि के स्वामित्व वाली स्थिर वायु राशि है, जिसका प्रतीक वह कुंभधारी है जो सबके लिए ज्ञान उड़ेलता है। कुंभ चंद्र राशि वाले लोग प्रायः स्वतंत्र, मानवतावादी, आविष्कारशील और मित्रों व आदर्शों के प्रति निष्ठावान होते हैं। वे बड़े समाज के बारे में सोचते हैं और उन्हें नए विचार, विज्ञान और सुधार अच्छे लगते हैं। भावनात्मक रूप से वे मित्रता और स्वतंत्रता को महत्व देते हैं, और सिद्धांत व कर्म से अपनी परवाह दिखाते हैं। विज्ञान, तकनीक, समाज-सेवा, शोध, शिक्षा और सामुदायिक संगठन प्रायः उनके अनुकूल होते हैं। उनका विकास निकटता में है — अपनी गर्मजोशी पूरी मानवता के साथ-साथ व्यक्तियों को भी दिखाना।",
    },
    "meen": {
        "en": "Meen (Pisces) is a dual water sign ruled by Jupiter, the last of the twelve rashis. People with the Moon in Meen are often compassionate, imaginative, gentle and spiritually inclined, with a deep sensitivity to the feelings of others. They forgive easily, help without being asked and are moved by music, art and devotion. Emotionally they are open-hearted and intuitive. Healing, counselling, the arts, music, charity, teaching and spiritual work often suit them. Their growth lies in healthy boundaries — caring for others without losing themselves, and turning their rich imagination into practical action.",
        "hi": "मीन गुरु के स्वामित्व वाली द्विस्वभाव जल राशि है, बारह राशियों में अंतिम। मीन चंद्र राशि वाले लोग प्रायः करुणामय, कल्पनाशील, कोमल और आध्यात्मिक झुकाव वाले होते हैं, जो दूसरों की भावनाओं के प्रति गहरे संवेदनशील होते हैं। वे जल्दी क्षमा कर देते हैं, बिना कहे मदद करते हैं और संगीत, कला व भक्ति से भाव-विभोर हो जाते हैं। भावनात्मक रूप से वे खुले दिल और अंतर्ज्ञानी होते हैं। उपचार, परामर्श, कला, संगीत, दान, शिक्षण और आध्यात्मिक कार्य प्रायः उनके अनुकूल होते हैं। उनका विकास स्वस्थ सीमाओं में है — स्वयं को खोए बिना दूसरों की देखभाल करना, और अपनी समृद्ध कल्पना को व्यावहारिक कर्म में बदलना।",
    },
}
