"""Short trait descriptions for the nakshatra and rashi pages (DIVASTRO-115).

Written for the public pages: 80–150 words in English, the same substance in
Hindi, respectful and never fear-based — no predictions of loss, illness or
"bad" stars, no promises. The gist follows the traditional character of each
nakshatra (its deity and symbol) and of each sign (its lord, element and
quality) as the standard jyotisha texts describe them; they are tendencies
people born with the Moon there often recognise, not verdicts. The test
checks the word counts, the slugs and a fear-word list.
"""

from __future__ import annotations

NAKSHATRA_TRAITS: dict[str, dict[str, str]] = {
    "ashwini": {
        "en": "Ashwini is the first nakshatra, ruled by the Ashwini Kumaras, the twin healers of the gods, and symbolised by a horse's head. People with the Moon here are often quick, energetic and eager to begin things — the first to help, the first to try something new. Tradition links Ashwini with healing, speed and fresh starts, so many feel drawn to medicine, sport, travel or any work that needs swift, practical action. The gift of this nakshatra is initiative and a youthful optimism; the lesson is patience, finishing what was started with the same enthusiasm with which it began.",
        "hi": "अश्विनी पहला नक्षत्र है, जिसके देवता देवताओं के वैद्य अश्विनी कुमार हैं और प्रतीक अश्व का मुख है। इस नक्षत्र में चंद्रमा वाले लोग प्रायः फुर्तीले, ऊर्जावान और नई शुरुआत के लिए उत्सुक होते हैं — मदद में सबसे आगे, कुछ नया करने में सबसे पहले। परंपरा अश्विनी को उपचार, गति और नए आरंभ से जोड़ती है, इसलिए कई लोगों का झुकाव चिकित्सा, खेल, यात्रा या ऐसे काम की ओर होता है जिसमें शीघ्र और व्यावहारिक कदम चाहिए। इस नक्षत्र का वरदान पहल और युवा आशावाद है; इसकी सीख धैर्य है — जो काम जिस उत्साह से शुरू हो, उसी उत्साह से पूरा भी हो।",
    },
    "bharani": {
        "en": "Bharani is ruled by Yama, the lord of dharma, and its symbol is the yoni, the womb that carries and protects new life. People with the Moon here often have strong will, deep feelings and a serious sense of responsibility. They tend to carry their commitments through to the end and are not easily swayed. Tradition sees Bharani as the nakshatra of bearing and nurturing — holding something until it is ready to be born — so creativity, family, art and work that asks for endurance suit it well. Its strength is steadfastness; its lesson is balancing desire with restraint and kindness.",
        "hi": "भरणी नक्षत्र के देवता धर्मराज यम हैं और इसका प्रतीक योनि है — वह गर्भ जो नए जीवन को धारण और सुरक्षित करता है। इस नक्षत्र में चंद्रमा वाले लोगों में प्रायः दृढ़ इच्छाशक्ति, गहरी भावनाएँ और ज़िम्मेदारी का गंभीर भाव होता है। वे अपने वचन अंत तक निभाते हैं और आसानी से डिगते नहीं। परंपरा भरणी को धारण और पोषण का नक्षत्र मानती है — किसी चीज़ को तब तक सँभालना जब तक वह जन्म लेने को तैयार न हो — इसलिए रचनात्मकता, परिवार, कला और धैर्य माँगने वाले काम इसके अनुकूल हैं। इसकी शक्ति स्थिरता है; इसकी सीख इच्छा और संयम में संतुलन रखना है।",
    },
    "krittika": {
        "en": "Krittika is ruled by Agni, the sacred fire, and symbolised by a razor or a flame. Fire purifies and cuts through confusion, and people with the Moon here are often direct, principled and sharp in judgement. They can be protective of those they love and are willing to say what needs to be said. Krittika is also the nakshatra of the six mothers who nursed Kartikeya, so beneath the sharpness there is real warmth and care. Teaching, cooking, leadership and any work that needs clarity suit it. Its lesson is to let the fire warm and guide rather than burn.",
        "hi": "कृत्तिका नक्षत्र के देवता पवित्र अग्नि हैं और इसका प्रतीक छुरा या अग्निशिखा है। अग्नि शुद्ध करती है और भ्रम को काटती है, और इस नक्षत्र में चंद्रमा वाले लोग प्रायः स्पष्टवादी, सिद्धांतवादी और तीक्ष्ण बुद्धि वाले होते हैं। वे अपनों की रक्षा करते हैं और जो कहना ज़रूरी हो, कह देते हैं। कृत्तिका उन छह माताओं का भी नक्षत्र है जिन्होंने कार्तिकेय का पालन किया, इसलिए तीखेपन के नीचे सच्ची ममता और स्नेह होता है। शिक्षण, रसोई, नेतृत्व और स्पष्टता माँगने वाले काम इसके अनुकूल हैं। इसकी सीख है कि अग्नि जलाए नहीं, बल्कि गर्माहट और मार्ग दे।",
    },
    "rohini": {
        "en": "Rohini is ruled by Brahma, the creator, and symbolised by a chariot or ox-cart. It is said to be the Moon's favourite nakshatra, and people with the Moon here are often warm, attractive, artistic and fond of comfort and beauty. They have a gift for making things grow — gardens, homes, businesses and relationships. Tradition associates Rohini with fertility, abundance and steady progress, so agriculture, the arts, design, food and hospitality suit it well. Its nature is gentle and settled; its lesson is to enjoy what is beautiful without holding on too tightly to it.",
        "hi": "रोहिणी नक्षत्र के देवता सृष्टिकर्ता ब्रह्मा हैं और इसका प्रतीक रथ या बैलगाड़ी है। इसे चंद्रमा का सबसे प्रिय नक्षत्र कहा गया है, और इसमें चंद्रमा वाले लोग प्रायः स्नेही, आकर्षक, कलाप्रिय और सुख-सौंदर्य के प्रेमी होते हैं। उनमें चीज़ों को बढ़ाने का गुण होता है — बाग़, घर, व्यापार और रिश्ते, सब उनके हाथ में फलते-फूलते हैं। परंपरा रोहिणी को उर्वरता, समृद्धि और स्थिर प्रगति से जोड़ती है, इसलिए कृषि, कला, डिज़ाइन, भोजन और आतिथ्य इसके अनुकूल हैं। इसका स्वभाव कोमल और स्थिर है; इसकी सीख है सुंदरता का आनंद लेना, पर उससे बहुत कसकर न बँधना।",
    },
    "mrigashira": {
        "en": "Mrigashira is ruled by Soma, the Moon, and its symbol is a deer's head — the deer that is always alert, curious and searching. People with the Moon here are often gentle, inquisitive and fond of learning, travel and conversation. They enjoy exploring ideas and places and rarely stop asking questions. Tradition sees Mrigashira as the seeker's nakshatra, which suits research, writing, teaching, trade and any work that rewards curiosity. Its charm is a light, friendly mind; its lesson is to settle on what has been found, so that the search leads somewhere rather than becoming restlessness.",
        "hi": "मृगशिरा नक्षत्र के देवता सोम (चंद्र) हैं और इसका प्रतीक मृग का मुख है — वह हिरण जो सदा सजग, जिज्ञासु और खोज में रहता है। इस नक्षत्र में चंद्रमा वाले लोग प्रायः कोमल, जिज्ञासु और पढ़ने, घूमने व बातचीत के शौक़ीन होते हैं। उन्हें नए विचारों और स्थानों को जानना अच्छा लगता है और वे प्रश्न पूछना कम ही छोड़ते हैं। परंपरा मृगशिरा को खोजी का नक्षत्र मानती है, इसलिए शोध, लेखन, शिक्षण, व्यापार और जिज्ञासा को पुरस्कृत करने वाले काम इसके अनुकूल हैं। इसका आकर्षण हल्का और मैत्रीपूर्ण मन है; इसकी सीख है जो मिल गया उस पर टिकना, ताकि खोज बेचैनी न बने।",
    },
    "ardra": {
        "en": "Ardra is ruled by Rudra, the storm form of Shiva, and symbolised by a teardrop or a diamond. As a storm clears the air and brings rain, people with the Moon here often have a strong, searching intellect and the ability to see through things to the truth. They can feel deeply and are not afraid of change. Tradition links Ardra with renewal after difficulty, so research, technology, writing, counselling and problem-solving suit it well. Its gift is honesty and a sharp mind; its lesson is to let feelings pass like the rain, leaving the ground greener.",
        "hi": "आर्द्रा नक्षत्र के देवता रुद्र हैं — शिव का तूफ़ानी रूप — और इसका प्रतीक अश्रुबिंदु या हीरा है। जैसे तूफ़ान हवा को साफ़ कर वर्षा लाता है, वैसे ही इस नक्षत्र में चंद्रमा वाले लोगों में प्रायः तेज़, खोजी बुद्धि और चीज़ों के भीतर का सत्य देखने की क्षमता होती है। वे गहराई से महसूस करते हैं और परिवर्तन से नहीं डरते। परंपरा आर्द्रा को कठिनाई के बाद नवीनीकरण से जोड़ती है, इसलिए शोध, तकनीक, लेखन, परामर्श और समस्या-समाधान इसके अनुकूल हैं। इसका वरदान सच्चाई और तीक्ष्ण बुद्धि है; इसकी सीख है भावनाओं को वर्षा की तरह बह जाने देना, ताकि धरती और हरी हो।",
    },
    "punarvasu": {
        "en": "Punarvasu is ruled by Aditi, the boundless mother of the gods, and symbolised by a bow and quiver. Its name means \"return of the light\", and people with the Moon here are often optimistic, generous and able to begin again after any setback. They tend to be content with simple things, good-humoured and caring towards family and guests. Tradition sees Punarvasu as a nakshatra of renewal and homecoming, suited to teaching, counselling, writing, travel and caring work. Its blessing is a hopeful, forgiving heart; its lesson is to aim the arrow — to choose a direction and stay with it.",
        "hi": "पुनर्वसु नक्षत्र की देवी देवमाता अदिति हैं और इसका प्रतीक धनुष और तूणीर है। इसके नाम का अर्थ है \"प्रकाश का लौटना\", और इसमें चंद्रमा वाले लोग प्रायः आशावादी, उदार और किसी भी रुकावट के बाद फिर से शुरू करने वाले होते हैं। वे सादगी में संतुष्ट, हँसमुख और परिवार व अतिथियों के प्रति स्नेही होते हैं। परंपरा पुनर्वसु को नवीनीकरण और घर-वापसी का नक्षत्र मानती है, इसलिए शिक्षण, परामर्श, लेखन, यात्रा और सेवा के काम इसके अनुकूल हैं। इसका आशीर्वाद आशा और क्षमा से भरा हृदय है; इसकी सीख है तीर को लक्ष्य देना — दिशा चुनना और उस पर टिके रहना।",
    },
    "pushya": {
        "en": "Pushya is ruled by Brihaspati, the guru of the gods, and symbolised by a cow's udder or a lotus — images of nourishment. It is counted among the most auspicious nakshatras, and people with the Moon here are often caring, dependable, devoted and generous with their time. They like to support others, keep traditions and build something lasting. Tradition links Pushya with nourishment and wisdom, so teaching, counselling, food, social service, finance and spiritual work suit it well. Its gift is a steady, protective kindness; its lesson is to nourish oneself as faithfully as one nourishes others.",
        "hi": "पुष्य नक्षत्र के देवता देवगुरु बृहस्पति हैं और इसका प्रतीक गाय का थन या कमल है — पोषण के प्रतीक। इसे सबसे शुभ नक्षत्रों में गिना जाता है, और इसमें चंद्रमा वाले लोग प्रायः देखभाल करने वाले, भरोसेमंद, श्रद्धावान और समय देने में उदार होते हैं। उन्हें दूसरों का सहारा बनना, परंपराएँ निभाना और कुछ स्थायी बनाना अच्छा लगता है। परंपरा पुष्य को पोषण और ज्ञान से जोड़ती है, इसलिए शिक्षण, परामर्श, भोजन, समाज-सेवा, वित्त और आध्यात्मिक कार्य इसके अनुकूल हैं। इसका वरदान स्थिर, रक्षा करने वाली करुणा है; इसकी सीख है स्वयं का भी उतना ही ध्यान रखना जितना दूसरों का।",
    },
    "ashlesha": {
        "en": "Ashlesha is ruled by the Nagas, the serpent deities, and symbolised by a coiled serpent — an image of kundalini, hidden energy and deep wisdom. People with the Moon here are often perceptive, intelligent and good at understanding what others leave unsaid. They can be persuasive and strategic, with a strong instinct for self-protection. Tradition links Ashlesha with insight and with the healing knowledge of herbs, so psychology, research, medicine, writing and negotiation suit it well. Its gift is penetrating understanding; its lesson is to use that insight to embrace and heal, the way the serpent's coil protects.",
        "hi": "आश्लेषा नक्षत्र के देवता नाग देवता हैं और इसका प्रतीक कुंडली मारे सर्प है — कुंडलिनी, छिपी ऊर्जा और गहरे ज्ञान का प्रतीक। इस नक्षत्र में चंद्रमा वाले लोग प्रायः पारखी, बुद्धिमान और अनकही बातों को समझने में कुशल होते हैं। वे प्रभावशाली और रणनीतिक हो सकते हैं, और अपनी रक्षा की उनमें स्वाभाविक समझ होती है। परंपरा आश्लेषा को अंतर्दृष्टि और औषधियों के ज्ञान से जोड़ती है, इसलिए मनोविज्ञान, शोध, चिकित्सा, लेखन और वार्ता इसके अनुकूल हैं। इसका वरदान गहरी समझ है; इसकी सीख है उस समझ से दूसरों को अपनाना और सँवारना, जैसे सर्प की कुंडली रक्षा करती है।",
    },
    "magha": {
        "en": "Magha is ruled by the Pitris, the ancestors, and symbolised by a royal throne. People with the Moon here often carry a natural dignity, a respect for family and tradition, and a wish to live up to the name they were given. They can be generous leaders who take responsibility for their people. Tradition links Magha with lineage, honour and authority, so leadership, administration, history, law and work that preserves heritage suit it well. Its gift is nobility of heart; its lesson is to wear the crown lightly — to lead through service and to honour the ancestors through good deeds.",
        "hi": "मघा नक्षत्र के देवता पितृ (पूर्वज) हैं और इसका प्रतीक राजसिंहासन है। इस नक्षत्र में चंद्रमा वाले लोगों में प्रायः स्वाभाविक गरिमा, परिवार और परंपरा के प्रति सम्मान, और अपने कुल का नाम ऊँचा रखने की इच्छा होती है। वे उदार नेता हो सकते हैं जो अपने लोगों की ज़िम्मेदारी लेते हैं। परंपरा मघा को वंश, सम्मान और अधिकार से जोड़ती है, इसलिए नेतृत्व, प्रशासन, इतिहास, क़ानून और विरासत सँभालने वाले काम इसके अनुकूल हैं। इसका वरदान हृदय की उदारता है; इसकी सीख है मुकुट को हल्के से धारण करना — सेवा से नेतृत्व करना और अच्छे कर्मों से पूर्वजों का सम्मान करना।",
    },
    "purva-phalguni": {
        "en": "Purva Phalguni is ruled by Bhaga, the god of fortune and marital happiness, and symbolised by the front legs of a bed — an image of rest and enjoyment. People with the Moon here are often warm, charming, creative and fond of celebration, music and good company. They bring people together and know how to relax and enjoy what they have earned. Tradition links Purva Phalguni with love, the arts and leisure, so entertainment, design, hospitality and relationship-centred work suit it well. Its gift is joy that is easily shared; its lesson is balance between pleasure and duty.",
        "hi": "पूर्वा फाल्गुनी नक्षत्र के देवता सौभाग्य और दांपत्य सुख के देव भग हैं और इसका प्रतीक पलंग के अगले पाये हैं — विश्राम और आनंद का प्रतीक। इस नक्षत्र में चंद्रमा वाले लोग प्रायः स्नेही, आकर्षक, रचनात्मक और उत्सव, संगीत व अच्छी संगति के प्रेमी होते हैं। वे लोगों को जोड़ते हैं और अपनी मेहनत की कमाई का आनंद लेना जानते हैं। परंपरा पूर्वा फाल्गुनी को प्रेम, कला और विश्राम से जोड़ती है, इसलिए मनोरंजन, डिज़ाइन, आतिथ्य और संबंधों पर आधारित काम इसके अनुकूल हैं। इसका वरदान बाँटा जाने वाला आनंद है; इसकी सीख है सुख और कर्तव्य में संतुलन।",
    },
    "uttara-phalguni": {
        "en": "Uttara Phalguni is ruled by Aryaman, the god of friendship, contracts and marriage vows, and symbolised by the back legs of a bed. Where its twin Purva Phalguni enjoys, Uttara Phalguni commits. People with the Moon here are often reliable, helpful, fair-minded and loyal to friends and partners. They keep their word and like to be of real use to others. Tradition links this nakshatra with patronage and lasting partnerships, so management, public service, counselling, law and charitable work suit it well. Its gift is dependable kindness; its lesson is to accept help as gracefully as it is given.",
        "hi": "उत्तरा फाल्गुनी नक्षत्र के देवता मित्रता, अनुबंध और विवाह-वचन के देव अर्यमा हैं और इसका प्रतीक पलंग के पिछले पाये हैं। जहाँ इसकी जुड़वाँ पूर्वा फाल्गुनी आनंद लेती है, वहीं उत्तरा फाल्गुनी वचन निभाती है। इस नक्षत्र में चंद्रमा वाले लोग प्रायः भरोसेमंद, मददगार, न्यायप्रिय और मित्रों व जीवनसाथी के प्रति निष्ठावान होते हैं। वे अपनी बात पर टिकते हैं और दूसरों के सच्चे काम आना चाहते हैं। परंपरा इस नक्षत्र को संरक्षण और स्थायी साझेदारी से जोड़ती है, इसलिए प्रबंधन, लोक-सेवा, परामर्श, क़ानून और परोपकार के काम इसके अनुकूल हैं। इसका वरदान भरोसेमंद दयालुता है; इसकी सीख है मदद लेना भी उतनी ही सहजता से जितनी सहजता से दी जाती है।",
    },
    "hasta": {
        "en": "Hasta is ruled by Savitr, the radiant Sun, and symbolised by a hand. People with the Moon here are often skilful, practical, witty and clever with their hands as well as their minds. They like to get things done and can turn an idea into something real. Tradition links Hasta with craftsmanship, healing touch and resourcefulness, so crafts, the arts, surgery, massage, writing, trade and any skilled trade suit it well. Its gift is the ability to make and to mend; its lesson is to hold things with an open hand, trusting that effort brings its own rewards.",
        "hi": "हस्त नक्षत्र के देवता तेजस्वी सविता (सूर्य) हैं और इसका प्रतीक हाथ है। इस नक्षत्र में चंद्रमा वाले लोग प्रायः कुशल, व्यावहारिक, हाज़िरजवाब और हाथ व दिमाग़ दोनों से चतुर होते हैं। उन्हें काम पूरा करना अच्छा लगता है और वे विचार को साकार कर सकते हैं। परंपरा हस्त को कारीगरी, उपचार के स्पर्श और साधन-संपन्नता से जोड़ती है, इसलिए शिल्प, कला, शल्य-चिकित्सा, मालिश, लेखन, व्यापार और कोई भी कौशल वाला काम इसके अनुकूल है। इसका वरदान बनाने और सँवारने की क्षमता है; इसकी सीख है चीज़ों को खुले हाथ से थामना, यह भरोसा रखते हुए कि मेहनत अपना फल स्वयं लाती है।",
    },
    "chitra": {
        "en": "Chitra is ruled by Tvashtr, also known as Vishwakarma, the divine architect, and symbolised by a bright jewel. Its name means \"brilliant\" or \"picture\", and people with the Moon here often have a strong sense of beauty, design and form. They enjoy creating things that are both useful and attractive, and they notice detail. Tradition links Chitra with architecture, the arts and craftsmanship, so design, engineering, fashion, jewellery, photography and planning suit it well. Its gift is the eye of an artist and the hand of a builder; its lesson is to value inner beauty as much as outer polish.",
        "hi": "चित्रा नक्षत्र के देवता दिव्य शिल्पी त्वष्टा (विश्वकर्मा) हैं और इसका प्रतीक चमकता रत्न है। इसके नाम का अर्थ है \"उज्ज्वल\" या \"चित्र\", और इसमें चंद्रमा वाले लोगों में प्रायः सौंदर्य, बनावट और रूप की गहरी समझ होती है। उन्हें ऐसी चीज़ें बनाना अच्छा लगता है जो उपयोगी भी हों और सुंदर भी, और वे बारीकियों पर ध्यान देते हैं। परंपरा चित्रा को वास्तुकला, कला और कारीगरी से जोड़ती है, इसलिए डिज़ाइन, इंजीनियरिंग, फ़ैशन, आभूषण, फ़ोटोग्राफ़ी और योजना के काम इसके अनुकूल हैं। इसका वरदान कलाकार की आँख और निर्माता का हाथ है; इसकी सीख है भीतर की सुंदरता को भी उतना ही महत्व देना जितना बाहरी चमक को।",
    },
    "swati": {
        "en": "Swati is ruled by Vayu, the wind, and symbolised by a young shoot swaying in the breeze — flexible, independent and able to bend without breaking. People with the Moon here often value freedom, fairness and their own way of doing things. They are usually diplomatic, courteous and good at business and negotiation. Tradition links Swati with trade, travel and self-reliance, so commerce, law, diplomacy, communication and independent work suit it well. Its gift is adaptability and a gentle, balanced manner; its lesson is to put down roots, so that the young shoot can grow into a strong tree.",
        "hi": "स्वाति नक्षत्र के देवता वायु देव हैं और इसका प्रतीक हवा में लहराता अंकुर है — लचीला, स्वतंत्र और टूटे बिना झुकने वाला। इस नक्षत्र में चंद्रमा वाले लोग प्रायः स्वतंत्रता, न्याय और अपने ढंग से काम करने को महत्व देते हैं। वे सामान्यतः कूटनीतिक, शिष्ट और व्यापार व बातचीत में कुशल होते हैं। परंपरा स्वाति को व्यापार, यात्रा और आत्मनिर्भरता से जोड़ती है, इसलिए वाणिज्य, क़ानून, कूटनीति, संचार और स्वतंत्र काम इसके अनुकूल हैं। इसका वरदान अनुकूलन क्षमता और कोमल, संतुलित व्यवहार है; इसकी सीख है जड़ें जमाना, ताकि नन्हा अंकुर मज़बूत वृक्ष बन सके।",
    },
    "vishakha": {
        "en": "Vishakha is ruled by Indra and Agni together, and symbolised by a triumphal arch decorated with leaves. People with the Moon here are often purposeful, ambitious and determined to reach the goal they have set. They have energy, conviction and the patience to keep going over a long road. Tradition calls Vishakha the nakshatra of purpose, so leadership, research, politics, sales, teaching and any long-term mission suit it well. Its gift is focus and the ability to inspire others towards a shared aim; its lesson is to enjoy the journey, not only the arch at its end.",
        "hi": "विशाखा नक्षत्र के देवता इन्द्र और अग्नि (इन्द्राग्नि) हैं और इसका प्रतीक पत्तों से सजा तोरण द्वार है। इस नक्षत्र में चंद्रमा वाले लोग प्रायः उद्देश्यपूर्ण, महत्वाकांक्षी और अपने तय किए लक्ष्य तक पहुँचने के लिए दृढ़ होते हैं। उनमें ऊर्जा, विश्वास और लंबी राह पर चलते रहने का धैर्य होता है। परंपरा विशाखा को उद्देश्य का नक्षत्र कहती है, इसलिए नेतृत्व, शोध, राजनीति, बिक्री, शिक्षण और कोई भी दीर्घकालीन लक्ष्य इसके अनुकूल है। इसका वरदान एकाग्रता और दूसरों को साझा लक्ष्य की ओर प्रेरित करने की क्षमता है; इसकी सीख है केवल अंत के तोरण का नहीं, पूरी यात्रा का आनंद लेना।",
    },
    "anuradha": {
        "en": "Anuradha is ruled by Mitra, the god of friendship and cooperation, and symbolised by a lotus that blooms out of muddy water. People with the Moon here are often loyal friends, devoted to their ideals and able to keep going with quiet faith in difficult places. They are good at bringing people together in groups and organisations. Tradition links Anuradha with friendship, devotion and success away from home, so teamwork, organisation, counselling, travel and spiritual practice suit it well. Its gift is the ability to blossom anywhere; its lesson is to be as gentle with oneself as with friends.",
        "hi": "अनुराधा नक्षत्र के देवता मित्रता और सहयोग के देव मित्र हैं और इसका प्रतीक कीचड़ में खिलने वाला कमल है। इस नक्षत्र में चंद्रमा वाले लोग प्रायः निष्ठावान मित्र, अपने आदर्शों के प्रति समर्पित और कठिन जगहों पर भी शांत श्रद्धा से आगे बढ़ने वाले होते हैं। वे लोगों को समूहों और संस्थाओं में जोड़ने में कुशल होते हैं। परंपरा अनुराधा को मित्रता, भक्ति और घर से दूर सफलता से जोड़ती है, इसलिए टीम-कार्य, संगठन, परामर्श, यात्रा और आध्यात्मिक साधना इसके अनुकूल हैं। इसका वरदान कहीं भी खिल उठने की क्षमता है; इसकी सीख है स्वयं के प्रति भी उतना ही कोमल रहना जितना मित्रों के प्रति।",
    },
    "jyeshtha": {
        "en": "Jyeshtha is ruled by Indra, king of the gods, and symbolised by a circular amulet or earring. Its name means \"the eldest\", and people with the Moon here often take on responsibility early, protect those around them and carry a quiet authority. They are resourceful, perceptive and capable under pressure. Tradition links Jyeshtha with seniority and protection, so leadership, management, administration, security and any role that looks after others suit it well. Its gift is courage and capability; its lesson is to lead with humility and to let others share the load rather than carrying everything alone.",
        "hi": "ज्येष्ठा नक्षत्र के देवता देवराज इन्द्र हैं और इसका प्रतीक गोल कुंडल या ताबीज़ है। इसके नाम का अर्थ है \"सबसे बड़ा\", और इसमें चंद्रमा वाले लोग प्रायः जल्दी ज़िम्मेदारी उठाते हैं, आसपास के लोगों की रक्षा करते हैं और उनमें शांत अधिकार-भाव होता है। वे साधन-संपन्न, पारखी और दबाव में भी सक्षम होते हैं। परंपरा ज्येष्ठा को वरिष्ठता और संरक्षण से जोड़ती है, इसलिए नेतृत्व, प्रबंधन, प्रशासन, सुरक्षा और दूसरों की देखभाल वाली भूमिकाएँ इसके अनुकूल हैं। इसका वरदान साहस और योग्यता है; इसकी सीख है विनम्रता से नेतृत्व करना और सारा भार अकेले उठाने के बजाय दूसरों को भी साथ लेना।",
    },
    "mula": {
        "en": "Mula is ruled by Nirriti and symbolised by a bunch of roots. Its name means \"the root\", and people with the Moon here are often drawn to get to the bottom of things — to find the origin of a question, an idea or a tradition. They can be independent, philosophical and unafraid to start again from first principles. Tradition links Mula with investigation and with letting go of what is no longer needed, so research, medicine, philosophy, botany and spiritual inquiry suit it well. Its gift is depth; its lesson is that clearing old ground makes room for new growth.",
        "hi": "मूल नक्षत्र की देवी निऋति हैं और इसका प्रतीक जड़ों का गुच्छा है। इसके नाम का अर्थ है \"जड़\", और इसमें चंद्रमा वाले लोग प्रायः चीज़ों की तह तक जाना चाहते हैं — किसी प्रश्न, विचार या परंपरा का मूल खोजना। वे स्वतंत्र, दार्शनिक और मूल सिद्धांतों से फिर शुरू करने में निडर हो सकते हैं। परंपरा मूल को खोज और अनावश्यक को छोड़ने से जोड़ती है, इसलिए शोध, चिकित्सा, दर्शन, वनस्पति-विज्ञान और आध्यात्मिक जिज्ञासा इसके अनुकूल हैं। इसका वरदान गहराई है; इसकी सीख है कि पुरानी ज़मीन साफ़ करने से नए अंकुर के लिए जगह बनती है।",
    },
    "purva-ashadha": {
        "en": "Purva Ashadha is ruled by Apas, the cosmic waters, and symbolised by a winnowing fan or an elephant tusk. Its name means \"the early invincible\", and people with the Moon here are often confident, persuasive and full of conviction. Like water, they can be gentle and yet wear down any obstacle in time. Tradition links Purva Ashadha with purification and with victory won through persistence, so teaching, law, debate, the arts, shipping and anything to do with water suit it well. Its gift is optimism and inner strength; its lesson is to stay open to other views while holding firm to its own.",
        "hi": "पूर्वाषाढ़ा नक्षत्र के देवता आपः (जल देवता) हैं और इसका प्रतीक सूप (पंखा) या हाथी दाँत है। इसके नाम का अर्थ है \"पहला अजेय\", और इसमें चंद्रमा वाले लोग प्रायः आत्मविश्वासी, प्रभावशाली और दृढ़ विश्वास वाले होते हैं। जल की तरह वे कोमल होकर भी समय के साथ हर बाधा को घिस देते हैं। परंपरा पूर्वाषाढ़ा को शुद्धि और लगन से मिली विजय से जोड़ती है, इसलिए शिक्षण, क़ानून, वाद-विवाद, कला, जहाज़रानी और जल से जुड़े काम इसके अनुकूल हैं। इसका वरदान आशावाद और भीतरी शक्ति है; इसकी सीख है अपनी बात पर दृढ़ रहते हुए दूसरों के विचारों के लिए भी खुले रहना।",
    },
    "uttara-ashadha": {
        "en": "Uttara Ashadha is ruled by the Vishvedevas, the universal gods, and symbolised by an elephant tusk. Its name means \"the later invincible\" — the victory that lasts because it was earned honestly. People with the Moon here are often principled, patient, responsible and respected for their integrity. They take the long view and finish what they commit to. Tradition links Uttara Ashadha with righteous leadership, so government, management, law, teaching and social causes suit it well. Its gift is steady, ethical strength; its lesson is to keep a little lightness and warmth alongside the seriousness of duty.",
        "hi": "उत्तराषाढ़ा नक्षत्र के देवता विश्वेदेव हैं और इसका प्रतीक हाथी दाँत है। इसके नाम का अर्थ है \"बाद का अजेय\" — वह विजय जो टिकती है क्योंकि ईमानदारी से अर्जित की गई। इस नक्षत्र में चंद्रमा वाले लोग प्रायः सिद्धांतवादी, धैर्यवान, ज़िम्मेदार और अपनी ईमानदारी के लिए सम्मानित होते हैं। वे दूर की सोचते हैं और जो वचन देते हैं उसे पूरा करते हैं। परंपरा उत्तराषाढ़ा को धर्मपूर्ण नेतृत्व से जोड़ती है, इसलिए शासन, प्रबंधन, क़ानून, शिक्षण और सामाजिक कार्य इसके अनुकूल हैं। इसका वरदान स्थिर, नैतिक शक्ति है; इसकी सीख है कर्तव्य की गंभीरता के साथ थोड़ा हल्कापन और स्नेह भी बनाए रखना।",
    },
    "shravana": {
        "en": "Shravana is ruled by Vishnu, the preserver, and symbolised by an ear or three footprints. Its name means \"hearing\", and people with the Moon here are often good listeners, eager learners and keepers of knowledge and tradition. They learn by listening and pass on what they have learned. Tradition links Shravana with wisdom gained through study and with connecting people, so teaching, counselling, media, languages, music and travel suit it well. Its gift is attentive understanding and a wish to be useful; its lesson is to listen to one's own inner voice as carefully as to others.",
        "hi": "श्रवण नक्षत्र के देवता पालनकर्ता भगवान विष्णु हैं और इसका प्रतीक कान या तीन पदचिह्न है। इसके नाम का अर्थ है \"सुनना\", और इसमें चंद्रमा वाले लोग प्रायः अच्छे श्रोता, सीखने के उत्सुक और ज्ञान व परंपरा के संरक्षक होते हैं। वे सुनकर सीखते हैं और सीखा हुआ आगे बाँटते हैं। परंपरा श्रवण को अध्ययन से मिले ज्ञान और लोगों को जोड़ने से जोड़ती है, इसलिए शिक्षण, परामर्श, मीडिया, भाषाएँ, संगीत और यात्रा इसके अनुकूल हैं। इसका वरदान ध्यान से समझना और उपयोगी बनने की इच्छा है; इसकी सीख है अपनी भीतरी आवाज़ को भी उतने ही ध्यान से सुनना जितना दूसरों को।",
    },
    "dhanishta": {
        "en": "Dhanishta is ruled by the eight Vasus, gods of abundance, and symbolised by a drum. Its name means \"the wealthiest\", and people with the Moon here often have rhythm, energy and a talent for music, dance or teamwork. They are generous, sociable and able to keep a group moving together. Tradition links Dhanishta with prosperity and with sound, so music, performance, sport, property, finance and community work suit it well. Its gift is the ability to set the beat that others follow; its lesson is to listen as well as play, leaving space for others' rhythms.",
        "hi": "धनिष्ठा नक्षत्र के देवता समृद्धि के देव अष्ट वसु हैं और इसका प्रतीक मृदंग (ढोल) है। इसके नाम का अर्थ है \"सबसे धनवान\", और इसमें चंद्रमा वाले लोगों में प्रायः लय, ऊर्जा और संगीत, नृत्य या टीम-कार्य की प्रतिभा होती है। वे उदार, मिलनसार और समूह को साथ लेकर चलने वाले होते हैं। परंपरा धनिष्ठा को समृद्धि और ध्वनि से जोड़ती है, इसलिए संगीत, प्रदर्शन-कला, खेल, संपत्ति, वित्त और सामुदायिक कार्य इसके अनुकूल हैं। इसका वरदान वह ताल देना है जिस पर दूसरे चलें; इसकी सीख है बजाने के साथ सुनना भी, ताकि दूसरों की लय के लिए भी जगह रहे।",
    },
    "shatabhisha": {
        "en": "Shatabhisha is ruled by Varuna, lord of the cosmic waters and of truth, and symbolised by an empty circle. Its name means \"a hundred healers\", and people with the Moon here are often independent thinkers, private, truthful and drawn to understanding how things really work. They can see patterns others miss. Tradition links Shatabhisha with healing and with the search for hidden truth, so medicine, research, science, technology, astronomy and alternative healing suit it well. Its gift is clear, original insight; its lesson is to let others into the circle, sharing what is understood with warmth.",
        "hi": "शतभिषा नक्षत्र के देवता जल और सत्य के स्वामी वरुण देव हैं और इसका प्रतीक रिक्त वृत्त है। इसके नाम का अर्थ है \"सौ वैद्य\", और इसमें चंद्रमा वाले लोग प्रायः स्वतंत्र विचारक, एकांतप्रिय, सत्यवादी और चीज़ों के वास्तविक रहस्य को समझने के इच्छुक होते हैं। वे ऐसे पैटर्न देख लेते हैं जो दूसरों से छूट जाते हैं। परंपरा शतभिषा को उपचार और छिपे सत्य की खोज से जोड़ती है, इसलिए चिकित्सा, शोध, विज्ञान, तकनीक, खगोल और वैकल्पिक उपचार इसके अनुकूल हैं। इसका वरदान स्पष्ट, मौलिक अंतर्दृष्टि है; इसकी सीख है दूसरों को भी उस वृत्त में आने देना और अपनी समझ स्नेह से बाँटना।",
    },
    "purva-bhadrapada": {
        "en": "Purva Bhadrapada is ruled by Aja Ekapada, the one-footed form of Shiva, and symbolised by swords or the front legs of a cot. People with the Moon here are often idealistic, intense and willing to give themselves fully to a cause they believe in. They can be eloquent, generous and deeply spiritual. Tradition links Purva Bhadrapada with transformation and with the fire of tapas — sincere effort for a higher aim — so social reform, philosophy, writing, research and spiritual life suit it well. Its gift is passionate commitment; its lesson is to temper intensity with patience and calm.",
        "hi": "पूर्व भाद्रपद नक्षत्र के देवता अज एकपाद (शिव का एकपाद रूप) हैं और इसका प्रतीक तलवार या खाट के अगले पाये हैं। इस नक्षत्र में चंद्रमा वाले लोग प्रायः आदर्शवादी, तीव्र और जिस उद्देश्य में विश्वास करते हैं उसके लिए पूरी तरह समर्पित होने वाले होते हैं। वे वाक्पटु, उदार और गहरे आध्यात्मिक हो सकते हैं। परंपरा पूर्व भाद्रपद को परिवर्तन और तप की अग्नि — ऊँचे लक्ष्य के लिए सच्चे प्रयास — से जोड़ती है, इसलिए समाज-सुधार, दर्शन, लेखन, शोध और आध्यात्मिक जीवन इसके अनुकूल हैं। इसका वरदान उत्कट समर्पण है; इसकी सीख है तीव्रता को धैर्य और शांति से संतुलित करना।",
    },
    "uttara-bhadrapada": {
        "en": "Uttara Bhadrapada is ruled by Ahir Budhnya, the serpent of the deep waters, and symbolised by the back legs of a cot or twins. Where Purva Bhadrapada burns, Uttara Bhadrapada settles into calm depth. People with the Moon here are often wise, patient, composed and compassionate, with self-control and a gift for counsel. They tend to think before they speak and are steady in difficult times. Tradition links this nakshatra with depth, renunciation and kindness, so counselling, charity, teaching, research and spiritual practice suit it well. Its gift is serene wisdom; its lesson is to share it actively, not only privately.",
        "hi": "उत्तर भाद्रपद नक्षत्र के देवता अहिर्बुध्न्य (गहरे जल के नाग) हैं और इसका प्रतीक खाट के पिछले पाये या जुड़वाँ हैं। जहाँ पूर्व भाद्रपद में अग्नि है, वहीं उत्तर भाद्रपद शांत गहराई में स्थिर होता है। इस नक्षत्र में चंद्रमा वाले लोग प्रायः ज्ञानी, धैर्यवान, संयमी और करुणामय होते हैं, और उनमें आत्म-नियंत्रण व अच्छी सलाह देने का गुण होता है। वे बोलने से पहले सोचते हैं और कठिन समय में स्थिर रहते हैं। परंपरा इस नक्षत्र को गहराई, त्याग और दयालुता से जोड़ती है, इसलिए परामर्श, दान, शिक्षण, शोध और आध्यात्मिक साधना इसके अनुकूल हैं। इसका वरदान शांत ज्ञान है; इसकी सीख है उसे केवल मन में न रखकर सक्रियता से बाँटना।",
    },
    "revati": {
        "en": "Revati, the last nakshatra, is ruled by Pushan, the nourisher who guides travellers and protects herds on their way, and symbolised by a fish. People with the Moon here are often gentle, kind, imaginative and protective of the weak, with a love of animals, art and music. They make good companions on any journey and help others reach their destination safely. Tradition links Revati with safe journeys, prosperity and completion, so caring work, the arts, travel, hospitality and spiritual life suit it well. Its gift is compassion and faith; its lesson is to care for oneself while caring for everyone else.",
        "hi": "रेवती अंतिम नक्षत्र है, जिसके देवता पूषा हैं — पोषण करने वाले, यात्रियों के मार्गदर्शक और राह में पशुओं के रक्षक — और इसका प्रतीक मछली है। इस नक्षत्र में चंद्रमा वाले लोग प्रायः कोमल, दयालु, कल्पनाशील और निर्बलों के रक्षक होते हैं, जिन्हें पशु, कला और संगीत प्रिय होते हैं। वे किसी भी यात्रा के अच्छे साथी होते हैं और दूसरों को सुरक्षित मंज़िल तक पहुँचने में मदद करते हैं। परंपरा रेवती को सुरक्षित यात्रा, समृद्धि और पूर्णता से जोड़ती है, इसलिए सेवा, कला, यात्रा, आतिथ्य और आध्यात्मिक जीवन इसके अनुकूल हैं। इसका वरदान करुणा और श्रद्धा है; इसकी सीख है सबका ध्यान रखते हुए स्वयं का भी ध्यान रखना।",
    },
}

# Kannada
for _k, _v in {
    "ashwini": "ಅಶ್ವಿನಿ ಮೊದಲ ನಕ್ಷತ್ರ. ಇದರ ಅಧಿದೇವತೆಗಳು ದೇವತೆಗಳ ಅವಳಿ ವೈದ್ಯರಾದ ಅಶ್ವಿನಿ ಕುಮಾರರು, ಮತ್ತು ಇದರ ಸಂಕೇತ ಕುದುರೆಯ ಮುಖ. ಈ ನಕ್ಷತ್ರದಲ್ಲಿ ಚಂದ್ರನಿರುವವರು ಸಾಮಾನ್ಯವಾಗಿ ಚುರುಕು, ಉತ್ಸಾಹಿಗಳು ಮತ್ತು ಹೊಸ ಕೆಲಸಗಳನ್ನು ಆರಂಭಿಸಲು ಸದಾ ಸಿದ್ಧರು — ಸಹಾಯಕ್ಕೆ ಮೊದಲು ಮುಂದೆ ಬರುವವರು, ಹೊಸದನ್ನು ಮೊದಲು ಪ್ರಯತ್ನಿಸುವವರು. ಸಂಪ್ರದಾಯವು ಅಶ್ವಿನಿಯನ್ನು ಚಿಕಿತ್ಸೆ, ವೇಗ ಮತ್ತು ಹೊಸ ಆರಂಭಗಳೊಂದಿಗೆ ಜೋಡಿಸುತ್ತದೆ; ಆದ್ದರಿಂದ ಅನೇಕರು ವೈದ್ಯಕೀಯ, ಕ್ರೀಡೆ, ಪ್ರಯಾಣ ಅಥವಾ ಶೀಘ್ರ ಮತ್ತು ಪ್ರಾಯೋಗಿಕ ಕ್ರಮ ಬೇಕಾಗುವ ಯಾವುದೇ ಕೆಲಸದತ್ತ ಆಕರ್ಷಿತರಾಗುತ್ತಾರೆ. ಈ ನಕ್ಷತ್ರದ ವರ ಉಪಕ್ರಮಶೀಲತೆ ಮತ್ತು ಯೌವನದ ಆಶಾವಾದ; ಇದರ ಪಾಠ ತಾಳ್ಮೆ — ಆರಂಭಿಸಿದ ಕೆಲಸವನ್ನು ಆರಂಭದ ಅದೇ ಉತ್ಸಾಹದಿಂದ ಪೂರ್ಣಗೊಳಿಸುವುದು.",
    "bharani": "ಭರಣಿ ನಕ್ಷತ್ರದ ಅಧಿದೇವತೆ ಧರ್ಮದ ಅಧಿಪತಿಯಾದ ಯಮ; ಇದರ ಸಂಕೇತ ಯೋನಿ — ಹೊಸ ಜೀವವನ್ನು ಹೊತ್ತು ಕಾಪಾಡುವ ಗರ್ಭ. ಈ ನಕ್ಷತ್ರದಲ್ಲಿ ಚಂದ್ರನಿರುವವರು ಸಾಮಾನ್ಯವಾಗಿ ದೃಢ ಸಂಕಲ್ಪ, ಆಳವಾದ ಭಾವನೆಗಳು ಮತ್ತು ಗಂಭೀರವಾದ ಜವಾಬ್ದಾರಿಯ ಪ್ರಜ್ಞೆ ಹೊಂದಿರುತ್ತಾರೆ. ಕೈಗೊಂಡ ಹೊಣೆಗಳನ್ನು ಕೊನೆಯವರೆಗೂ ನಿಭಾಯಿಸುತ್ತಾರೆ ಮತ್ತು ಸುಲಭವಾಗಿ ವಿಚಲಿತರಾಗುವುದಿಲ್ಲ. ಸಂಪ್ರದಾಯವು ಭರಣಿಯನ್ನು ಹೊರುವ ಮತ್ತು ಪೋಷಿಸುವ ನಕ್ಷತ್ರವೆಂದು ಕಾಣುತ್ತದೆ — ಯಾವುದನ್ನಾದರೂ ಜನ್ಮಕ್ಕೆ ಸಿದ್ಧವಾಗುವವರೆಗೆ ಕಾಪಾಡುವುದು; ಆದ್ದರಿಂದ ಸೃಜನಶೀಲತೆ, ಕುಟುಂಬ, ಕಲೆ ಮತ್ತು ಸಹನಶಕ್ತಿ ಬೇಡುವ ಕೆಲಸಗಳು ಇದಕ್ಕೆ ಚೆನ್ನಾಗಿ ಹೊಂದುತ್ತವೆ. ಇದರ ಶಕ್ತಿ ಸ್ಥಿರತೆ; ಇದರ ಪಾಠ ಆಸೆಯನ್ನು ಸಂಯಮ ಮತ್ತು ದಯೆಯೊಂದಿಗೆ ಸಮತೋಲನಗೊಳಿಸುವುದು.",
    "krittika": "ಕೃತ್ತಿಕಾ ನಕ್ಷತ್ರದ ಅಧಿದೇವತೆ ಪವಿತ್ರ ಅಗ್ನಿ; ಇದರ ಸಂಕೇತ ಕ್ಷೌರದ ಕತ್ತಿ ಅಥವಾ ಜ್ವಾಲೆ. ಬೆಂಕಿ ಶುದ್ಧೀಕರಿಸುತ್ತದೆ ಮತ್ತು ಗೊಂದಲವನ್ನು ಕತ್ತರಿಸಿ ಹಾಕುತ್ತದೆ; ಈ ನಕ್ಷತ್ರದಲ್ಲಿ ಚಂದ್ರನಿರುವವರು ಸಾಮಾನ್ಯವಾಗಿ ನೇರ ನುಡಿಯವರು, ತತ್ತ್ವನಿಷ್ಠರು ಮತ್ತು ತೀಕ್ಷ್ಣ ವಿವೇಚನೆಯುಳ್ಳವರು. ತಾವು ಪ್ರೀತಿಸುವವರನ್ನು ಕಾಪಾಡುತ್ತಾರೆ ಮತ್ತು ಹೇಳಬೇಕಾದುದನ್ನು ಹೇಳಲು ಹಿಂಜರಿಯುವುದಿಲ್ಲ. ಕಾರ್ತಿಕೇಯನನ್ನು ಪೋಷಿಸಿದ ಆರು ತಾಯಂದಿರ ನಕ್ಷತ್ರವೂ ಕೃತ್ತಿಕಾ; ಆದ್ದರಿಂದ ಆ ತೀಕ್ಷ್ಣತೆಯ ಒಳಗೆ ನಿಜವಾದ ಮಮತೆ ಮತ್ತು ಕಾಳಜಿ ಇರುತ್ತದೆ. ಬೋಧನೆ, ಅಡುಗೆ, ನಾಯಕತ್ವ ಮತ್ತು ಸ್ಪಷ್ಟತೆ ಬೇಕಾಗುವ ಯಾವುದೇ ಕೆಲಸ ಇದಕ್ಕೆ ಹೊಂದುತ್ತದೆ. ಇದರ ಪಾಠ — ಬೆಂಕಿ ಸುಡುವುದಕ್ಕಿಂತ ಬೆಚ್ಚಗಿಡಲಿ, ದಾರಿ ತೋರಲಿ.",
    "rohini": "ರೋಹಿಣಿ ನಕ್ಷತ್ರದ ಅಧಿದೇವತೆ ಸೃಷ್ಟಿಕರ್ತನಾದ ಬ್ರಹ್ಮ; ಇದರ ಸಂಕೇತ ರಥ ಅಥವಾ ಎತ್ತಿನ ಗಾಡಿ. ಇದು ಚಂದ್ರನ ಅತ್ಯಂತ ಪ್ರಿಯ ನಕ್ಷತ್ರ ಎನ್ನಲಾಗುತ್ತದೆ; ಈ ನಕ್ಷತ್ರದಲ್ಲಿ ಚಂದ್ರನಿರುವವರು ಸಾಮಾನ್ಯವಾಗಿ ಆತ್ಮೀಯರು, ಆಕರ್ಷಕರು, ಕಲಾಭಿರುಚಿಯುಳ್ಳವರು ಮತ್ತು ಸುಖ-ಸೌಂದರ್ಯಗಳನ್ನು ಇಷ್ಟಪಡುವವರು. ತೋಟ, ಮನೆ, ವ್ಯಾಪಾರ, ಸಂಬಂಧ — ಯಾವುದನ್ನೇ ಆಗಲಿ ಬೆಳೆಸುವ ಕೌಶಲ ಅವರಲ್ಲಿರುತ್ತದೆ. ಸಂಪ್ರದಾಯವು ರೋಹಿಣಿಯನ್ನು ಫಲವತ್ತತೆ, ಸಮೃದ್ಧಿ ಮತ್ತು ಸ್ಥಿರ ಪ್ರಗತಿಯೊಂದಿಗೆ ಜೋಡಿಸುತ್ತದೆ; ಆದ್ದರಿಂದ ಕೃಷಿ, ಕಲೆಗಳು, ವಿನ್ಯಾಸ, ಆಹಾರ ಮತ್ತು ಆತಿಥ್ಯ ಇದಕ್ಕೆ ಚೆನ್ನಾಗಿ ಹೊಂದುತ್ತವೆ. ಇದರ ಸ್ವಭಾವ ಸೌಮ್ಯ ಮತ್ತು ನೆಲೆನಿಂತದ್ದು; ಇದರ ಪಾಠ ಸುಂದರವಾದುದನ್ನು ಅತಿಯಾಗಿ ಹಿಡಿದಿಟ್ಟುಕೊಳ್ಳದೆ ಆನಂದಿಸುವುದು.",
    "mrigashira": "ಮೃಗಶಿರ ನಕ್ಷತ್ರದ ಅಧಿದೇವತೆ ಸೋಮ, ಅಂದರೆ ಚಂದ್ರ; ಇದರ ಸಂಕೇತ ಜಿಂಕೆಯ ತಲೆ — ಸದಾ ಎಚ್ಚರ, ಕುತೂಹಲ ಮತ್ತು ಹುಡುಕಾಟದಲ್ಲಿರುವ ಜಿಂಕೆ. ಈ ನಕ್ಷತ್ರದಲ್ಲಿ ಚಂದ್ರನಿರುವವರು ಸಾಮಾನ್ಯವಾಗಿ ಸೌಮ್ಯರು, ಜಿಜ್ಞಾಸುಗಳು ಮತ್ತು ಕಲಿಕೆ, ಪ್ರಯಾಣ, ಮಾತುಕತೆಗಳನ್ನು ಇಷ್ಟಪಡುವವರು. ವಿಚಾರಗಳನ್ನೂ ಸ್ಥಳಗಳನ್ನೂ ಅನ್ವೇಷಿಸುವುದರಲ್ಲಿ ಅವರಿಗೆ ಆನಂದ, ಪ್ರಶ್ನೆ ಕೇಳುವುದನ್ನು ಅವರು ಅಪರೂಪವಾಗಿ ನಿಲ್ಲಿಸುತ್ತಾರೆ. ಸಂಪ್ರದಾಯವು ಮೃಗಶಿರವನ್ನು ಅನ್ವೇಷಕನ ನಕ್ಷತ್ರವೆಂದು ಕಾಣುತ್ತದೆ; ಸಂಶೋಧನೆ, ಬರವಣಿಗೆ, ಬೋಧನೆ, ವ್ಯಾಪಾರ ಮತ್ತು ಕುತೂಹಲಕ್ಕೆ ಫಲ ನೀಡುವ ಯಾವುದೇ ಕೆಲಸ ಇದಕ್ಕೆ ಹೊಂದುತ್ತದೆ. ಇದರ ಸೊಗಸು ಹಗುರವಾದ, ಸ್ನೇಹಪರ ಮನಸ್ಸು; ಇದರ ಪಾಠ ಕಂಡುಕೊಂಡದ್ದರಲ್ಲಿ ನೆಲೆಯೂರುವುದು — ಹುಡುಕಾಟ ಚಡಪಡಿಕೆಯಾಗದೆ ಎಲ್ಲಿಗಾದರೂ ತಲುಪಿಸಲಿ.",
    "ardra": "ಆರ್ದ್ರಾ ನಕ್ಷತ್ರದ ಅಧಿದೇವತೆ ಶಿವನ ಬಿರುಗಾಳಿಯ ರೂಪವಾದ ರುದ್ರ; ಇದರ ಸಂಕೇತ ಕಣ್ಣೀರಿನ ಹನಿ ಅಥವಾ ವಜ್ರ. ಬಿರುಗಾಳಿ ಗಾಳಿಯನ್ನು ಶುದ್ಧಗೊಳಿಸಿ ಮಳೆ ತರುವಂತೆ, ಈ ನಕ್ಷತ್ರದಲ್ಲಿ ಚಂದ್ರನಿರುವವರು ಸಾಮಾನ್ಯವಾಗಿ ಬಲವಾದ, ಶೋಧಕ ಬುದ್ಧಿಯನ್ನೂ ವಿಷಯಗಳ ಆಳಕ್ಕೆ ಇಳಿದು ಸತ್ಯವನ್ನು ಕಾಣುವ ಸಾಮರ್ಥ್ಯವನ್ನೂ ಹೊಂದಿರುತ್ತಾರೆ. ಅವರು ಆಳವಾಗಿ ಅನುಭವಿಸುತ್ತಾರೆ ಮತ್ತು ಬದಲಾವಣೆಗೆ ಹೆದರುವುದಿಲ್ಲ. ಸಂಪ್ರದಾಯವು ಆರ್ದ್ರಾವನ್ನು ಕಷ್ಟದ ನಂತರದ ನವೀಕರಣದೊಂದಿಗೆ ಜೋಡಿಸುತ್ತದೆ; ಆದ್ದರಿಂದ ಸಂಶೋಧನೆ, ತಂತ್ರಜ್ಞಾನ, ಬರವಣಿಗೆ, ಆಪ್ತಸಮಾಲೋಚನೆ ಮತ್ತು ಸಮಸ್ಯೆ ಪರಿಹಾರ ಇದಕ್ಕೆ ಚೆನ್ನಾಗಿ ಹೊಂದುತ್ತವೆ. ಇದರ ವರ ಪ್ರಾಮಾಣಿಕತೆ ಮತ್ತು ತೀಕ್ಷ್ಣ ಮನಸ್ಸು; ಇದರ ಪಾಠ ಭಾವನೆಗಳನ್ನು ಮಳೆಯಂತೆ ಹಾದುಹೋಗಲು ಬಿಡುವುದು — ಅವು ನೆಲವನ್ನು ಇನ್ನಷ್ಟು ಹಸಿರಾಗಿಸಿ ಹೋಗಲಿ.",
    "punarvasu": "ಪುನರ್ವಸು ನಕ್ಷತ್ರದ ಅಧಿದೇವತೆ ದೇವತೆಗಳ ಅಪರಿಮಿತ ತಾಯಿಯಾದ ಅದಿತಿ; ಇದರ ಸಂಕೇತ ಬಿಲ್ಲು ಮತ್ತು ಬತ್ತಳಿಕೆ. ಇದರ ಹೆಸರಿನ ಅರ್ಥ \"ಬೆಳಕಿನ ಮರಳುವಿಕೆ\"; ಈ ನಕ್ಷತ್ರದಲ್ಲಿ ಚಂದ್ರನಿರುವವರು ಸಾಮಾನ್ಯವಾಗಿ ಆಶಾವಾದಿಗಳು, ಉದಾರಿಗಳು ಮತ್ತು ಯಾವುದೇ ಹಿನ್ನಡೆಯ ನಂತರ ಮತ್ತೆ ಆರಂಭಿಸಬಲ್ಲವರು. ಸರಳ ವಿಷಯಗಳಲ್ಲಿ ತೃಪ್ತರು, ಹಸನ್ಮುಖಿಗಳು ಮತ್ತು ಕುಟುಂಬ ಹಾಗೂ ಅತಿಥಿಗಳ ಬಗ್ಗೆ ಕಾಳಜಿಯುಳ್ಳವರು. ಸಂಪ್ರದಾಯವು ಪುನರ್ವಸುವನ್ನು ನವೀಕರಣ ಮತ್ತು ಮನೆಗೆ ಮರಳುವಿಕೆಯ ನಕ್ಷತ್ರವೆಂದು ಕಾಣುತ್ತದೆ; ಬೋಧನೆ, ಆಪ್ತಸಮಾಲೋಚನೆ, ಬರವಣಿಗೆ, ಪ್ರಯಾಣ ಮತ್ತು ಆರೈಕೆಯ ಕೆಲಸಗಳು ಇದಕ್ಕೆ ಹೊಂದುತ್ತವೆ. ಇದರ ಆಶೀರ್ವಾದ ಆಶಾಭರಿತ, ಕ್ಷಮಾಶೀಲ ಹೃದಯ; ಇದರ ಪಾಠ ಬಾಣಕ್ಕೆ ಗುರಿ ಇಡುವುದು — ಒಂದು ದಿಕ್ಕನ್ನು ಆರಿಸಿ ಅದರಲ್ಲೇ ಮುಂದುವರಿಯುವುದು.",
    "pushya": "ಪುಷ್ಯ ನಕ್ಷತ್ರದ ಅಧಿದೇವತೆ ದೇವತೆಗಳ ಗುರುವಾದ ಬೃಹಸ್ಪತಿ; ಇದರ ಸಂಕೇತ ಹಸುವಿನ ಕೆಚ್ಚಲು ಅಥವಾ ಕಮಲ — ಪೋಷಣೆಯ ಪ್ರತಿರೂಪಗಳು. ಇದನ್ನು ಅತ್ಯಂತ ಶುಭ ನಕ್ಷತ್ರಗಳಲ್ಲಿ ಒಂದೆಂದು ಪರಿಗಣಿಸಲಾಗುತ್ತದೆ; ಈ ನಕ್ಷತ್ರದಲ್ಲಿ ಚಂದ್ರನಿರುವವರು ಸಾಮಾನ್ಯವಾಗಿ ಕಾಳಜಿಯುಳ್ಳವರು, ನಂಬಿಕಸ್ಥರು, ಶ್ರದ್ಧಾವಂತರು ಮತ್ತು ತಮ್ಮ ಸಮಯವನ್ನು ಉದಾರವಾಗಿ ನೀಡುವವರು. ಇತರರಿಗೆ ಆಸರೆಯಾಗುವುದು, ಸಂಪ್ರದಾಯಗಳನ್ನು ಉಳಿಸುವುದು ಮತ್ತು ಶಾಶ್ವತವಾದುದನ್ನು ಕಟ್ಟುವುದು ಅವರಿಗೆ ಇಷ್ಟ. ಸಂಪ್ರದಾಯವು ಪುಷ್ಯವನ್ನು ಪೋಷಣೆ ಮತ್ತು ಜ್ಞಾನದೊಂದಿಗೆ ಜೋಡಿಸುತ್ತದೆ; ಆದ್ದರಿಂದ ಬೋಧನೆ, ಆಪ್ತಸಮಾಲೋಚನೆ, ಆಹಾರ, ಸಮಾಜಸೇವೆ, ಹಣಕಾಸು ಮತ್ತು ಆಧ್ಯಾತ್ಮಿಕ ಕಾರ್ಯ ಇದಕ್ಕೆ ಚೆನ್ನಾಗಿ ಹೊಂದುತ್ತವೆ. ಇದರ ವರ ಸ್ಥಿರವಾದ, ರಕ್ಷಿಸುವ ದಯೆ; ಇದರ ಪಾಠ ಇತರರನ್ನು ಪೋಷಿಸುವಷ್ಟೇ ನಿಷ್ಠೆಯಿಂದ ತನ್ನನ್ನೂ ಪೋಷಿಸಿಕೊಳ್ಳುವುದು.",
    "ashlesha": "ಆಶ್ಲೇಷ ನಕ್ಷತ್ರದ ಅಧಿದೇವತೆಗಳು ಸರ್ಪದೇವತೆಗಳಾದ ನಾಗರು; ಇದರ ಸಂಕೇತ ಸುರುಳಿ ಸುತ್ತಿದ ಸರ್ಪ — ಕುಂಡಲಿನಿ, ಅಡಗಿದ ಶಕ್ತಿ ಮತ್ತು ಆಳವಾದ ಜ್ಞಾನದ ಪ್ರತೀಕ. ಈ ನಕ್ಷತ್ರದಲ್ಲಿ ಚಂದ್ರನಿರುವವರು ಸಾಮಾನ್ಯವಾಗಿ ಸೂಕ್ಷ್ಮಗ್ರಾಹಿಗಳು, ಬುದ್ಧಿವಂತರು ಮತ್ತು ಇತರರು ಹೇಳದೆ ಬಿಟ್ಟದ್ದನ್ನು ಅರ್ಥಮಾಡಿಕೊಳ್ಳುವುದರಲ್ಲಿ ನಿಪುಣರು. ಅವರು ಮನವೊಲಿಸಬಲ್ಲವರು ಮತ್ತು ಯೋಜನಾಬದ್ಧರು, ಆತ್ಮರಕ್ಷಣೆಯ ಬಲವಾದ ಸಹಜ ಪ್ರವೃತ್ತಿಯುಳ್ಳವರು. ಸಂಪ್ರದಾಯವು ಆಶ್ಲೇಷವನ್ನು ಒಳನೋಟ ಮತ್ತು ಗಿಡಮೂಲಿಕೆಗಳ ಚಿಕಿತ್ಸಾ ಜ್ಞಾನದೊಂದಿಗೆ ಜೋಡಿಸುತ್ತದೆ; ಆದ್ದರಿಂದ ಮನೋವಿಜ್ಞಾನ, ಸಂಶೋಧನೆ, ವೈದ್ಯಕೀಯ, ಬರವಣಿಗೆ ಮತ್ತು ಸಂಧಾನ ಇದಕ್ಕೆ ಚೆನ್ನಾಗಿ ಹೊಂದುತ್ತವೆ. ಇದರ ವರ ಆಳವಾಗಿ ಭೇದಿಸುವ ತಿಳಿವಳಿಕೆ; ಇದರ ಪಾಠ ಆ ಒಳನೋಟವನ್ನು ಅಪ್ಪಿಕೊಳ್ಳಲು ಮತ್ತು ಗುಣಪಡಿಸಲು ಬಳಸುವುದು — ಸರ್ಪದ ಸುರುಳಿ ಕಾಪಾಡುವಂತೆ.",
    "magha": "ಮಖಾ ನಕ್ಷತ್ರದ ಅಧಿದೇವತೆಗಳು ಪೂರ್ವಜರಾದ ಪಿತೃಗಳು; ಇದರ ಸಂಕೇತ ರಾಜಸಿಂಹಾಸನ. ಈ ನಕ್ಷತ್ರದಲ್ಲಿ ಚಂದ್ರನಿರುವವರಲ್ಲಿ ಸಾಮಾನ್ಯವಾಗಿ ಸಹಜವಾದ ಘನತೆ, ಕುಟುಂಬ ಮತ್ತು ಸಂಪ್ರದಾಯದ ಬಗ್ಗೆ ಗೌರವ, ಹಾಗೂ ತಮಗೆ ದೊರೆತ ಹೆಸರಿಗೆ ತಕ್ಕಂತೆ ಬಾಳುವ ಬಯಕೆ ಇರುತ್ತದೆ. ಅವರು ತಮ್ಮವರ ಹೊಣೆ ಹೊರುವ ಉದಾರ ನಾಯಕರಾಗಬಲ್ಲರು. ಸಂಪ್ರದಾಯವು ಮಖಾವನ್ನು ವಂಶ, ಗೌರವ ಮತ್ತು ಅಧಿಕಾರದೊಂದಿಗೆ ಜೋಡಿಸುತ್ತದೆ; ಆದ್ದರಿಂದ ನಾಯಕತ್ವ, ಆಡಳಿತ, ಇತಿಹಾಸ, ಕಾನೂನು ಮತ್ತು ಪರಂಪರೆಯನ್ನು ಉಳಿಸುವ ಕೆಲಸಗಳು ಇದಕ್ಕೆ ಚೆನ್ನಾಗಿ ಹೊಂದುತ್ತವೆ. ಇದರ ವರ ಹೃದಯದ ಉದಾತ್ತತೆ; ಇದರ ಪಾಠ ಕಿರೀಟವನ್ನು ಹಗುರವಾಗಿ ಧರಿಸುವುದು — ಸೇವೆಯ ಮೂಲಕ ಮುನ್ನಡೆಸುವುದು ಮತ್ತು ಒಳ್ಳೆಯ ಕಾರ್ಯಗಳ ಮೂಲಕ ಪೂರ್ವಜರನ್ನು ಗೌರವಿಸುವುದು.",
    "purva-phalguni": "ಪುಬ್ಬ (ಪೂರ್ವ ಫಲ್ಗುಣಿ) ನಕ್ಷತ್ರದ ಅಧಿದೇವತೆ ಸೌಭಾಗ್ಯ ಮತ್ತು ದಾಂಪತ್ಯ ಸುಖದ ದೇವನಾದ ಭಗ; ಇದರ ಸಂಕೇತ ಮಂಚದ ಮುಂದಿನ ಕಾಲುಗಳು — ವಿಶ್ರಾಂತಿ ಮತ್ತು ಆನಂದದ ಪ್ರತೀಕ. ಈ ನಕ್ಷತ್ರದಲ್ಲಿ ಚಂದ್ರನಿರುವವರು ಸಾಮಾನ್ಯವಾಗಿ ಆತ್ಮೀಯರು, ಮನಮೋಹಕರು, ಸೃಜನಶೀಲರು ಮತ್ತು ಸಂಭ್ರಮ, ಸಂಗೀತ, ಒಳ್ಳೆಯ ಒಡನಾಟಗಳನ್ನು ಇಷ್ಟಪಡುವವರು. ಅವರು ಜನರನ್ನು ಒಗ್ಗೂಡಿಸುತ್ತಾರೆ ಮತ್ತು ತಾವು ಗಳಿಸಿದ್ದನ್ನು ನಿರಾಳವಾಗಿ ಅನುಭವಿಸುವುದನ್ನು ಬಲ್ಲರು. ಸಂಪ್ರದಾಯವು ಪುಬ್ಬವನ್ನು ಪ್ರೀತಿ, ಕಲೆಗಳು ಮತ್ತು ವಿರಾಮದೊಂದಿಗೆ ಜೋಡಿಸುತ್ತದೆ; ಆದ್ದರಿಂದ ಮನರಂಜನೆ, ವಿನ್ಯಾಸ, ಆತಿಥ್ಯ ಮತ್ತು ಸಂಬಂಧ ಕೇಂದ್ರಿತ ಕೆಲಸಗಳು ಇದಕ್ಕೆ ಚೆನ್ನಾಗಿ ಹೊಂದುತ್ತವೆ. ಇದರ ವರ ಸುಲಭವಾಗಿ ಹಂಚಿಕೊಳ್ಳುವ ಸಂತೋಷ; ಇದರ ಪಾಠ ಸುಖ ಮತ್ತು ಕರ್ತವ್ಯದ ನಡುವಿನ ಸಮತೋಲನ.",
    "uttara-phalguni": "ಉತ್ತರಾ (ಉತ್ತರ ಫಲ್ಗುಣಿ) ನಕ್ಷತ್ರದ ಅಧಿದೇವತೆ ಸ್ನೇಹ, ಒಪ್ಪಂದಗಳು ಮತ್ತು ವಿವಾಹ ಪ್ರತಿಜ್ಞೆಗಳ ದೇವನಾದ ಅರ್ಯಮ; ಇದರ ಸಂಕೇತ ಮಂಚದ ಹಿಂದಿನ ಕಾಲುಗಳು. ಇದರ ಜೋಡಿ ನಕ್ಷತ್ರವಾದ ಪುಬ್ಬ ಆನಂದಿಸಿದರೆ, ಉತ್ತರಾ ಬದ್ಧತೆ ತೋರುತ್ತದೆ. ಈ ನಕ್ಷತ್ರದಲ್ಲಿ ಚಂದ್ರನಿರುವವರು ಸಾಮಾನ್ಯವಾಗಿ ನಂಬಿಕಸ್ಥರು, ಸಹಾಯಕರು, ನ್ಯಾಯಪರರು ಮತ್ತು ಸ್ನೇಹಿತರು ಹಾಗೂ ಸಂಗಾತಿಗಳಿಗೆ ನಿಷ್ಠರು. ಕೊಟ್ಟ ಮಾತನ್ನು ಉಳಿಸಿಕೊಳ್ಳುತ್ತಾರೆ ಮತ್ತು ಇತರರಿಗೆ ನಿಜವಾಗಿ ಉಪಯೋಗವಾಗಲು ಬಯಸುತ್ತಾರೆ. ಸಂಪ್ರದಾಯವು ಈ ನಕ್ಷತ್ರವನ್ನು ಆಶ್ರಯದಾತೃತ್ವ ಮತ್ತು ದೀರ್ಘಕಾಲದ ಸಹಭಾಗಿತ್ವಗಳೊಂದಿಗೆ ಜೋಡಿಸುತ್ತದೆ; ಆದ್ದರಿಂದ ನಿರ್ವಹಣೆ, ಸಾರ್ವಜನಿಕ ಸೇವೆ, ಆಪ್ತಸಮಾಲೋಚನೆ, ಕಾನೂನು ಮತ್ತು ದತ್ತಿ ಕಾರ್ಯಗಳು ಇದಕ್ಕೆ ಚೆನ್ನಾಗಿ ಹೊಂದುತ್ತವೆ. ಇದರ ವರ ಅವಲಂಬಿಸಬಹುದಾದ ದಯೆ; ಇದರ ಪಾಠ ಸಹಾಯವನ್ನು ನೀಡುವಷ್ಟೇ ಸೌಜನ್ಯದಿಂದ ಸ್ವೀಕರಿಸುವುದು.",
    "hasta": "ಹಸ್ತ ನಕ್ಷತ್ರದ ಅಧಿದೇವತೆ ಪ್ರಕಾಶಮಾನ ಸೂರ್ಯನಾದ ಸವಿತೃ; ಇದರ ಸಂಕೇತ ಕೈ. ಈ ನಕ್ಷತ್ರದಲ್ಲಿ ಚಂದ್ರನಿರುವವರು ಸಾಮಾನ್ಯವಾಗಿ ಕುಶಲರು, ವ್ಯವಹಾರಜ್ಞರು, ಹಾಸ್ಯಪ್ರಜ್ಞೆಯುಳ್ಳವರು ಮತ್ತು ಮನಸ್ಸಿನಂತೆಯೇ ಕೈಗಳಿಂದಲೂ ಚತುರರು. ಕೆಲಸವನ್ನು ಮುಗಿಸುವುದು ಅವರಿಗೆ ಇಷ್ಟ, ಒಂದು ಆಲೋಚನೆಯನ್ನು ವಾಸ್ತವವಾಗಿಸಬಲ್ಲರು. ಸಂಪ್ರದಾಯವು ಹಸ್ತವನ್ನು ಕರಕೌಶಲ, ಗುಣಪಡಿಸುವ ಸ್ಪರ್ಶ ಮತ್ತು ಸಂಪನ್ಮೂಲಶೀಲತೆಯೊಂದಿಗೆ ಜೋಡಿಸುತ್ತದೆ; ಆದ್ದರಿಂದ ಕರಕುಶಲ ಕಲೆಗಳು, ಲಲಿತಕಲೆಗಳು, ಶಸ್ತ್ರಚಿಕಿತ್ಸೆ, ಮಸಾಜ್ ಚಿಕಿತ್ಸೆ, ಬರವಣಿಗೆ, ವ್ಯಾಪಾರ ಮತ್ತು ಯಾವುದೇ ಕೌಶಲಾಧಾರಿತ ವೃತ್ತಿ ಇದಕ್ಕೆ ಚೆನ್ನಾಗಿ ಹೊಂದುತ್ತವೆ. ಇದರ ವರ ರಚಿಸುವ ಮತ್ತು ದುರಸ್ತಿ ಮಾಡುವ ಸಾಮರ್ಥ್ಯ; ಇದರ ಪಾಠ ಪರಿಶ್ರಮಕ್ಕೆ ತನ್ನದೇ ಆದ ಫಲ ಸಿಗುತ್ತದೆ ಎಂದು ನಂಬಿ, ವಸ್ತುಗಳನ್ನು ತೆರೆದ ಕೈಯಿಂದ ಹಿಡಿಯುವುದು.",
    "chitra": "ಚಿತ್ತಾ (ಚಿತ್ರಾ) ನಕ್ಷತ್ರದ ಅಧಿದೇವತೆ ದಿವ್ಯ ಶಿಲ್ಪಿ ತ್ವಷ್ಟೃ, ವಿಶ್ವಕರ್ಮ ಎಂದೂ ಕರೆಯಲ್ಪಡುವವನು; ಇದರ ಸಂಕೇತ ಹೊಳೆಯುವ ರತ್ನ. ಇದರ ಹೆಸರಿನ ಅರ್ಥ \"ಉಜ್ವಲ\" ಅಥವಾ \"ಚಿತ್ರ\"; ಈ ನಕ್ಷತ್ರದಲ್ಲಿ ಚಂದ್ರನಿರುವವರಲ್ಲಿ ಸಾಮಾನ್ಯವಾಗಿ ಸೌಂದರ್ಯ, ವಿನ್ಯಾಸ ಮತ್ತು ರೂಪದ ಬಗ್ಗೆ ತೀವ್ರ ಪ್ರಜ್ಞೆ ಇರುತ್ತದೆ. ಉಪಯುಕ್ತವೂ ಆಕರ್ಷಕವೂ ಆದ ವಸ್ತುಗಳನ್ನು ರಚಿಸುವುದರಲ್ಲಿ ಅವರಿಗೆ ಆನಂದ, ಸೂಕ್ಷ್ಮ ವಿವರಗಳನ್ನು ಗಮನಿಸುತ್ತಾರೆ. ಸಂಪ್ರದಾಯವು ಚಿತ್ತಾವನ್ನು ವಾಸ್ತುಶಿಲ್ಪ, ಕಲೆಗಳು ಮತ್ತು ಕರಕೌಶಲದೊಂದಿಗೆ ಜೋಡಿಸುತ್ತದೆ; ಆದ್ದರಿಂದ ವಿನ್ಯಾಸ, ಎಂಜಿನಿಯರಿಂಗ್, ಫ್ಯಾಷನ್, ಆಭರಣ, ಛಾಯಾಗ್ರಹಣ ಮತ್ತು ಯೋಜನೆ ಇದಕ್ಕೆ ಚೆನ್ನಾಗಿ ಹೊಂದುತ್ತವೆ. ಇದರ ವರ ಕಲಾವಿದನ ಕಣ್ಣು ಮತ್ತು ನಿರ್ಮಾತೃವಿನ ಕೈ; ಇದರ ಪಾಠ ಬಾಹ್ಯ ಹೊಳಪಿನಷ್ಟೇ ಆಂತರಿಕ ಸೌಂದರ್ಯಕ್ಕೂ ಬೆಲೆ ಕೊಡುವುದು.",
    "swati": "ಸ್ವಾತಿ ನಕ್ಷತ್ರದ ಅಧಿದೇವತೆ ವಾಯು; ಇದರ ಸಂಕೇತ ತಂಗಾಳಿಯಲ್ಲಿ ತೂಗಾಡುವ ಎಳೆಯ ಚಿಗುರು — ಬಾಗುವ, ಸ್ವತಂತ್ರವಾದ, ಬಾಗಿದರೂ ಮುರಿಯದ ಚಿಗುರು. ಈ ನಕ್ಷತ್ರದಲ್ಲಿ ಚಂದ್ರನಿರುವವರು ಸಾಮಾನ್ಯವಾಗಿ ಸ್ವಾತಂತ್ರ್ಯ, ನ್ಯಾಯ ಮತ್ತು ತಮ್ಮದೇ ಆದ ಕಾರ್ಯವಿಧಾನಕ್ಕೆ ಬೆಲೆ ಕೊಡುತ್ತಾರೆ. ಅವರು ಸಾಮಾನ್ಯವಾಗಿ ಚಾಣಾಕ್ಷರು, ವಿನಯಶೀಲರು ಮತ್ತು ವ್ಯಾಪಾರ ಹಾಗೂ ಸಂಧಾನದಲ್ಲಿ ನಿಪುಣರು. ಸಂಪ್ರದಾಯವು ಸ್ವಾತಿಯನ್ನು ವ್ಯಾಪಾರ, ಪ್ರಯಾಣ ಮತ್ತು ಸ್ವಾವಲಂಬನೆಯೊಂದಿಗೆ ಜೋಡಿಸುತ್ತದೆ; ಆದ್ದರಿಂದ ವಾಣಿಜ್ಯ, ಕಾನೂನು, ರಾಜತಾಂತ್ರಿಕತೆ, ಸಂವಹನ ಮತ್ತು ಸ್ವತಂತ್ರ ಕೆಲಸ ಇದಕ್ಕೆ ಚೆನ್ನಾಗಿ ಹೊಂದುತ್ತವೆ. ಇದರ ವರ ಹೊಂದಿಕೊಳ್ಳುವ ಗುಣ ಮತ್ತು ಸೌಮ್ಯ, ಸಮತೋಲಿತ ನಡವಳಿಕೆ; ಇದರ ಪಾಠ ಬೇರೂರುವುದು — ಆಗ ಎಳೆಯ ಚಿಗುರು ಬಲಿಷ್ಠ ಮರವಾಗಿ ಬೆಳೆಯಬಲ್ಲದು.",
    "vishakha": "ವಿಶಾಖ ನಕ್ಷತ್ರದ ಅಧಿದೇವತೆಗಳು ಇಂದ್ರ ಮತ್ತು ಅಗ್ನಿ ಜೊತೆಯಾಗಿ; ಇದರ ಸಂಕೇತ ಎಲೆಗಳಿಂದ ಅಲಂಕರಿಸಿದ ವಿಜಯ ತೋರಣ. ಈ ನಕ್ಷತ್ರದಲ್ಲಿ ಚಂದ್ರನಿರುವವರು ಸಾಮಾನ್ಯವಾಗಿ ಗುರಿಯುಳ್ಳವರು, ಮಹತ್ವಾಕಾಂಕ್ಷಿಗಳು ಮತ್ತು ತಾವು ಇಟ್ಟುಕೊಂಡ ಗುರಿಯನ್ನು ತಲುಪಲು ದೃಢನಿಶ್ಚಯವುಳ್ಳವರು. ಅವರಲ್ಲಿ ಶಕ್ತಿ, ದೃಢವಿಶ್ವಾಸ ಮತ್ತು ದೀರ್ಘ ಹಾದಿಯಲ್ಲಿ ಮುಂದುವರಿಯುವ ತಾಳ್ಮೆ ಇರುತ್ತದೆ. ಸಂಪ್ರದಾಯವು ವಿಶಾಖವನ್ನು ಉದ್ದೇಶದ ನಕ್ಷತ್ರವೆನ್ನುತ್ತದೆ; ಆದ್ದರಿಂದ ನಾಯಕತ್ವ, ಸಂಶೋಧನೆ, ರಾಜಕೀಯ, ಮಾರಾಟ, ಬೋಧನೆ ಮತ್ತು ಯಾವುದೇ ದೀರ್ಘಾವಧಿಯ ಧ್ಯೇಯ ಇದಕ್ಕೆ ಚೆನ್ನಾಗಿ ಹೊಂದುತ್ತವೆ. ಇದರ ವರ ಏಕಾಗ್ರತೆ ಮತ್ತು ಹಂಚಿಕೊಂಡ ಗುರಿಯತ್ತ ಇತರರನ್ನು ಪ್ರೇರೇಪಿಸುವ ಸಾಮರ್ಥ್ಯ; ಇದರ ಪಾಠ ಕೊನೆಯ ತೋರಣವನ್ನು ಮಾತ್ರವಲ್ಲ, ಪಯಣವನ್ನೂ ಆನಂದಿಸುವುದು.",
    "anuradha": "ಅನುರಾಧ ನಕ್ಷತ್ರದ ಅಧಿದೇವತೆ ಸ್ನೇಹ ಮತ್ತು ಸಹಕಾರದ ದೇವನಾದ ಮಿತ್ರ; ಇದರ ಸಂಕೇತ ಕೆಸರು ನೀರಿನಿಂದ ಅರಳುವ ಕಮಲ. ಈ ನಕ್ಷತ್ರದಲ್ಲಿ ಚಂದ್ರನಿರುವವರು ಸಾಮಾನ್ಯವಾಗಿ ನಿಷ್ಠಾವಂತ ಸ್ನೇಹಿತರು, ತಮ್ಮ ಆದರ್ಶಗಳಿಗೆ ಬದ್ಧರು ಮತ್ತು ಕಠಿಣ ಸನ್ನಿವೇಶಗಳಲ್ಲೂ ಮೌನ ಶ್ರದ್ಧೆಯಿಂದ ಮುಂದುವರಿಯಬಲ್ಲವರು. ಗುಂಪುಗಳು ಮತ್ತು ಸಂಘಟನೆಗಳಲ್ಲಿ ಜನರನ್ನು ಒಗ್ಗೂಡಿಸುವುದರಲ್ಲಿ ನಿಪುಣರು. ಸಂಪ್ರದಾಯವು ಅನುರಾಧವನ್ನು ಸ್ನೇಹ, ಭಕ್ತಿ ಮತ್ತು ಮನೆಯಿಂದ ದೂರದಲ್ಲಿ ದೊರೆಯುವ ಯಶಸ್ಸಿನೊಂದಿಗೆ ಜೋಡಿಸುತ್ತದೆ; ಆದ್ದರಿಂದ ತಂಡದ ಕೆಲಸ, ಸಂಘಟನೆ, ಆಪ್ತಸಮಾಲೋಚನೆ, ಪ್ರಯಾಣ ಮತ್ತು ಆಧ್ಯಾತ್ಮಿಕ ಸಾಧನೆ ಇದಕ್ಕೆ ಚೆನ್ನಾಗಿ ಹೊಂದುತ್ತವೆ. ಇದರ ವರ ಎಲ್ಲಿಯಾದರೂ ಅರಳುವ ಸಾಮರ್ಥ್ಯ; ಇದರ ಪಾಠ ಸ್ನೇಹಿತರೊಂದಿಗೆ ಇರುವಷ್ಟೇ ಮೃದುವಾಗಿ ತನ್ನೊಂದಿಗೂ ಇರುವುದು.",
    "jyeshtha": "ಜ್ಯೇಷ್ಠ ನಕ್ಷತ್ರದ ಅಧಿದೇವತೆ ದೇವತೆಗಳ ರಾಜನಾದ ಇಂದ್ರ; ಇದರ ಸಂಕೇತ ವೃತ್ತಾಕಾರದ ತಾಯಿತ ಅಥವಾ ಕಿವಿಯೋಲೆ. ಇದರ ಹೆಸರಿನ ಅರ್ಥ \"ಹಿರಿಯ\"; ಈ ನಕ್ಷತ್ರದಲ್ಲಿ ಚಂದ್ರನಿರುವವರು ಸಾಮಾನ್ಯವಾಗಿ ಚಿಕ್ಕ ವಯಸ್ಸಿನಲ್ಲೇ ಹೊಣೆ ಹೊರುತ್ತಾರೆ, ಸುತ್ತಲಿನವರನ್ನು ಕಾಪಾಡುತ್ತಾರೆ ಮತ್ತು ಶಾಂತವಾದ ಅಧಿಕಾರವನ್ನು ಹೊಂದಿರುತ್ತಾರೆ. ಅವರು ಸಂಪನ್ಮೂಲಶೀಲರು, ಸೂಕ್ಷ್ಮಗ್ರಾಹಿಗಳು ಮತ್ತು ಒತ್ತಡದಲ್ಲೂ ಸಮರ್ಥರು. ಸಂಪ್ರದಾಯವು ಜ್ಯೇಷ್ಠವನ್ನು ಹಿರಿತನ ಮತ್ತು ರಕ್ಷಣೆಯೊಂದಿಗೆ ಜೋಡಿಸುತ್ತದೆ; ಆದ್ದರಿಂದ ನಾಯಕತ್ವ, ನಿರ್ವಹಣೆ, ಆಡಳಿತ, ಭದ್ರತೆ ಮತ್ತು ಇತರರನ್ನು ನೋಡಿಕೊಳ್ಳುವ ಯಾವುದೇ ಪಾತ್ರ ಇದಕ್ಕೆ ಚೆನ್ನಾಗಿ ಹೊಂದುತ್ತದೆ. ಇದರ ವರ ಧೈರ್ಯ ಮತ್ತು ಸಾಮರ್ಥ್ಯ; ಇದರ ಪಾಠ ವಿನಯದಿಂದ ಮುನ್ನಡೆಸುವುದು ಮತ್ತು ಎಲ್ಲವನ್ನೂ ಒಬ್ಬರೇ ಹೊರುವ ಬದಲು ಇತರರೂ ಭಾರ ಹಂಚಿಕೊಳ್ಳಲು ಬಿಡುವುದು.",
    "mula": "ಮೂಲ ನಕ್ಷತ್ರದ ಅಧಿದೇವತೆ ನಿರ್ಋತಿ; ಇದರ ಸಂಕೇತ ಬೇರುಗಳ ಗೊಂಚಲು. ಇದರ ಹೆಸರಿನ ಅರ್ಥ \"ಬೇರು\"; ಈ ನಕ್ಷತ್ರದಲ್ಲಿ ಚಂದ್ರನಿರುವವರು ಸಾಮಾನ್ಯವಾಗಿ ವಿಷಯಗಳ ಆಳಕ್ಕೆ ಇಳಿಯಲು ಬಯಸುತ್ತಾರೆ — ಒಂದು ಪ್ರಶ್ನೆ, ಆಲೋಚನೆ ಅಥವಾ ಸಂಪ್ರದಾಯದ ಮೂಲವನ್ನು ಹುಡುಕಲು. ಅವರು ಸ್ವತಂತ್ರರು, ತಾತ್ತ್ವಿಕರು ಮತ್ತು ಮೂಲ ತತ್ತ್ವಗಳಿಂದ ಮತ್ತೆ ಆರಂಭಿಸಲು ಅಂಜದವರು ಆಗಿರಬಹುದು. ಸಂಪ್ರದಾಯವು ಮೂಲವನ್ನು ಅನ್ವೇಷಣೆ ಮತ್ತು ಇನ್ನು ಬೇಕಿಲ್ಲದುದನ್ನು ಬಿಟ್ಟುಬಿಡುವುದರೊಂದಿಗೆ ಜೋಡಿಸುತ್ತದೆ; ಆದ್ದರಿಂದ ಸಂಶೋಧನೆ, ವೈದ್ಯಕೀಯ, ತತ್ತ್ವಶಾಸ್ತ್ರ, ಸಸ್ಯಶಾಸ್ತ್ರ ಮತ್ತು ಆಧ್ಯಾತ್ಮಿಕ ಜಿಜ್ಞಾಸೆ ಇದಕ್ಕೆ ಚೆನ್ನಾಗಿ ಹೊಂದುತ್ತವೆ. ಇದರ ವರ ಆಳ; ಇದರ ಪಾಠ — ಹಳೆಯ ನೆಲವನ್ನು ಹಸನುಗೊಳಿಸಿದಾಗ ಹೊಸ ಬೆಳವಣಿಗೆಗೆ ಜಾಗ ಸಿಗುತ್ತದೆ.",
    "purva-ashadha": "ಪೂರ್ವಾಷಾಢ ನಕ್ಷತ್ರದ ಅಧಿದೇವತೆ ವಿಶ್ವದ ಜಲಗಳಾದ ಆಪಃ; ಇದರ ಸಂಕೇತ ಮೊರ ಅಥವಾ ಆನೆಯ ದಂತ. ಇದರ ಹೆಸರಿನ ಅರ್ಥ \"ಮೊದಲ ಅಜೇಯ\"; ಈ ನಕ್ಷತ್ರದಲ್ಲಿ ಚಂದ್ರನಿರುವವರು ಸಾಮಾನ್ಯವಾಗಿ ಆತ್ಮವಿಶ್ವಾಸಿಗಳು, ಮನವೊಲಿಸಬಲ್ಲವರು ಮತ್ತು ದೃಢವಿಶ್ವಾಸದಿಂದ ತುಂಬಿದವರು. ನೀರಿನಂತೆ ಅವರು ಮೃದುವಾಗಿದ್ದರೂ ಕಾಲಕ್ರಮೇಣ ಯಾವುದೇ ಅಡ್ಡಿಯನ್ನು ಸವೆಸಬಲ್ಲರು. ಸಂಪ್ರದಾಯವು ಪೂರ್ವಾಷಾಢವನ್ನು ಶುದ್ಧೀಕರಣ ಮತ್ತು ಛಲದಿಂದ ಗಳಿಸಿದ ವಿಜಯದೊಂದಿಗೆ ಜೋಡಿಸುತ್ತದೆ; ಆದ್ದರಿಂದ ಬೋಧನೆ, ಕಾನೂನು, ಚರ್ಚೆ, ಕಲೆಗಳು, ಹಡಗು ಸಾಗಣೆ ಮತ್ತು ನೀರಿಗೆ ಸಂಬಂಧಿಸಿದ ಯಾವುದೇ ಕೆಲಸ ಇದಕ್ಕೆ ಚೆನ್ನಾಗಿ ಹೊಂದುತ್ತವೆ. ಇದರ ವರ ಆಶಾವಾದ ಮತ್ತು ಆಂತರಿಕ ಬಲ; ಇದರ ಪಾಠ ತನ್ನ ನಿಲುವಿಗೆ ದೃಢವಾಗಿ ನಿಂತೇ ಇತರರ ಅಭಿಪ್ರಾಯಗಳಿಗೂ ತೆರೆದ ಮನಸ್ಸಿನಿಂದಿರುವುದು.",
    "uttara-ashadha": "ಉತ್ತರಾಷಾಢ ನಕ್ಷತ್ರದ ಅಧಿದೇವತೆಗಳು ವಿಶ್ವದೇವತೆಗಳಾದ ವಿಶ್ವೇದೇವರು; ಇದರ ಸಂಕೇತ ಆನೆಯ ದಂತ. ಇದರ ಹೆಸರಿನ ಅರ್ಥ \"ನಂತರದ ಅಜೇಯ\" — ಪ್ರಾಮಾಣಿಕವಾಗಿ ಗಳಿಸಿದ್ದರಿಂದ ಶಾಶ್ವತವಾಗುವ ವಿಜಯ. ಈ ನಕ್ಷತ್ರದಲ್ಲಿ ಚಂದ್ರನಿರುವವರು ಸಾಮಾನ್ಯವಾಗಿ ತತ್ತ್ವನಿಷ್ಠರು, ತಾಳ್ಮೆಯುಳ್ಳವರು, ಜವಾಬ್ದಾರಿಯುತರು ಮತ್ತು ತಮ್ಮ ಪ್ರಾಮಾಣಿಕತೆಗಾಗಿ ಗೌರವಿಸಲ್ಪಡುವವರು. ಅವರು ದೂರದೃಷ್ಟಿಯಿಂದ ನೋಡುತ್ತಾರೆ ಮತ್ತು ಒಪ್ಪಿಕೊಂಡದ್ದನ್ನು ಪೂರ್ಣಗೊಳಿಸುತ್ತಾರೆ. ಸಂಪ್ರದಾಯವು ಉತ್ತರಾಷಾಢವನ್ನು ಧರ್ಮನಿಷ್ಠ ನಾಯಕತ್ವದೊಂದಿಗೆ ಜೋಡಿಸುತ್ತದೆ; ಆದ್ದರಿಂದ ಸರ್ಕಾರ, ನಿರ್ವಹಣೆ, ಕಾನೂನು, ಬೋಧನೆ ಮತ್ತು ಸಾಮಾಜಿಕ ಉದ್ದೇಶಗಳು ಇದಕ್ಕೆ ಚೆನ್ನಾಗಿ ಹೊಂದುತ್ತವೆ. ಇದರ ವರ ಸ್ಥಿರವಾದ, ನೈತಿಕ ಬಲ; ಇದರ ಪಾಠ ಕರ್ತವ್ಯದ ಗಂಭೀರತೆಯೊಂದಿಗೆ ಸ್ವಲ್ಪ ಲಘುತೆ ಮತ್ತು ಆತ್ಮೀಯತೆಯನ್ನೂ ಉಳಿಸಿಕೊಳ್ಳುವುದು.",
    "shravana": "ಶ್ರವಣ ನಕ್ಷತ್ರದ ಅಧಿದೇವತೆ ಪಾಲಕನಾದ ವಿಷ್ಣು; ಇದರ ಸಂಕೇತ ಕಿವಿ ಅಥವಾ ಮೂರು ಹೆಜ್ಜೆಗುರುತುಗಳು. ಇದರ ಹೆಸರಿನ ಅರ್ಥ \"ಕೇಳುವುದು\"; ಈ ನಕ್ಷತ್ರದಲ್ಲಿ ಚಂದ್ರನಿರುವವರು ಸಾಮಾನ್ಯವಾಗಿ ಒಳ್ಳೆಯ ಕೇಳುಗರು, ಉತ್ಸಾಹದ ಕಲಿಕಾರ್ಥಿಗಳು ಮತ್ತು ಜ್ಞಾನ ಹಾಗೂ ಸಂಪ್ರದಾಯದ ರಕ್ಷಕರು. ಅವರು ಕೇಳುವ ಮೂಲಕ ಕಲಿಯುತ್ತಾರೆ ಮತ್ತು ಕಲಿತದ್ದನ್ನು ಮುಂದಿನವರಿಗೆ ದಾಟಿಸುತ್ತಾರೆ. ಸಂಪ್ರದಾಯವು ಶ್ರವಣವನ್ನು ಅಧ್ಯಯನದಿಂದ ಗಳಿಸಿದ ಜ್ಞಾನ ಮತ್ತು ಜನರನ್ನು ಬೆಸೆಯುವುದರೊಂದಿಗೆ ಜೋಡಿಸುತ್ತದೆ; ಆದ್ದರಿಂದ ಬೋಧನೆ, ಆಪ್ತಸಮಾಲೋಚನೆ, ಮಾಧ್ಯಮ, ಭಾಷೆಗಳು, ಸಂಗೀತ ಮತ್ತು ಪ್ರಯಾಣ ಇದಕ್ಕೆ ಚೆನ್ನಾಗಿ ಹೊಂದುತ್ತವೆ. ಇದರ ವರ ಗಮನವಿಟ್ಟು ಅರಿಯುವ ಗುಣ ಮತ್ತು ಉಪಯೋಗವಾಗುವ ಬಯಕೆ; ಇದರ ಪಾಠ ಇತರರನ್ನು ಕೇಳುವಷ್ಟೇ ಎಚ್ಚರದಿಂದ ತನ್ನ ಅಂತರಂಗದ ಧ್ವನಿಯನ್ನೂ ಕೇಳುವುದು.",
    "dhanishta": "ಧನಿಷ್ಠ ನಕ್ಷತ್ರದ ಅಧಿದೇವತೆಗಳು ಸಮೃದ್ಧಿಯ ದೇವತೆಗಳಾದ ಅಷ್ಟ ವಸುಗಳು; ಇದರ ಸಂಕೇತ ಡೋಲು. ಇದರ ಹೆಸರಿನ ಅರ್ಥ \"ಅತ್ಯಂತ ಶ್ರೀಮಂತ\"; ಈ ನಕ್ಷತ್ರದಲ್ಲಿ ಚಂದ್ರನಿರುವವರಲ್ಲಿ ಸಾಮಾನ್ಯವಾಗಿ ಲಯ, ಶಕ್ತಿ ಮತ್ತು ಸಂಗೀತ, ನೃತ್ಯ ಅಥವಾ ತಂಡದ ಕೆಲಸದಲ್ಲಿ ಪ್ರತಿಭೆ ಇರುತ್ತದೆ. ಅವರು ಉದಾರಿಗಳು, ಬೆರೆಯುವ ಸ್ವಭಾವದವರು ಮತ್ತು ಗುಂಪನ್ನು ಒಟ್ಟಾಗಿ ಮುನ್ನಡೆಸಬಲ್ಲವರು. ಸಂಪ್ರದಾಯವು ಧನಿಷ್ಠವನ್ನು ಸಮೃದ್ಧಿ ಮತ್ತು ನಾದದೊಂದಿಗೆ ಜೋಡಿಸುತ್ತದೆ; ಆದ್ದರಿಂದ ಸಂಗೀತ, ಪ್ರದರ್ಶನ ಕಲೆ, ಕ್ರೀಡೆ, ಸ್ಥಿರಾಸ್ತಿ, ಹಣಕಾಸು ಮತ್ತು ಸಮುದಾಯ ಕಾರ್ಯ ಇದಕ್ಕೆ ಚೆನ್ನಾಗಿ ಹೊಂದುತ್ತವೆ. ಇದರ ವರ ಇತರರು ಅನುಸರಿಸುವ ತಾಳವನ್ನು ಹಾಕುವ ಸಾಮರ್ಥ್ಯ; ಇದರ ಪಾಠ ನುಡಿಸುವುದರ ಜೊತೆಗೆ ಆಲಿಸುವುದು — ಇತರರ ಲಯಕ್ಕೂ ಅವಕಾಶ ಕೊಡುವುದು.",
    "shatabhisha": "ಶತಭಿಷ ನಕ್ಷತ್ರದ ಅಧಿದೇವತೆ ವಿಶ್ವದ ಜಲಗಳ ಮತ್ತು ಸತ್ಯದ ಅಧಿಪತಿಯಾದ ವರುಣ; ಇದರ ಸಂಕೇತ ಖಾಲಿ ವೃತ್ತ. ಇದರ ಹೆಸರಿನ ಅರ್ಥ \"ನೂರು ವೈದ್ಯರು\"; ಈ ನಕ್ಷತ್ರದಲ್ಲಿ ಚಂದ್ರನಿರುವವರು ಸಾಮಾನ್ಯವಾಗಿ ಸ್ವತಂತ್ರ ಚಿಂತಕರು, ಏಕಾಂತಪ್ರಿಯರು, ಸತ್ಯನಿಷ್ಠರು ಮತ್ತು ವಸ್ತುಗಳು ನಿಜವಾಗಿ ಹೇಗೆ ಕೆಲಸ ಮಾಡುತ್ತವೆ ಎಂದು ಅರಿಯುವತ್ತ ಆಕರ್ಷಿತರು. ಇತರರು ಗಮನಿಸದ ಮಾದರಿಗಳನ್ನು ಅವರು ಕಾಣಬಲ್ಲರು. ಸಂಪ್ರದಾಯವು ಶತಭಿಷವನ್ನು ಚಿಕಿತ್ಸೆ ಮತ್ತು ಅಡಗಿದ ಸತ್ಯದ ಹುಡುಕಾಟದೊಂದಿಗೆ ಜೋಡಿಸುತ್ತದೆ; ಆದ್ದರಿಂದ ವೈದ್ಯಕೀಯ, ಸಂಶೋಧನೆ, ವಿಜ್ಞಾನ, ತಂತ್ರಜ್ಞಾನ, ಖಗೋಳಶಾಸ್ತ್ರ ಮತ್ತು ಪರ್ಯಾಯ ಚಿಕಿತ್ಸೆ ಇದಕ್ಕೆ ಚೆನ್ನಾಗಿ ಹೊಂದುತ್ತವೆ. ಇದರ ವರ ಸ್ಪಷ್ಟ, ಸ್ವಂತಿಕೆಯ ಒಳನೋಟ; ಇದರ ಪಾಠ ಇತರರನ್ನೂ ವೃತ್ತದೊಳಗೆ ಬರಮಾಡಿಕೊಳ್ಳುವುದು — ಅರಿತದ್ದನ್ನು ಆತ್ಮೀಯತೆಯಿಂದ ಹಂಚಿಕೊಳ್ಳುವುದು.",
    "purva-bhadrapada": "ಪೂರ್ವಾಭಾದ್ರ ನಕ್ಷತ್ರದ ಅಧಿದೇವತೆ ಶಿವನ ಒಂಟಿಕಾಲಿನ ರೂಪವಾದ ಅಜ ಏಕಪಾದ; ಇದರ ಸಂಕೇತ ಖಡ್ಗಗಳು ಅಥವಾ ಮಂಚದ ಮುಂದಿನ ಕಾಲುಗಳು. ಈ ನಕ್ಷತ್ರದಲ್ಲಿ ಚಂದ್ರನಿರುವವರು ಸಾಮಾನ್ಯವಾಗಿ ಆದರ್ಶವಾದಿಗಳು, ತೀವ್ರ ಸ್ವಭಾವದವರು ಮತ್ತು ತಾವು ನಂಬಿದ ಧ್ಯೇಯಕ್ಕೆ ಸಂಪೂರ್ಣವಾಗಿ ತಮ್ಮನ್ನು ಅರ್ಪಿಸಿಕೊಳ್ಳಲು ಸಿದ್ಧರು. ಅವರು ವಾಕ್ಚತುರರು, ಉದಾರಿಗಳು ಮತ್ತು ಆಳವಾದ ಆಧ್ಯಾತ್ಮಿಕತೆಯುಳ್ಳವರು ಆಗಿರಬಹುದು. ಸಂಪ್ರದಾಯವು ಪೂರ್ವಾಭಾದ್ರವನ್ನು ಪರಿವರ್ತನೆ ಮತ್ತು ತಪಸ್ಸಿನ ಅಗ್ನಿಯೊಂದಿಗೆ — ಉನ್ನತ ಗುರಿಗಾಗಿ ಪ್ರಾಮಾಣಿಕ ಪ್ರಯತ್ನದೊಂದಿಗೆ — ಜೋಡಿಸುತ್ತದೆ; ಆದ್ದರಿಂದ ಸಮಾಜ ಸುಧಾರಣೆ, ತತ್ತ್ವಶಾಸ್ತ್ರ, ಬರವಣಿಗೆ, ಸಂಶೋಧನೆ ಮತ್ತು ಆಧ್ಯಾತ್ಮಿಕ ಜೀವನ ಇದಕ್ಕೆ ಚೆನ್ನಾಗಿ ಹೊಂದುತ್ತವೆ. ಇದರ ವರ ಉತ್ಕಟ ಬದ್ಧತೆ; ಇದರ ಪಾಠ ತೀವ್ರತೆಯನ್ನು ತಾಳ್ಮೆ ಮತ್ತು ಶಾಂತಿಯಿಂದ ಹದಗೊಳಿಸುವುದು.",
    "uttara-bhadrapada": "ಉತ್ತರಾಭಾದ್ರ ನಕ್ಷತ್ರದ ಅಧಿದೇವತೆ ಆಳವಾದ ಜಲಗಳ ಸರ್ಪನಾದ ಅಹಿರ್ಬುಧ್ನ್ಯ; ಇದರ ಸಂಕೇತ ಮಂಚದ ಹಿಂದಿನ ಕಾಲುಗಳು ಅಥವಾ ಅವಳಿಗಳು. ಪೂರ್ವಾಭಾದ್ರದಲ್ಲಿ ಅಗ್ನಿ ಉರಿದರೆ, ಉತ್ತರಾಭಾದ್ರ ಶಾಂತ ಆಳದಲ್ಲಿ ನೆಲೆಗೊಳ್ಳುತ್ತದೆ. ಈ ನಕ್ಷತ್ರದಲ್ಲಿ ಚಂದ್ರನಿರುವವರು ಸಾಮಾನ್ಯವಾಗಿ ಜ್ಞಾನಿಗಳು, ತಾಳ್ಮೆಯುಳ್ಳವರು, ಸಮಚಿತ್ತರು ಮತ್ತು ಕರುಣಾಮಯಿಗಳು; ಅವರಲ್ಲಿ ಆತ್ಮಸಂಯಮ ಮತ್ತು ಸಲಹೆ ನೀಡುವ ಕೌಶಲ ಇರುತ್ತದೆ. ಮಾತನಾಡುವ ಮೊದಲು ಯೋಚಿಸುತ್ತಾರೆ ಮತ್ತು ಕಠಿಣ ಸಮಯದಲ್ಲಿ ಸ್ಥಿರವಾಗಿರುತ್ತಾರೆ. ಸಂಪ್ರದಾಯವು ಈ ನಕ್ಷತ್ರವನ್ನು ಆಳ, ತ್ಯಾಗ ಮತ್ತು ದಯೆಯೊಂದಿಗೆ ಜೋಡಿಸುತ್ತದೆ; ಆದ್ದರಿಂದ ಆಪ್ತಸಮಾಲೋಚನೆ, ದಾನಧರ್ಮ, ಬೋಧನೆ, ಸಂಶೋಧನೆ ಮತ್ತು ಆಧ್ಯಾತ್ಮಿಕ ಸಾಧನೆ ಇದಕ್ಕೆ ಚೆನ್ನಾಗಿ ಹೊಂದುತ್ತವೆ. ಇದರ ವರ ಪ್ರಶಾಂತ ಜ್ಞಾನ; ಇದರ ಪಾಠ ಅದನ್ನು ತನ್ನೊಳಗೇ ಇಟ್ಟುಕೊಳ್ಳದೆ ಸಕ್ರಿಯವಾಗಿ ಹಂಚಿಕೊಳ್ಳುವುದು.",
    "revati": "ರೇವತಿ ಕೊನೆಯ ನಕ್ಷತ್ರ. ಇದರ ಅಧಿದೇವತೆ ಪೂಷನ್ — ಪೋಷಿಸುವವನು, ಪ್ರಯಾಣಿಕರಿಗೆ ದಾರಿ ತೋರುವವನು ಮತ್ತು ಹಾದಿಯಲ್ಲಿ ಹಿಂಡುಗಳನ್ನು ಕಾಪಾಡುವವನು; ಇದರ ಸಂಕೇತ ಮೀನು. ಈ ನಕ್ಷತ್ರದಲ್ಲಿ ಚಂದ್ರನಿರುವವರು ಸಾಮಾನ್ಯವಾಗಿ ಸೌಮ್ಯರು, ದಯಾಳುಗಳು, ಕಲ್ಪನಾಶೀಲರು ಮತ್ತು ದುರ್ಬಲರ ರಕ್ಷಕರು; ಅವರಿಗೆ ಪ್ರಾಣಿಗಳು, ಕಲೆ ಮತ್ತು ಸಂಗೀತ ಪ್ರಿಯ. ಯಾವುದೇ ಪಯಣದಲ್ಲಿ ಅವರು ಒಳ್ಳೆಯ ಸಂಗಾತಿಗಳು ಮತ್ತು ಇತರರು ಸುರಕ್ಷಿತವಾಗಿ ಗಮ್ಯ ತಲುಪಲು ನೆರವಾಗುತ್ತಾರೆ. ಸಂಪ್ರದಾಯವು ರೇವತಿಯನ್ನು ಸುರಕ್ಷಿತ ಪ್ರಯಾಣ, ಸಮೃದ್ಧಿ ಮತ್ತು ಪೂರ್ಣತೆಯೊಂದಿಗೆ ಜೋಡಿಸುತ್ತದೆ; ಆದ್ದರಿಂದ ಆರೈಕೆಯ ಕೆಲಸ, ಕಲೆಗಳು, ಪ್ರಯಾಣ, ಆತಿಥ್ಯ ಮತ್ತು ಆಧ್ಯಾತ್ಮಿಕ ಜೀವನ ಇದಕ್ಕೆ ಚೆನ್ನಾಗಿ ಹೊಂದುತ್ತವೆ. ಇದರ ವರ ಕರುಣೆ ಮತ್ತು ಶ್ರದ್ಧೆ; ಇದರ ಪಾಠ ಎಲ್ಲರನ್ನೂ ನೋಡಿಕೊಳ್ಳುತ್ತಲೇ ತನ್ನನ್ನೂ ನೋಡಿಕೊಳ್ಳುವುದು.",
}.items():
    NAKSHATRA_TRAITS[_k]["kn"] = _v

# Telugu
for _k, _v in {
    "ashwini": "అశ్విని మొదటి నక్షత్రం. దీని అధిదేవతలు దేవతల వైద్యులైన కవల సోదరులు అశ్వినీ కుమారులు, దీని చిహ్నం గుర్రపు ముఖం. ఈ నక్షత్రంలో చంద్రుడు ఉన్నవారు తరచుగా చురుకుగా, ఉత్సాహంగా ఉంటారు, కొత్త పనులు మొదలుపెట్టడానికి ఆసక్తి చూపుతారు — సాయం చేయడంలో ముందుంటారు, కొత్తదాన్ని ప్రయత్నించడంలో మొదటివారుగా ఉంటారు. సంప్రదాయం అశ్వినిని వైద్యం, వేగం, కొత్త ఆరంభాలతో ముడిపెడుతుంది; అందుకే చాలామంది వైద్యం, క్రీడలు, ప్రయాణం లేదా వేగంగా, ఆచరణాత్మకంగా వ్యవహరించాల్సిన ఏ పని వైపైనా ఆకర్షితులవుతారు. ఈ నక్షత్రం ఇచ్చే వరం చొరవ, యవ్వనపు ఆశావాదం; నేర్చుకోవలసిన పాఠం ఓర్పు — ఏ ఉత్సాహంతో మొదలుపెట్టారో అదే ఉత్సాహంతో పనిని పూర్తి చేయడం.",
    "bharani": "భరణి నక్షత్రానికి అధిదేవత ధర్మానికి అధిపతి అయిన యముడు; దీని చిహ్నం యోని — కొత్త ప్రాణాన్ని మోసి కాపాడే గర్భం. ఈ నక్షత్రంలో చంద్రుడు ఉన్నవారికి తరచుగా దృఢమైన సంకల్పం, లోతైన భావాలు, బాధ్యత పట్ల గంభీరమైన అవగాహన ఉంటాయి. తాము చేపట్టిన బాధ్యతలను చివరి వరకు నిర్వర్తిస్తారు, సులభంగా ఊగిసలాడరు. సంప్రదాయం భరణిని మోయడం, పోషించడం అనే గుణాల నక్షత్రంగా చూస్తుంది — దేనినైనా అది జన్మించడానికి సిద్ధమయ్యే వరకు కాపాడుకోవడం — అందుకే సృజనాత్మకత, కుటుంబం, కళలు, సహనం అవసరమైన పనులు దీనికి బాగా సరిపోతాయి. దీని బలం నిలకడ; దీని పాఠం కోరికను సంయమనంతో, దయతో సమతుల్యం చేసుకోవడం.",
    "krittika": "కృత్తిక నక్షత్రానికి అధిదేవత పవిత్రమైన అగ్ని; దీని చిహ్నం కత్తి లేదా జ్వాల. అగ్ని శుద్ధి చేస్తుంది, గందరగోళాన్ని ఛేదిస్తుంది; ఈ నక్షత్రంలో చంద్రుడు ఉన్నవారు తరచుగా సూటిగా మాట్లాడేవారు, సిద్ధాంతాలకు కట్టుబడినవారు, పదునైన విచక్షణ కలవారు. తాము ప్రేమించేవారిని కాపాడుకుంటారు, చెప్పవలసిన మాటను చెప్పడానికి వెనుకాడరు. కార్తికేయుని పెంచిన ఆరుగురు తల్లుల నక్షత్రం కూడా కృత్తికే; అందుకే ఆ పదును వెనుక నిజమైన ఆప్యాయత, శ్రద్ధ ఉంటాయి. బోధన, వంట, నాయకత్వం, స్పష్టత అవసరమైన ఏ పనైనా దీనికి సరిపోతుంది. దీని పాఠం — అగ్ని కాల్చడం కాకుండా వెచ్చదనం ఇచ్చి దారి చూపేలా చేయడం.",
    "rohini": "రోహిణి నక్షత్రానికి అధిదేవత సృష్టికర్త బ్రహ్మ; దీని చిహ్నం రథం లేదా ఎడ్ల బండి. ఇది చంద్రునికి అత్యంత ప్రియమైన నక్షత్రమని చెబుతారు; ఈ నక్షత్రంలో చంద్రుడు ఉన్నవారు తరచుగా ఆప్యాయంగా, ఆకర్షణీయంగా, కళాభిరుచితో ఉంటారు, సౌకర్యాన్నీ అందాన్నీ ఇష్టపడతారు. దేనినైనా ఎదిగేలా చేసే ప్రతిభ వారికి ఉంటుంది — తోటలు, ఇళ్లు, వ్యాపారాలు, బంధాలు. సంప్రదాయం రోహిణిని ఫలవంతం, సమృద్ధి, స్థిరమైన పురోగతితో ముడిపెడుతుంది; అందుకే వ్యవసాయం, కళలు, డిజైన్, ఆహారం, ఆతిథ్యం దీనికి బాగా సరిపోతాయి. దీని స్వభావం సౌమ్యం, స్థిరం; దీని పాఠం — అందమైనదాన్ని ఆస్వాదిస్తూనే దాన్ని మరీ గట్టిగా పట్టుకోకపోవడం.",
    "mrigashira": "మృగశిర నక్షత్రానికి అధిదేవత సోముడు (చంద్రుడు); దీని చిహ్నం జింక తల — ఎప్పుడూ అప్రమత్తంగా, కుతూహలంగా, వెతుకుతూ ఉండే జింక. ఈ నక్షత్రంలో చంద్రుడు ఉన్నవారు తరచుగా సౌమ్యులు, జిజ్ఞాస కలవారు; చదువు, ప్రయాణం, సంభాషణ అంటే ఇష్టపడతారు. ఆలోచనలనూ ప్రదేశాలనూ అన్వేషించడం వారికి ఆనందం, ప్రశ్నలు అడగడం అరుదుగా ఆపుతారు. సంప్రదాయం మృగశిరను అన్వేషకుని నక్షత్రంగా చూస్తుంది; పరిశోధన, రచన, బోధన, వ్యాపారం, కుతూహలానికి ఫలితమిచ్చే ఏ పనైనా దీనికి సరిపోతుంది. దీని ఆకర్షణ తేలికైన, స్నేహపూర్వకమైన మనసు; దీని పాఠం — కనుగొన్నదానిపై స్థిరపడటం, అప్పుడే అన్వేషణ అశాంతిగా మారకుండా ఒక గమ్యానికి చేరుతుంది.",
    "ardra": "ఆర్ద్ర నక్షత్రానికి అధిదేవత శివుని తుఫాను రూపమైన రుద్రుడు; దీని చిహ్నం కన్నీటి బిందువు లేదా వజ్రం. తుఫాను గాలిని శుభ్రపరిచి వర్షాన్ని తెచ్చినట్లే, ఈ నక్షత్రంలో చంద్రుడు ఉన్నవారికి తరచుగా బలమైన, శోధించే బుద్ధి, విషయాల లోతుకు వెళ్లి సత్యాన్ని చూసే సామర్థ్యం ఉంటాయి. వారు లోతుగా అనుభూతి చెందుతారు, మార్పుకు భయపడరు. సంప్రదాయం ఆర్ద్రను కష్టం తర్వాత వచ్చే పునరుద్ధరణతో ముడిపెడుతుంది; అందుకే పరిశోధన, సాంకేతికత, రచన, కౌన్సెలింగ్, సమస్యల పరిష్కారం దీనికి బాగా సరిపోతాయి. దీని వరం నిజాయితీ, పదునైన బుద్ధి; దీని పాఠం — భావాలను వర్షంలా కురిసి వెళ్లనివ్వడం, నేలను మరింత పచ్చగా వదిలి.",
    "punarvasu": "పునర్వసు నక్షత్రానికి అధిదేవత దేవతల తల్లి, అనంతమైన అదితి; దీని చిహ్నం విల్లు, అమ్ముల పొది. దీని పేరుకు అర్థం “వెలుగు తిరిగి రావడం”; ఈ నక్షత్రంలో చంద్రుడు ఉన్నవారు తరచుగా ఆశావాదులు, ఉదారులు, ఏ ఎదురుదెబ్బ తర్వాతైనా మళ్లీ మొదలుపెట్టగలవారు. సాధారణమైన విషయాలతో తృప్తి పడతారు, హాస్యప్రియులు, కుటుంబం పట్లా అతిథుల పట్లా శ్రద్ధ చూపుతారు. సంప్రదాయం పునర్వసును పునరుద్ధరణ, ఇంటికి తిరిగి రావడం అనే భావాల నక్షత్రంగా చూస్తుంది; బోధన, కౌన్సెలింగ్, రచన, ప్రయాణం, సేవా రంగం దీనికి సరిపోతాయి. దీని ఆశీర్వాదం ఆశతో నిండిన, క్షమించే హృదయం; దీని పాఠం బాణాన్ని గురిపెట్టడం — ఒక దిశను ఎంచుకుని దానితోనే నిలవడం.",
    "pushya": "పుష్యమి నక్షత్రానికి అధిదేవత దేవతల గురువు బృహస్పతి; దీని చిహ్నం ఆవు పొదుగు లేదా పద్మం — పోషణకు ప్రతీకలు. ఇది అత్యంత శుభప్రదమైన నక్షత్రాలలో ఒకటిగా పరిగణించబడుతుంది; ఈ నక్షత్రంలో చంద్రుడు ఉన్నవారు తరచుగా శ్రద్ధ చూపేవారు, నమ్మదగినవారు, భక్తిపరులు, తమ సమయాన్ని ఉదారంగా ఇచ్చేవారు. ఇతరులకు అండగా నిలవడం, సంప్రదాయాలను కాపాడటం, శాశ్వతంగా నిలిచేదాన్ని నిర్మించడం వారికి ఇష్టం. సంప్రదాయం పుష్యమిని పోషణ, జ్ఞానంతో ముడిపెడుతుంది; అందుకే బోధన, కౌన్సెలింగ్, ఆహారం, సమాజ సేవ, ఆర్థిక రంగం, ఆధ్యాత్మిక కార్యాలు దీనికి బాగా సరిపోతాయి. దీని వరం స్థిరమైన, రక్షణనిచ్చే దయ; దీని పాఠం — ఇతరులను పోషించినంత శ్రద్ధగా తనను తాను కూడా పోషించుకోవడం.",
    "ashlesha": "ఆశ్లేష నక్షత్రానికి అధిదేవతలు సర్ప దేవతలైన నాగులు; దీని చిహ్నం చుట్టుకున్న సర్పం — కుండలిని, దాగి ఉన్న శక్తి, లోతైన జ్ఞానానికి ప్రతీక. ఈ నక్షత్రంలో చంద్రుడు ఉన్నవారు తరచుగా సూక్ష్మగ్రాహులు, తెలివైనవారు, ఇతరులు చెప్పకుండా వదిలేసినదాన్ని అర్థం చేసుకోవడంలో నేర్పరులు. వారు ఇతరులను ఒప్పించగలరు, వ్యూహాత్మకంగా ఆలోచించగలరు, తమను తాము కాపాడుకునే బలమైన సహజ ప్రవృత్తి కలవారు. సంప్రదాయం ఆశ్లేషను అంతర్దృష్టితో, మూలికల వైద్య జ్ఞానంతో ముడిపెడుతుంది; అందుకే మనస్తత్వశాస్త్రం, పరిశోధన, వైద్యం, రచన, చర్చలు-ఒప్పందాలు దీనికి బాగా సరిపోతాయి. దీని వరం లోతైన అవగాహన; దీని పాఠం — సర్పం చుట్ట కాపాడినట్లే, ఆ అంతర్దృష్టిని అక్కున చేర్చుకోవడానికి, స్వస్థపరచడానికి ఉపయోగించడం.",
    "magha": "మఖ నక్షత్రానికి అధిదేవతలు పితృదేవతలు (పూర్వీకులు); దీని చిహ్నం రాజ సింహాసనం. ఈ నక్షత్రంలో చంద్రుడు ఉన్నవారిలో తరచుగా సహజమైన హుందాతనం, కుటుంబం పట్లా సంప్రదాయం పట్లా గౌరవం, తమకు లభించిన పేరుకు తగినట్లు జీవించాలనే కోరిక కనిపిస్తాయి. వారు తమవారి బాధ్యత తీసుకునే ఉదారమైన నాయకులు కాగలరు. సంప్రదాయం మఖను వంశం, గౌరవం, అధికారంతో ముడిపెడుతుంది; అందుకే నాయకత్వం, పరిపాలన, చరిత్ర, న్యాయం, వారసత్వాన్ని కాపాడే పనులు దీనికి బాగా సరిపోతాయి. దీని వరం హృదయ ఔన్నత్యం; దీని పాఠం కిరీటాన్ని తేలికగా ధరించడం — సేవ ద్వారా నాయకత్వం వహించడం, మంచి పనుల ద్వారా పూర్వీకులను గౌరవించడం.",
    "purva-phalguni": "పుబ్బ (పూర్వ ఫల్గుణి) నక్షత్రానికి అధిదేవత అదృష్టానికీ దాంపత్య సుఖానికీ దేవుడైన భగుడు; దీని చిహ్నం మంచం ముందు కాళ్లు — విశ్రాంతికీ ఆనందానికీ ప్రతీక. ఈ నక్షత్రంలో చంద్రుడు ఉన్నవారు తరచుగా ఆప్యాయంగా, ఆకర్షణీయంగా, సృజనాత్మకంగా ఉంటారు; వేడుకలు, సంగీతం, మంచి సాంగత్యం అంటే ఇష్టపడతారు. వారు మనుషులను ఒక్కచోట చేరుస్తారు; విశ్రాంతి తీసుకోవడం, తాము సంపాదించినదాన్ని ఆస్వాదించడం వారికి తెలుసు. సంప్రదాయం పుబ్బను ప్రేమ, కళలు, విరామంతో ముడిపెడుతుంది; అందుకే వినోద రంగం, డిజైన్, ఆతిథ్యం, సంబంధాలపై ఆధారపడిన పనులు దీనికి బాగా సరిపోతాయి. దీని వరం సులభంగా పంచుకునే ఆనందం; దీని పాఠం సుఖానికీ కర్తవ్యానికీ మధ్య సమతుల్యం.",
    "uttara-phalguni": "ఉత్తర (ఉత్తర ఫల్గుణి) నక్షత్రానికి అధిదేవత స్నేహం, ఒప్పందాలు, వివాహ ప్రమాణాలకు దేవుడైన అర్యముడు; దీని చిహ్నం మంచం వెనుక కాళ్లు. దీని జంట నక్షత్రమైన పుబ్బ ఆస్వాదిస్తే, ఉత్తర కట్టుబడుతుంది. ఈ నక్షత్రంలో చంద్రుడు ఉన్నవారు తరచుగా నమ్మదగినవారు, సాయపడేవారు, న్యాయబుద్ధి కలవారు, స్నేహితులకూ భాగస్వాములకూ విశ్వాసపాత్రులు. ఇచ్చిన మాట నిలబెట్టుకుంటారు, ఇతరులకు నిజంగా ఉపయోగపడాలని కోరుకుంటారు. సంప్రదాయం ఈ నక్షత్రాన్ని ఆదరణ, శాశ్వత భాగస్వామ్యాలతో ముడిపెడుతుంది; అందుకే నిర్వహణ, ప్రజా సేవ, కౌన్సెలింగ్, న్యాయం, దాతృత్వ కార్యాలు దీనికి బాగా సరిపోతాయి. దీని వరం నమ్మదగిన దయ; దీని పాఠం — సాయం చేసినంత హుందాగా సాయాన్ని స్వీకరించడం కూడా.",
    "hasta": "హస్త నక్షత్రానికి అధిదేవత ప్రకాశించే సూర్యుడైన సవిత; దీని చిహ్నం చేయి. ఈ నక్షత్రంలో చంద్రుడు ఉన్నవారు తరచుగా నైపుణ్యం కలవారు, ఆచరణాత్మకులు, చమత్కారులు; చేతులతోనూ బుద్ధితోనూ చాకచక్యం చూపుతారు. పనులు పూర్తి చేయడం వారికి ఇష్టం, ఒక ఆలోచనను వాస్తవంగా మార్చగలరు. సంప్రదాయం హస్తను హస్తకళా నైపుణ్యం, స్వస్థపరిచే స్పర్శ, వనరులను చక్కగా వాడుకునే చతురతతో ముడిపెడుతుంది; అందుకే చేతిపనులు, కళలు, శస్త్రచికిత్స, మర్దన, రచన, వ్యాపారం, ఏ నైపుణ్య వృత్తి అయినా దీనికి బాగా సరిపోతుంది. దీని వరం తయారు చేయడం, బాగుచేయడం అనే సామర్థ్యం; దీని పాఠం — తెరిచిన చేతితో పట్టుకోవడం, శ్రమ తన ఫలాన్ని తానే తెస్తుందని నమ్మడం.",
    "chitra": "చిత్త (చిత్ర) నక్షత్రానికి అధిదేవత దివ్య శిల్పి విశ్వకర్మగా కూడా పిలువబడే త్వష్ట; దీని చిహ్నం మెరిసే రత్నం. దీని పేరుకు అర్థం “ప్రకాశవంతమైనది” లేదా “చిత్రం”; ఈ నక్షత్రంలో చంద్రుడు ఉన్నవారికి తరచుగా అందం, రూపకల్పన, ఆకృతి పట్ల బలమైన అభిరుచి ఉంటుంది. ఉపయోగకరంగానూ ఆకర్షణీయంగానూ ఉండే వస్తువులను సృష్టించడం వారికి ఆనందం, చిన్న వివరాలనూ గమనిస్తారు. సంప్రదాయం చిత్తను వాస్తుశిల్పం, కళలు, హస్తకళా నైపుణ్యంతో ముడిపెడుతుంది; అందుకే డిజైన్, ఇంజినీరింగ్, ఫ్యాషన్, ఆభరణాలు, ఫోటోగ్రఫీ, ప్రణాళిక దీనికి బాగా సరిపోతాయి. దీని వరం కళాకారుని కన్ను, నిర్మాత చేయి; దీని పాఠం — బాహ్య మెరుగుకు ఇచ్చినంత విలువను అంతర సౌందర్యానికీ ఇవ్వడం.",
    "swati": "స్వాతి నక్షత్రానికి అధిదేవత వాయుదేవుడు; దీని చిహ్నం గాలికి ఊగే లేత మొలక — సరళమైన, స్వతంత్రమైన, వంగినా విరగని మొలక. ఈ నక్షత్రంలో చంద్రుడు ఉన్నవారు తరచుగా స్వేచ్ఛకు, న్యాయానికి, తమదైన పద్ధతికి విలువ ఇస్తారు. సాధారణంగా వారు దౌత్యనైపుణ్యం, మర్యాద కలవారు, వ్యాపారంలోనూ చర్చల్లోనూ నేర్పరులు. సంప్రదాయం స్వాతిని వాణిజ్యం, ప్రయాణం, స్వావలంబనతో ముడిపెడుతుంది; అందుకే వ్యాపారం, న్యాయం, దౌత్యం, సమాచార రంగం, స్వతంత్రంగా చేసే పనులు దీనికి బాగా సరిపోతాయి. దీని వరం పరిస్థితులకు అనుగుణంగా మారే గుణం, సౌమ్యమైన సమతుల స్వభావం; దీని పాఠం వేళ్లూనుకోవడం — అప్పుడే ఆ లేత మొలక బలమైన చెట్టుగా ఎదుగుతుంది.",
    "vishakha": "విశాఖ నక్షత్రానికి అధిదేవతలు ఇంద్రుడు, అగ్ని కలిసి; దీని చిహ్నం ఆకులతో అలంకరించిన విజయ తోరణం. ఈ నక్షత్రంలో చంద్రుడు ఉన్నవారు తరచుగా స్పష్టమైన లక్ష్యం, ఆశయం కలవారు, తాము నిర్ణయించుకున్న గమ్యాన్ని చేరాలనే పట్టుదల కలవారు. వారిలో శక్తి, దృఢ విశ్వాసం, సుదీర్ఘ ప్రయాణంలో ముందుకు సాగే ఓర్పు ఉంటాయి. సంప్రదాయం విశాఖను లక్ష్యానికి నక్షత్రంగా పిలుస్తుంది; అందుకే నాయకత్వం, పరిశోధన, రాజకీయాలు, అమ్మకాలు, బోధన, ఏ దీర్ఘకాలిక లక్ష్యమైనా దీనికి బాగా సరిపోతాయి. దీని వరం ఏకాగ్రత, ఉమ్మడి లక్ష్యం వైపు ఇతరులకు స్ఫూర్తినిచ్చే సామర్థ్యం; దీని పాఠం — చివర ఉన్న తోరణాన్నే కాక, ప్రయాణాన్నీ ఆస్వాదించడం.",
    "anuradha": "అనూరాధ నక్షత్రానికి అధిదేవత స్నేహానికీ సహకారానికీ దేవుడైన మిత్రుడు; దీని చిహ్నం బురద నీటిలో వికసించే పద్మం. ఈ నక్షత్రంలో చంద్రుడు ఉన్నవారు తరచుగా విశ్వాసపాత్రులైన స్నేహితులు, తమ ఆదర్శాలకు అంకితమైనవారు, కష్టమైన పరిస్థితుల్లోనూ నిశ్శబ్ద విశ్వాసంతో ముందుకు సాగగలవారు. బృందాల్లో, సంస్థల్లో మనుషులను ఒక్కటి చేయడంలో నేర్పరులు. సంప్రదాయం అనూరాధను స్నేహం, భక్తి, ఇంటికి దూరంగా సాధించే విజయంతో ముడిపెడుతుంది; అందుకే బృంద కార్యం, సంస్థాగత నిర్వహణ, కౌన్సెలింగ్, ప్రయాణం, ఆధ్యాత్మిక సాధన దీనికి బాగా సరిపోతాయి. దీని వరం ఎక్కడైనా వికసించగల సామర్థ్యం; దీని పాఠం — స్నేహితుల పట్ల ఉన్నంత మృదువుగా తన పట్ల కూడా ఉండటం.",
    "jyeshtha": "జ్యేష్ఠ నక్షత్రానికి అధిదేవత దేవతల రాజు ఇంద్రుడు; దీని చిహ్నం గుండ్రని రక్షరేకు లేదా కర్ణాభరణం. దీని పేరుకు అర్థం “అందరికన్నా పెద్దది”; ఈ నక్షత్రంలో చంద్రుడు ఉన్నవారు తరచుగా చిన్న వయసులోనే బాధ్యతలు తీసుకుంటారు, చుట్టూ ఉన్నవారిని కాపాడతారు, నిశ్శబ్దమైన అధికారాన్ని కలిగి ఉంటారు. వారు వనరులను చక్కగా వాడుకునేవారు, సూక్ష్మగ్రాహులు, ఒత్తిడిలోనూ సమర్థులు. సంప్రదాయం జ్యేష్ఠను పెద్దరికం, రక్షణతో ముడిపెడుతుంది; అందుకే నాయకత్వం, నిర్వహణ, పరిపాలన, భద్రత, ఇతరులను చూసుకునే ఏ బాధ్యతైనా దీనికి బాగా సరిపోతుంది. దీని వరం ధైర్యం, సామర్థ్యం; దీని పాఠం — వినయంతో నడిపించడం, అన్నింటినీ ఒంటరిగా మోయకుండా భారాన్ని ఇతరులతో పంచుకోవడం.",
    "mula": "మూల నక్షత్రానికి అధిదేవత నిర్ఋతి; దీని చిహ్నం వేళ్ల గుత్తి. దీని పేరుకు అర్థం “వేరు”; ఈ నక్షత్రంలో చంద్రుడు ఉన్నవారు తరచుగా విషయాల మూలానికి వెళ్లాలని కోరుకుంటారు — ఒక ప్రశ్న, ఆలోచన లేదా సంప్రదాయం ఎక్కడ పుట్టిందో కనుగొనాలని. వారు స్వతంత్రులు, తాత్వికులు, మౌలిక సూత్రాల నుంచి మళ్లీ మొదలుపెట్టడానికి వెనుకాడనివారు కాగలరు. సంప్రదాయం మూలను పరిశోధనతో, ఇక అవసరం లేనిదాన్ని వదిలిపెట్టడంతో ముడిపెడుతుంది; అందుకే పరిశోధన, వైద్యం, తత్వశాస్త్రం, వృక్షశాస్త్రం, ఆధ్యాత్మిక అన్వేషణ దీనికి బాగా సరిపోతాయి. దీని వరం లోతు; దీని పాఠం — పాత నేలను శుభ్రం చేస్తేనే కొత్త ఎదుగుదలకు చోటు దొరుకుతుంది.",
    "purva-ashadha": "పూర్వాషాఢ నక్షత్రానికి అధిదేవత విశ్వ జలాలైన ఆపః; దీని చిహ్నం చేట లేదా ఏనుగు దంతం. దీని పేరుకు అర్థం “తొలి అజేయం”; ఈ నక్షత్రంలో చంద్రుడు ఉన్నవారు తరచుగా ఆత్మవిశ్వాసం, ఒప్పించే నేర్పు, దృఢ నమ్మకం నిండినవారు. నీటిలాగే వారు మృదువుగా ఉంటూనే కాలక్రమంలో ఏ అడ్డంకినైనా కరిగించగలరు. సంప్రదాయం పూర్వాషాఢను శుద్ధితో, పట్టుదలతో సాధించే విజయంతో ముడిపెడుతుంది; అందుకే బోధన, న్యాయం, వాదప్రతివాదాలు, కళలు, నౌకాయానం, నీటికి సంబంధించిన ఏ పనైనా దీనికి బాగా సరిపోతాయి. దీని వరం ఆశావాదం, అంతర్గత బలం; దీని పాఠం — తన అభిప్రాయంపై దృఢంగా నిలుస్తూనే ఇతరుల అభిప్రాయాలకూ తెరిచి ఉండటం.",
    "uttara-ashadha": "ఉత్తరాషాఢ నక్షత్రానికి అధిదేవతలు విశ్వదేవతలు; దీని చిహ్నం ఏనుగు దంతం. దీని పేరుకు అర్థం “తరువాతి అజేయం” — నిజాయితీగా సంపాదించినందువల్ల నిలిచి ఉండే విజయం. ఈ నక్షత్రంలో చంద్రుడు ఉన్నవారు తరచుగా సిద్ధాంతబద్ధులు, ఓర్పు కలవారు, బాధ్యతాయుతులు, తమ నిజాయితీకి గౌరవం పొందేవారు. దీర్ఘదృష్టితో ఆలోచిస్తారు, చేపట్టినది పూర్తి చేస్తారు. సంప్రదాయం ఉత్తరాషాఢను ధర్మబద్ధమైన నాయకత్వంతో ముడిపెడుతుంది; అందుకే ప్రభుత్వం, నిర్వహణ, న్యాయం, బోధన, సామాజిక ఆశయాలు దీనికి బాగా సరిపోతాయి. దీని వరం స్థిరమైన, నైతిక బలం; దీని పాఠం — కర్తవ్యపు గంభీరతతో పాటు కొంచెం తేలికదనాన్నీ ఆప్యాయతనూ నిలుపుకోవడం.",
    "shravana": "శ్రవణ నక్షత్రానికి అధిదేవత జగత్పాలకుడైన విష్ణువు; దీని చిహ్నం చెవి లేదా మూడు పాదముద్రలు. దీని పేరుకు అర్థం “వినడం”; ఈ నక్షత్రంలో చంద్రుడు ఉన్నవారు తరచుగా మంచి శ్రోతలు, ఉత్సాహంగా నేర్చుకునేవారు, జ్ఞానాన్నీ సంప్రదాయాన్నీ కాపాడేవారు. విని నేర్చుకుంటారు, నేర్చుకున్నదాన్ని ఇతరులకు అందిస్తారు. సంప్రదాయం శ్రవణాన్ని అధ్యయనం ద్వారా వచ్చే జ్ఞానంతో, మనుషులను కలపడంతో ముడిపెడుతుంది; అందుకే బోధన, కౌన్సెలింగ్, మీడియా, భాషలు, సంగీతం, ప్రయాణం దీనికి బాగా సరిపోతాయి. దీని వరం శ్రద్ధగా అర్థం చేసుకోవడం, ఉపయోగపడాలనే కోరిక; దీని పాఠం — ఇతరులను విన్నంత శ్రద్ధగా తన అంతరంగ స్వరాన్నీ వినడం.",
    "dhanishta": "ధనిష్ఠ నక్షత్రానికి అధిదేవతలు సమృద్ధికి దేవతలైన అష్ట వసువులు; దీని చిహ్నం డోలు. దీని పేరుకు అర్థం “అత్యంత సంపన్నమైనది”; ఈ నక్షత్రంలో చంద్రుడు ఉన్నవారిలో తరచుగా లయ, శక్తి, సంగీతం, నృత్యం లేదా బృందంగా పనిచేయడంలో ప్రతిభ కనిపిస్తాయి. వారు ఉదారులు, కలుపుగోలుగా ఉంటారు, ఒక బృందాన్ని కలిసికట్టుగా ముందుకు నడిపించగలరు. సంప్రదాయం ధనిష్ఠను ఐశ్వర్యంతో, నాదంతో ముడిపెడుతుంది; అందుకే సంగీతం, ప్రదర్శన కళలు, క్రీడలు, స్థిరాస్తి, ఆర్థిక రంగం, సమాజ సేవ దీనికి బాగా సరిపోతాయి. దీని వరం ఇతరులు అనుసరించే తాళాన్ని వేయగల సామర్థ్యం; దీని పాఠం — వాయించడంతో పాటు వినడం కూడా, ఇతరుల లయకూ చోటివ్వడం.",
    "shatabhisha": "శతభిష నక్షత్రానికి అధిదేవత విశ్వ జలాలకూ సత్యానికీ అధిపతి అయిన వరుణుడు; దీని చిహ్నం శూన్య వృత్తం. దీని పేరుకు అర్థం “వంద మంది వైద్యులు”; ఈ నక్షత్రంలో చంద్రుడు ఉన్నవారు తరచుగా స్వతంత్ర ఆలోచనాపరులు, గోప్యతను ఇష్టపడేవారు, సత్యవంతులు, విషయాలు నిజంగా ఎలా పనిచేస్తాయో అర్థం చేసుకోవాలనే ఆసక్తి కలవారు. ఇతరులు గమనించని క్రమాలను వారు చూడగలరు. సంప్రదాయం శతభిషను వైద్యంతో, దాగి ఉన్న సత్యాన్వేషణతో ముడిపెడుతుంది; అందుకే వైద్యం, పరిశోధన, విజ్ఞానశాస్త్రం, సాంకేతికత, ఖగోళశాస్త్రం, ప్రత్యామ్నాయ వైద్యం దీనికి బాగా సరిపోతాయి. దీని వరం స్పష్టమైన, మౌలికమైన అంతర్దృష్టి; దీని పాఠం — ఆ వృత్తంలోకి ఇతరులనూ రానివ్వడం, తాను అర్థం చేసుకున్నదాన్ని ఆప్యాయంగా పంచుకోవడం.",
    "purva-bhadrapada": "పూర్వాభాద్ర నక్షత్రానికి అధిదేవత శివుని ఏకపాద రూపమైన అజ ఏకపాదుడు; దీని చిహ్నం ఖడ్గాలు లేదా మంచం ముందు కాళ్లు. ఈ నక్షత్రంలో చంద్రుడు ఉన్నవారు తరచుగా ఆదర్శవాదులు, తీవ్రమైన భావావేశం కలవారు, తాము నమ్మిన లక్ష్యానికి పూర్తిగా అంకితమయ్యేవారు. వారు వాక్చాతుర్యం, ఉదారత, లోతైన ఆధ్యాత్మికత కలవారు కాగలరు. సంప్రదాయం పూర్వాభాద్రను పరివర్తనతో, తపస్సు అనే అగ్నితో — ఉన్నత లక్ష్యం కోసం చేసే నిజాయితీ ప్రయత్నంతో — ముడిపెడుతుంది; అందుకే సామాజిక సంస్కరణ, తత్వశాస్త్రం, రచన, పరిశోధన, ఆధ్యాత్మిక జీవితం దీనికి బాగా సరిపోతాయి. దీని వరం ఉత్కట నిబద్ధత; దీని పాఠం — తీవ్రతను ఓర్పుతో, ప్రశాంతతతో సమతుల్యం చేసుకోవడం.",
    "uttara-bhadrapada": "ఉత్తరాభాద్ర నక్షత్రానికి అధిదేవత లోతైన జలాలలోని సర్పమైన అహిర్బుధ్న్యుడు; దీని చిహ్నం మంచం వెనుక కాళ్లు లేదా కవలలు. పూర్వాభాద్ర జ్వలిస్తే, ఉత్తరాభాద్ర ప్రశాంతమైన లోతులో స్థిరపడుతుంది. ఈ నక్షత్రంలో చంద్రుడు ఉన్నవారు తరచుగా జ్ఞానులు, ఓర్పు కలవారు, నిలకడ గలవారు, కరుణామయులు; ఆత్మనిగ్రహం, సలహా ఇచ్చే ప్రతిభ కలవారు. మాట్లాడే ముందు ఆలోచిస్తారు, కష్ట సమయాల్లో స్థిరంగా ఉంటారు. సంప్రదాయం ఈ నక్షత్రాన్ని లోతు, త్యాగం, దయతో ముడిపెడుతుంది; అందుకే కౌన్సెలింగ్, దాతృత్వం, బోధన, పరిశోధన, ఆధ్యాత్మిక సాధన దీనికి బాగా సరిపోతాయి. దీని వరం ప్రశాంతమైన జ్ఞానం; దీని పాఠం — దాన్ని తనలోనే ఉంచుకోకుండా చురుకుగా పంచుకోవడం.",
    "revati": "చివరి నక్షత్రమైన రేవతికి అధిదేవత ప్రయాణికులకు దారి చూపి, దారిలో పశువుల మందలను కాపాడే పోషకుడైన పూషుడు; దీని చిహ్నం చేప. ఈ నక్షత్రంలో చంద్రుడు ఉన్నవారు తరచుగా సౌమ్యులు, దయగలవారు, ఊహాశక్తి కలవారు, బలహీనులను కాపాడేవారు; జంతువులు, కళలు, సంగీతం అంటే వారికి ప్రేమ. ఏ ప్రయాణంలోనైనా మంచి తోడుగా ఉంటారు, ఇతరులు తమ గమ్యాన్ని సురక్షితంగా చేరడానికి సాయపడతారు. సంప్రదాయం రేవతిని సురక్షిత ప్రయాణాలు, సమృద్ధి, పరిపూర్ణతతో ముడిపెడుతుంది; అందుకే సేవా రంగం, కళలు, ప్రయాణం, ఆతిథ్యం, ఆధ్యాత్మిక జీవితం దీనికి బాగా సరిపోతాయి. దీని వరం కరుణ, విశ్వాసం; దీని పాఠం — అందరినీ చూసుకుంటూనే తనను తానూ చూసుకోవడం.",
}.items():
    NAKSHATRA_TRAITS[_k]["te"] = _v

RASHI_TRAITS: dict[str, dict[str, str]] = {
    "mesh": {
        "en": "Mesh (Aries) is the first rashi, a movable fire sign ruled by Mars. People with the Moon in Mesh are often energetic, direct, courageous and quick to act — natural starters who enjoy a challenge and like to lead from the front. They are honest about their feelings and recover quickly from setbacks. Their emotional life is warm and spontaneous, and they bring enthusiasm wherever they go. Work that rewards initiative — sport, the armed forces, engineering, entrepreneurship, surgery — often suits them. Their growth lies in patience and in listening before acting, so that their courage is matched by care for others.",
        "hi": "मेष पहली राशि है — मंगल के स्वामित्व वाली चर अग्नि राशि। मेष राशि (चंद्र राशि) वाले लोग प्रायः ऊर्जावान, स्पष्टवादी, साहसी और तुरंत कदम उठाने वाले होते हैं — स्वाभाविक रूप से शुरुआत करने वाले, जिन्हें चुनौती पसंद है और जो आगे रहकर नेतृत्व करते हैं। वे अपनी भावनाओं के प्रति ईमानदार होते हैं और रुकावटों से जल्दी उबर जाते हैं। उनका भावनात्मक जीवन गर्मजोशी और सहजता से भरा होता है, और वे जहाँ जाते हैं उत्साह ले जाते हैं। पहल को पुरस्कृत करने वाले काम — खेल, सेना, इंजीनियरिंग, उद्यम, शल्य-चिकित्सा — प्रायः उनके अनुकूल होते हैं। उनका विकास धैर्य में और कदम उठाने से पहले सुनने में है, ताकि उनके साहस के साथ दूसरों की परवाह भी हो।",
    },
    "vrishabh": {
        "en": "Vrishabh (Taurus) is a fixed earth sign ruled by Venus, and the Moon is exalted here. People with the Moon in Vrishabh are often calm, patient, loyal and steady, with a love of comfort, good food, music and beautiful things. They build slowly and surely, and what they build tends to last. Emotionally they are dependable and affectionate, preferring security to drama. Finance, agriculture, the arts, food, design and any work that rewards persistence often suit them. Their growth lies in flexibility — welcoming change when it comes, and holding possessions and opinions a little more lightly.",
        "hi": "वृषभ स्थिर पृथ्वी राशि है, जिसके स्वामी शुक्र हैं, और इसमें चंद्रमा उच्च का होता है। वृषभ चंद्र राशि वाले लोग प्रायः शांत, धैर्यवान, निष्ठावान और स्थिर होते हैं, और उन्हें सुख-सुविधा, अच्छा भोजन, संगीत और सुंदर चीज़ें प्रिय होती हैं। वे धीरे-धीरे पर पक्का बनाते हैं, और जो बनाते हैं वह टिकता है। भावनात्मक रूप से वे भरोसेमंद और स्नेही होते हैं, और नाटकीयता से अधिक सुरक्षा पसंद करते हैं। वित्त, कृषि, कला, भोजन, डिज़ाइन और लगन माँगने वाले काम प्रायः उनके अनुकूल होते हैं। उनका विकास लचीलेपन में है — परिवर्तन आने पर उसका स्वागत करना, और वस्तुओं व विचारों को थोड़ा हल्के से थामना।",
    },
    "mithun": {
        "en": "Mithun (Gemini) is a dual air sign ruled by Mercury. People with the Moon in Mithun are often curious, witty, talkative and quick to learn, with many interests and a gift for connecting ideas and people. They enjoy conversation, reading, travel and anything that keeps the mind busy. Emotionally they need variety and a partner who is also a friend they can talk to. Writing, teaching, media, sales, technology and trade often suit them. Their growth lies in depth and focus — choosing a few things and seeing them through — and in giving their own feelings the attention they give to ideas.",
        "hi": "मिथुन बुध के स्वामित्व वाली द्विस्वभाव वायु राशि है। मिथुन चंद्र राशि वाले लोग प्रायः जिज्ञासु, हाज़िरजवाब, बातूनी और जल्दी सीखने वाले होते हैं, जिनकी अनेक रुचियाँ होती हैं और जो विचारों व लोगों को जोड़ने में कुशल होते हैं। उन्हें बातचीत, पढ़ना, यात्रा और मन को व्यस्त रखने वाली हर चीज़ अच्छी लगती है। भावनात्मक रूप से उन्हें विविधता और ऐसा साथी चाहिए जो मित्र भी हो, जिससे वे खुलकर बात कर सकें। लेखन, शिक्षण, मीडिया, बिक्री, तकनीक और व्यापार प्रायः उनके अनुकूल होते हैं। उनका विकास गहराई और एकाग्रता में है — कुछ चीज़ें चुनकर उन्हें पूरा करना — और अपनी भावनाओं को भी उतना ध्यान देना जितना विचारों को।",
    },
    "kark": {
        "en": "Kark (Cancer) is a movable water sign ruled by the Moon itself, so the Moon is at home here. People with the Moon in Kark are often caring, sensitive, intuitive and devoted to family and home. They remember kindness, protect those they love and create warmth wherever they live. Their moods can change like the tides, but their loyalty runs deep. Nursing, teaching, hospitality, food, real estate, counselling and public service often suit them. Their growth lies in trusting their own strength, letting go of old hurts and allowing others to care for them in return.",
        "hi": "कर्क चर जल राशि है, जिसके स्वामी स्वयं चंद्रमा हैं, इसलिए यहाँ चंद्रमा अपने घर में होता है। कर्क चंद्र राशि वाले लोग प्रायः देखभाल करने वाले, संवेदनशील, अंतर्ज्ञानी और परिवार व घर के प्रति समर्पित होते हैं। वे भलाई को याद रखते हैं, अपनों की रक्षा करते हैं और जहाँ रहते हैं वहाँ अपनापन भर देते हैं। उनका मन ज्वार-भाटे की तरह बदल सकता है, पर उनकी निष्ठा गहरी होती है। नर्सिंग, शिक्षण, आतिथ्य, भोजन, संपत्ति, परामर्श और लोक-सेवा प्रायः उनके अनुकूल होते हैं। उनका विकास अपनी शक्ति पर भरोसा करने, पुरानी चोटों को छोड़ने और दूसरों को भी अपनी देखभाल करने देने में है।",
    },
    "simha": {
        "en": "Simha (Leo) is a fixed fire sign ruled by the Sun. People with the Moon in Simha are often generous, dignified, confident and warm-hearted, with a natural sense of leadership and a love of recognition. They are loyal to those who trust them and protective of their family and friends. Emotionally they are proud and open-hearted, and they shine when appreciated. Leadership, administration, politics, the performing arts, teaching and government service often suit them. Their growth lies in humility — letting others share the stage, and finding confidence from within rather than from applause.",
        "hi": "सिंह सूर्य के स्वामित्व वाली स्थिर अग्नि राशि है। सिंह चंद्र राशि वाले लोग प्रायः उदार, गरिमामय, आत्मविश्वासी और खुले दिल के होते हैं, उनमें स्वाभाविक नेतृत्व होता है और उन्हें सम्मान अच्छा लगता है। जो उन पर भरोसा करें, उनके प्रति वे निष्ठावान होते हैं और परिवार व मित्रों की रक्षा करते हैं। भावनात्मक रूप से वे स्वाभिमानी और उदार हृदय होते हैं, और सराहना मिलने पर खिल उठते हैं। नेतृत्व, प्रशासन, राजनीति, प्रदर्शन-कला, शिक्षण और सरकारी सेवा प्रायः उनके अनुकूल होते हैं। उनका विकास विनम्रता में है — दूसरों को भी मंच पर जगह देना, और तालियों से नहीं, भीतर से आत्मविश्वास पाना।",
    },
    "kanya": {
        "en": "Kanya (Virgo) is a dual earth sign ruled by Mercury. People with the Moon in Kanya are often practical, analytical, modest and helpful, with an eye for detail and a wish to make things work properly. They show care through service — fixing, organising and looking after the small things others overlook. Emotionally they can be reserved, but they are deeply dependable. Medicine, accounting, research, editing, nutrition, teaching and any precise craft often suit them. Their growth lies in self-acceptance: being as kind to their own imperfections as they are patient with other people's needs.",
        "hi": "कन्या बुध के स्वामित्व वाली द्विस्वभाव पृथ्वी राशि है। कन्या चंद्र राशि वाले लोग प्रायः व्यावहारिक, विश्लेषणशील, विनम्र और मददगार होते हैं, बारीकियों पर उनकी नज़र रहती है और वे चाहते हैं कि हर काम ठीक से हो। वे सेवा से अपनी परवाह दिखाते हैं — सुधारना, व्यवस्थित करना और उन छोटी बातों का ध्यान रखना जो दूसरे भूल जाते हैं। भावनात्मक रूप से वे संकोची हो सकते हैं, पर बहुत भरोसेमंद होते हैं। चिकित्सा, लेखा, शोध, संपादन, पोषण, शिक्षण और कोई भी सटीक कौशल प्रायः उनके अनुकूल होता है। उनका विकास आत्म-स्वीकृति में है: अपनी कमियों के प्रति भी उतना ही दयालु होना जितना वे दूसरों की ज़रूरतों के प्रति धैर्यवान होते हैं।",
    },
    "tula": {
        "en": "Tula (Libra) is a movable air sign ruled by Venus, symbolised by the scales. People with the Moon in Tula are often gracious, fair-minded, sociable and diplomatic, with a strong sense of beauty and justice. They value harmony in relationships and are good at seeing both sides of a question. Emotionally they need partnership and feel most at ease when things around them are balanced. Law, diplomacy, design, fashion, the arts, counselling and business partnerships often suit them. Their growth lies in decisiveness — trusting their own judgement and accepting that a little disagreement can be healthy.",
        "hi": "तुला शुक्र के स्वामित्व वाली चर वायु राशि है, जिसका प्रतीक तराज़ू है। तुला चंद्र राशि वाले लोग प्रायः शालीन, न्यायप्रिय, मिलनसार और कूटनीतिक होते हैं, जिनमें सौंदर्य और न्याय की गहरी समझ होती है। वे रिश्तों में सामंजस्य को महत्व देते हैं और किसी भी प्रश्न के दोनों पक्ष देख पाते हैं। भावनात्मक रूप से उन्हें साथी की ज़रूरत होती है और जब आसपास संतुलन हो तब वे सबसे सहज रहते हैं। क़ानून, कूटनीति, डिज़ाइन, फ़ैशन, कला, परामर्श और व्यापारिक साझेदारी प्रायः उनके अनुकूल होते हैं। उनका विकास निर्णय-क्षमता में है — अपने विवेक पर भरोसा करना, और यह मानना कि थोड़ी असहमति भी स्वस्थ हो सकती है।",
    },
    "vrishchik": {
        "en": "Vrishchik (Scorpio) is a fixed water sign ruled by Mars. People with the Moon in Vrishchik are often intense, perceptive, determined and deeply loyal, with feelings that run far below the surface. They are not satisfied with appearances and want to understand what is really going on. Once they commit — to a person, a cause or a goal — they rarely let go. Research, investigation, medicine, psychology, finance and crisis work often suit them. Their growth lies in trust and forgiveness: letting others in, and allowing old feelings to transform rather than be held.",
        "hi": "वृश्चिक मंगल के स्वामित्व वाली स्थिर जल राशि है। वृश्चिक चंद्र राशि वाले लोग प्रायः गहन, पारखी, दृढ़निश्चयी और गहरे निष्ठावान होते हैं, जिनकी भावनाएँ सतह से बहुत नीचे बहती हैं। वे दिखावे से संतुष्ट नहीं होते और जानना चाहते हैं कि वास्तव में क्या हो रहा है। एक बार किसी व्यक्ति, उद्देश्य या लक्ष्य से जुड़ जाएँ तो शायद ही छोड़ते हैं। शोध, जाँच-पड़ताल, चिकित्सा, मनोविज्ञान, वित्त और संकट-प्रबंधन प्रायः उनके अनुकूल होते हैं। उनका विकास भरोसे और क्षमा में है: दूसरों को भीतर आने देना, और पुरानी भावनाओं को पकड़े रहने के बजाय बदलने देना।",
    },
    "dhanu": {
        "en": "Dhanu (Sagittarius) is a dual fire sign ruled by Jupiter, symbolised by the archer. People with the Moon in Dhanu are often optimistic, honest, generous and philosophical, with a love of learning, travel and freedom. They look for meaning in life and enjoy sharing what they have learned. Emotionally they are open and cheerful, and they need room to grow. Teaching, law, religion and philosophy, publishing, travel and sport often suit them. Their growth lies in following through — giving the same attention to the details of daily life that they give to big ideas and distant horizons.",
        "hi": "धनु गुरु के स्वामित्व वाली द्विस्वभाव अग्नि राशि है, जिसका प्रतीक धनुर्धर है। धनु चंद्र राशि वाले लोग प्रायः आशावादी, ईमानदार, उदार और दार्शनिक होते हैं, जिन्हें ज्ञान, यात्रा और स्वतंत्रता प्रिय होती है। वे जीवन में अर्थ खोजते हैं और जो सीखा है उसे बाँटना पसंद करते हैं। भावनात्मक रूप से वे खुले और प्रसन्नचित्त होते हैं, और उन्हें बढ़ने के लिए खुली जगह चाहिए। शिक्षण, क़ानून, धर्म और दर्शन, प्रकाशन, यात्रा और खेल प्रायः उनके अनुकूल होते हैं। उनका विकास काम को पूरा करने में है — रोज़मर्रा की बारीकियों को भी उतना ही ध्यान देना जितना बड़े विचारों और दूर के क्षितिज को।",
    },
    "makar": {
        "en": "Makar (Capricorn) is a movable earth sign ruled by Saturn. People with the Moon in Makar are often responsible, disciplined, practical and ambitious in a patient, long-term way. They take duty seriously, work steadily and earn respect over time. Emotionally they can seem reserved, but they show love through reliability and quiet support. Administration, management, engineering, government service, finance and any field that rewards perseverance often suit them. Their growth lies in warmth and rest — allowing themselves joy along the way, and remembering that their worth is not measured only by achievement.",
        "hi": "मकर शनि के स्वामित्व वाली चर पृथ्वी राशि है। मकर चंद्र राशि वाले लोग प्रायः ज़िम्मेदार, अनुशासित, व्यावहारिक और धैर्य के साथ दूरगामी महत्वाकांक्षा वाले होते हैं। वे कर्तव्य को गंभीरता से लेते हैं, लगातार मेहनत करते हैं और समय के साथ सम्मान कमाते हैं। भावनात्मक रूप से वे संकोची लग सकते हैं, पर वे भरोसे और चुपचाप साथ देकर अपना स्नेह दिखाते हैं। प्रशासन, प्रबंधन, इंजीनियरिंग, सरकारी सेवा, वित्त और लगन को पुरस्कृत करने वाला हर क्षेत्र प्रायः उनके अनुकूल होता है। उनका विकास गर्मजोशी और विश्राम में है — रास्ते में आनंद लेने देना, और यह याद रखना कि उनका मूल्य केवल उपलब्धियों से नहीं मापा जाता।",
    },
    "kumbh": {
        "en": "Kumbh (Aquarius) is a fixed air sign ruled by Saturn, symbolised by the water-bearer who pours knowledge out for all. People with the Moon in Kumbh are often independent, humanitarian, inventive and loyal to friends and ideals. They think about the wider community and enjoy new ideas, science and reform. Emotionally they value friendship and freedom, and they show care through principle and action. Science, technology, social work, research, education and community organisations often suit them. Their growth lies in closeness — letting their warmth show to individuals as well as to humanity as a whole.",
        "hi": "कुंभ शनि के स्वामित्व वाली स्थिर वायु राशि है, जिसका प्रतीक वह कुंभधारी है जो सबके लिए ज्ञान उड़ेलता है। कुंभ चंद्र राशि वाले लोग प्रायः स्वतंत्र, मानवतावादी, आविष्कारशील और मित्रों व आदर्शों के प्रति निष्ठावान होते हैं। वे बड़े समाज के बारे में सोचते हैं और उन्हें नए विचार, विज्ञान और सुधार अच्छे लगते हैं। भावनात्मक रूप से वे मित्रता और स्वतंत्रता को महत्व देते हैं, और सिद्धांत व कर्म से अपनी परवाह दिखाते हैं। विज्ञान, तकनीक, समाज-सेवा, शोध, शिक्षा और सामुदायिक संगठन प्रायः उनके अनुकूल होते हैं। उनका विकास निकटता में है — अपनी गर्मजोशी पूरी मानवता के साथ-साथ व्यक्तियों को भी दिखाना।",
    },
    "meen": {
        "en": "Meen (Pisces) is a dual water sign ruled by Jupiter, the last of the twelve rashis. People with the Moon in Meen are often compassionate, imaginative, gentle and spiritually inclined, with a deep sensitivity to the feelings of others. They forgive easily, help without being asked and are moved by music, art and devotion. Emotionally they are open-hearted and intuitive. Healing, counselling, the arts, music, charity, teaching and spiritual work often suit them. Their growth lies in healthy boundaries — caring for others without losing themselves, and turning their rich imagination into practical action.",
        "hi": "मीन गुरु के स्वामित्व वाली द्विस्वभाव जल राशि है, बारह राशियों में अंतिम। मीन चंद्र राशि वाले लोग प्रायः करुणामय, कल्पनाशील, कोमल और आध्यात्मिक झुकाव वाले होते हैं, जो दूसरों की भावनाओं के प्रति गहरे संवेदनशील होते हैं। वे जल्दी क्षमा कर देते हैं, बिना कहे मदद करते हैं और संगीत, कला व भक्ति से भाव-विभोर हो जाते हैं। भावनात्मक रूप से वे खुले दिल और अंतर्ज्ञानी होते हैं। उपचार, परामर्श, कला, संगीत, दान, शिक्षण और आध्यात्मिक कार्य प्रायः उनके अनुकूल होते हैं। उनका विकास स्वस्थ सीमाओं में है — स्वयं को खोए बिना दूसरों की देखभाल करना, और अपनी समृद्ध कल्पना को व्यावहारिक कर्म में बदलना।",
    },
}

# Kannada
for _k, _v in {
    "mesh": "ಮೇಷ ಮೊದಲ ರಾಶಿ — ಕುಜನ ಅಧಿಪತ್ಯದ ಚರ ಅಗ್ನಿತತ್ತ್ವ ರಾಶಿ. ಮೇಷ ರಾಶಿಯಲ್ಲಿ ಚಂದ್ರನಿರುವವರು ಸಾಮಾನ್ಯವಾಗಿ ಉತ್ಸಾಹಿಗಳು, ನೇರ ನುಡಿಯವರು, ಧೈರ್ಯಶಾಲಿಗಳು ಮತ್ತು ತಕ್ಷಣ ಕಾರ್ಯಪ್ರವೃತ್ತರಾಗುವವರು — ಸವಾಲುಗಳನ್ನು ಇಷ್ಟಪಡುವ, ಮುಂದೆ ನಿಂತು ನಾಯಕತ್ವ ವಹಿಸುವ ಸಹಜ ಆರಂಭಕಾರರು. ತಮ್ಮ ಭಾವನೆಗಳ ಬಗ್ಗೆ ಪ್ರಾಮಾಣಿಕರು ಮತ್ತು ಹಿನ್ನಡೆಗಳಿಂದ ಬೇಗನೆ ಚೇತರಿಸಿಕೊಳ್ಳುತ್ತಾರೆ. ಅವರ ಭಾವನಾತ್ಮಕ ಜೀವನ ಆತ್ಮೀಯ ಮತ್ತು ಸಹಜವಾದದ್ದು; ಹೋದಲ್ಲೆಲ್ಲಾ ಉತ್ಸಾಹ ತರುತ್ತಾರೆ. ಉಪಕ್ರಮಕ್ಕೆ ಫಲ ನೀಡುವ ಕೆಲಸಗಳು — ಕ್ರೀಡೆ, ಸಶಸ್ತ್ರ ಪಡೆಗಳು, ಎಂಜಿನಿಯರಿಂಗ್, ಸ್ವಂತ ಉದ್ಯಮ, ಶಸ್ತ್ರಚಿಕಿತ್ಸೆ — ಸಾಮಾನ್ಯವಾಗಿ ಅವರಿಗೆ ಹೊಂದುತ್ತವೆ. ಅವರ ಬೆಳವಣಿಗೆ ತಾಳ್ಮೆಯಲ್ಲಿ ಮತ್ತು ಕಾರ್ಯಕ್ಕಿಳಿಯುವ ಮೊದಲು ಆಲಿಸುವುದರಲ್ಲಿದೆ — ಆಗ ಅವರ ಧೈರ್ಯದ ಜೊತೆಗೆ ಇತರರ ಬಗ್ಗೆ ಕಾಳಜಿಯೂ ಸೇರುತ್ತದೆ.",
    "vrishabh": "ವೃಷಭ ಶುಕ್ರನ ಅಧಿಪತ್ಯದ ಸ್ಥಿರ ಭೂತತ್ತ್ವ ರಾಶಿ; ಚಂದ್ರನು ಇಲ್ಲಿ ಉಚ್ಚನಾಗಿರುತ್ತಾನೆ. ವೃಷಭ ರಾಶಿಯಲ್ಲಿ ಚಂದ್ರನಿರುವವರು ಸಾಮಾನ್ಯವಾಗಿ ಶಾಂತರು, ತಾಳ್ಮೆಯುಳ್ಳವರು, ನಿಷ್ಠಾವಂತರು ಮತ್ತು ಸ್ಥಿರ ಸ್ವಭಾವದವರು; ಸುಖ, ಒಳ್ಳೆಯ ಆಹಾರ, ಸಂಗೀತ ಮತ್ತು ಸುಂದರ ವಸ್ತುಗಳು ಅವರಿಗೆ ಪ್ರಿಯ. ನಿಧಾನವಾಗಿ ಆದರೆ ಖಚಿತವಾಗಿ ಕಟ್ಟುತ್ತಾರೆ, ಮತ್ತು ಅವರು ಕಟ್ಟಿದ್ದು ಬಹುಕಾಲ ಉಳಿಯುತ್ತದೆ. ಭಾವನಾತ್ಮಕವಾಗಿ ಅವರು ನಂಬಿಕಸ್ಥರು ಮತ್ತು ಪ್ರೀತಿಪಾತ್ರರು; ನಾಟಕೀಯತೆಗಿಂತ ಭದ್ರತೆಯನ್ನು ಬಯಸುತ್ತಾರೆ. ಹಣಕಾಸು, ಕೃಷಿ, ಕಲೆಗಳು, ಆಹಾರ, ವಿನ್ಯಾಸ ಮತ್ತು ಛಲಕ್ಕೆ ಫಲ ನೀಡುವ ಯಾವುದೇ ಕೆಲಸ ಸಾಮಾನ್ಯವಾಗಿ ಅವರಿಗೆ ಹೊಂದುತ್ತದೆ. ಅವರ ಬೆಳವಣಿಗೆ ಹೊಂದಿಕೊಳ್ಳುವಿಕೆಯಲ್ಲಿದೆ — ಬದಲಾವಣೆ ಬಂದಾಗ ಅದನ್ನು ಸ್ವಾಗತಿಸುವುದು, ಮತ್ತು ಸ್ವತ್ತುಗಳನ್ನೂ ಅಭಿಪ್ರಾಯಗಳನ್ನೂ ಸ್ವಲ್ಪ ಸಡಿಲವಾಗಿ ಹಿಡಿಯುವುದು.",
    "mithun": "ಮಿಥುನ ಬುಧನ ಅಧಿಪತ್ಯದ ದ್ವಿಸ್ವಭಾವ ವಾಯುತತ್ತ್ವ ರಾಶಿ. ಮಿಥುನ ರಾಶಿಯಲ್ಲಿ ಚಂದ್ರನಿರುವವರು ಸಾಮಾನ್ಯವಾಗಿ ಕುತೂಹಲಿಗಳು, ಹಾಸ್ಯಪ್ರಜ್ಞೆಯುಳ್ಳವರು, ಮಾತುಗಾರರು ಮತ್ತು ಬೇಗನೆ ಕಲಿಯುವವರು; ಅನೇಕ ಆಸಕ್ತಿಗಳೂ ವಿಚಾರಗಳನ್ನೂ ಜನರನ್ನೂ ಬೆಸೆಯುವ ಕೌಶಲವೂ ಅವರಲ್ಲಿರುತ್ತದೆ. ಮಾತುಕತೆ, ಓದು, ಪ್ರಯಾಣ ಮತ್ತು ಮನಸ್ಸನ್ನು ಚುರುಕಾಗಿಡುವ ಯಾವುದೇ ವಿಷಯ ಅವರಿಗೆ ಇಷ್ಟ. ಭಾವನಾತ್ಮಕವಾಗಿ ಅವರಿಗೆ ವೈವಿಧ್ಯ ಬೇಕು, ಮತ್ತು ಮನಬಿಚ್ಚಿ ಮಾತನಾಡಬಹುದಾದ ಸ್ನೇಹಿತನೂ ಆಗಿರುವ ಸಂಗಾತಿ ಬೇಕು. ಬರವಣಿಗೆ, ಬೋಧನೆ, ಮಾಧ್ಯಮ, ಮಾರಾಟ, ತಂತ್ರಜ್ಞಾನ ಮತ್ತು ವ್ಯಾಪಾರ ಸಾಮಾನ್ಯವಾಗಿ ಅವರಿಗೆ ಹೊಂದುತ್ತವೆ. ಅವರ ಬೆಳವಣಿಗೆ ಆಳ ಮತ್ತು ಏಕಾಗ್ರತೆಯಲ್ಲಿದೆ — ಕೆಲವೇ ವಿಷಯಗಳನ್ನು ಆರಿಸಿ ಕೊನೆಯವರೆಗೆ ಮುಗಿಸುವುದು — ಮತ್ತು ವಿಚಾರಗಳಿಗೆ ಕೊಡುವಷ್ಟೇ ಗಮನವನ್ನು ತಮ್ಮ ಭಾವನೆಗಳಿಗೂ ಕೊಡುವುದರಲ್ಲಿದೆ.",
    "kark": "ಕರ್ಕಾಟಕ ಸ್ವತಃ ಚಂದ್ರನ ಅಧಿಪತ್ಯದ ಚರ ಜಲತತ್ತ್ವ ರಾಶಿ; ಆದ್ದರಿಂದ ಚಂದ್ರನು ಇಲ್ಲಿ ಸ್ವಗೃಹದಲ್ಲಿರುತ್ತಾನೆ. ಕರ್ಕಾಟಕ ರಾಶಿಯಲ್ಲಿ ಚಂದ್ರನಿರುವವರು ಸಾಮಾನ್ಯವಾಗಿ ಕಾಳಜಿಯುಳ್ಳವರು, ಸಂವೇದನಾಶೀಲರು, ಅಂತರ್ಬೋಧೆಯುಳ್ಳವರು ಮತ್ತು ಕುಟುಂಬ ಹಾಗೂ ಮನೆಗೆ ಮೀಸಲಾದವರು. ತಮಗೆ ತೋರಿದ ದಯೆಯನ್ನು ನೆನಪಿಟ್ಟುಕೊಳ್ಳುತ್ತಾರೆ, ಪ್ರೀತಿಪಾತ್ರರನ್ನು ಕಾಪಾಡುತ್ತಾರೆ ಮತ್ತು ವಾಸಿಸುವಲ್ಲೆಲ್ಲಾ ಆತ್ಮೀಯತೆ ಮೂಡಿಸುತ್ತಾರೆ. ಅವರ ಮನಸ್ಥಿತಿ ಸಮುದ್ರದ ಉಬ್ಬರವಿಳಿತದಂತೆ ಬದಲಾಗಬಹುದು, ಆದರೆ ಅವರ ನಿಷ್ಠೆ ಆಳವಾದದ್ದು. ಶುಶ್ರೂಷೆ, ಬೋಧನೆ, ಆತಿಥ್ಯ, ಆಹಾರ, ಸ್ಥಿರಾಸ್ತಿ, ಆಪ್ತಸಮಾಲೋಚನೆ ಮತ್ತು ಸಾರ್ವಜನಿಕ ಸೇವೆ ಸಾಮಾನ್ಯವಾಗಿ ಅವರಿಗೆ ಹೊಂದುತ್ತವೆ. ಅವರ ಬೆಳವಣಿಗೆ ತಮ್ಮದೇ ಶಕ್ತಿಯನ್ನು ನಂಬುವುದರಲ್ಲಿ, ಹಳೆಯ ನೋವುಗಳನ್ನು ಬಿಟ್ಟುಬಿಡುವುದರಲ್ಲಿ ಮತ್ತು ಪ್ರತಿಯಾಗಿ ಇತರರೂ ತಮ್ಮನ್ನು ನೋಡಿಕೊಳ್ಳಲು ಅವಕಾಶ ಕೊಡುವುದರಲ್ಲಿದೆ.",
    "simha": "ಸಿಂಹ ಸೂರ್ಯನ ಅಧಿಪತ್ಯದ ಸ್ಥಿರ ಅಗ್ನಿತತ್ತ್ವ ರಾಶಿ. ಸಿಂಹ ರಾಶಿಯಲ್ಲಿ ಚಂದ್ರನಿರುವವರು ಸಾಮಾನ್ಯವಾಗಿ ಉದಾರಿಗಳು, ಘನತೆಯುಳ್ಳವರು, ಆತ್ಮವಿಶ್ವಾಸಿಗಳು ಮತ್ತು ಹೃದಯವಂತರು; ಅವರಲ್ಲಿ ಸಹಜ ನಾಯಕತ್ವ ಮತ್ತು ಮನ್ನಣೆಯ ಬಯಕೆ ಇರುತ್ತದೆ. ತಮ್ಮನ್ನು ನಂಬಿದವರಿಗೆ ನಿಷ್ಠರು ಮತ್ತು ಕುಟುಂಬ ಹಾಗೂ ಸ್ನೇಹಿತರನ್ನು ಕಾಪಾಡುವವರು. ಭಾವನಾತ್ಮಕವಾಗಿ ಅವರು ಸ್ವಾಭಿಮಾನಿಗಳು ಮತ್ತು ತೆರೆದ ಹೃದಯದವರು; ಮೆಚ್ಚುಗೆ ಸಿಕ್ಕಾಗ ಅವರು ಮಿಂಚುತ್ತಾರೆ. ನಾಯಕತ್ವ, ಆಡಳಿತ, ರಾಜಕೀಯ, ರಂಗಕಲೆಗಳು, ಬೋಧನೆ ಮತ್ತು ಸರ್ಕಾರಿ ಸೇವೆ ಸಾಮಾನ್ಯವಾಗಿ ಅವರಿಗೆ ಹೊಂದುತ್ತವೆ. ಅವರ ಬೆಳವಣಿಗೆ ವಿನಯದಲ್ಲಿದೆ — ವೇದಿಕೆಯನ್ನು ಇತರರೊಂದಿಗೆ ಹಂಚಿಕೊಳ್ಳುವುದು, ಮತ್ತು ಚಪ್ಪಾಳೆಯಿಂದಲ್ಲದೆ ಅಂತರಂಗದಿಂದ ಆತ್ಮವಿಶ್ವಾಸ ಪಡೆಯುವುದು.",
    "kanya": "ಕನ್ಯಾ ಬುಧನ ಅಧಿಪತ್ಯದ ದ್ವಿಸ್ವಭಾವ ಭೂತತ್ತ್ವ ರಾಶಿ. ಕನ್ಯಾ ರಾಶಿಯಲ್ಲಿ ಚಂದ್ರನಿರುವವರು ಸಾಮಾನ್ಯವಾಗಿ ವ್ಯವಹಾರಜ್ಞರು, ವಿಶ್ಲೇಷಣಾತ್ಮಕರು, ವಿನಮ್ರರು ಮತ್ತು ಸಹಾಯಕರು; ಸೂಕ್ಷ್ಮ ವಿವರಗಳತ್ತ ಗಮನ ಮತ್ತು ಎಲ್ಲವೂ ಸರಿಯಾಗಿ ನಡೆಯಬೇಕೆಂಬ ಬಯಕೆ ಅವರಲ್ಲಿರುತ್ತದೆ. ಸೇವೆಯ ಮೂಲಕ ಕಾಳಜಿ ತೋರುತ್ತಾರೆ — ಸರಿಪಡಿಸುವುದು, ವ್ಯವಸ್ಥೆಗೊಳಿಸುವುದು ಮತ್ತು ಇತರರು ಕಡೆಗಣಿಸುವ ಸಣ್ಣ ವಿಷಯಗಳನ್ನು ನೋಡಿಕೊಳ್ಳುವುದು. ಭಾವನಾತ್ಮಕವಾಗಿ ಅವರು ಸಂಕೋಚ ಸ್ವಭಾವದವರಾಗಿರಬಹುದು, ಆದರೆ ಆಳವಾಗಿ ನಂಬಿಕಸ್ಥರು. ವೈದ್ಯಕೀಯ, ಲೆಕ್ಕಪತ್ರ, ಸಂಶೋಧನೆ, ಸಂಪಾದನೆ, ಪೋಷಣಾ ವಿಜ್ಞಾನ, ಬೋಧನೆ ಮತ್ತು ಯಾವುದೇ ನಿಖರ ಕೌಶಲ ಸಾಮಾನ್ಯವಾಗಿ ಅವರಿಗೆ ಹೊಂದುತ್ತವೆ. ಅವರ ಬೆಳವಣಿಗೆ ಆತ್ಮಸ್ವೀಕಾರದಲ್ಲಿದೆ: ಇತರರ ಅಗತ್ಯಗಳ ಬಗ್ಗೆ ಎಷ್ಟು ತಾಳ್ಮೆ ತೋರುತ್ತಾರೋ ಅಷ್ಟೇ ದಯೆಯನ್ನು ತಮ್ಮ ಅಪೂರ್ಣತೆಗಳ ಬಗ್ಗೆಯೂ ತೋರುವುದು.",
    "tula": "ತುಲಾ ಶುಕ್ರನ ಅಧಿಪತ್ಯದ ಚರ ವಾಯುತತ್ತ್ವ ರಾಶಿ; ಇದರ ಸಂಕೇತ ತಕ್ಕಡಿ. ತುಲಾ ರಾಶಿಯಲ್ಲಿ ಚಂದ್ರನಿರುವವರು ಸಾಮಾನ್ಯವಾಗಿ ಸೌಜನ್ಯಶೀಲರು, ನ್ಯಾಯಪರರು, ಬೆರೆಯುವ ಸ್ವಭಾವದವರು ಮತ್ತು ಚಾಣಾಕ್ಷರು; ಸೌಂದರ್ಯ ಮತ್ತು ನ್ಯಾಯದ ಬಗ್ಗೆ ಬಲವಾದ ಪ್ರಜ್ಞೆ ಅವರಲ್ಲಿರುತ್ತದೆ. ಸಂಬಂಧಗಳಲ್ಲಿ ಸಾಮರಸ್ಯಕ್ಕೆ ಬೆಲೆ ಕೊಡುತ್ತಾರೆ ಮತ್ತು ಒಂದು ಪ್ರಶ್ನೆಯ ಎರಡೂ ಬದಿಗಳನ್ನು ನೋಡುವುದರಲ್ಲಿ ನಿಪುಣರು. ಭಾವನಾತ್ಮಕವಾಗಿ ಅವರಿಗೆ ಸಹಭಾಗಿತ್ವ ಬೇಕು; ಸುತ್ತಲಿನ ವಿಷಯಗಳು ಸಮತೋಲನದಲ್ಲಿದ್ದಾಗ ಅವರು ಅತ್ಯಂತ ನಿರಾಳರಾಗಿರುತ್ತಾರೆ. ಕಾನೂನು, ರಾಜತಾಂತ್ರಿಕತೆ, ವಿನ್ಯಾಸ, ಫ್ಯಾಷನ್, ಕಲೆಗಳು, ಆಪ್ತಸಮಾಲೋಚನೆ ಮತ್ತು ವ್ಯಾಪಾರ ಪಾಲುದಾರಿಕೆಗಳು ಸಾಮಾನ್ಯವಾಗಿ ಅವರಿಗೆ ಹೊಂದುತ್ತವೆ. ಅವರ ಬೆಳವಣಿಗೆ ನಿರ್ಣಾಯಕತೆಯಲ್ಲಿದೆ — ತಮ್ಮದೇ ವಿವೇಚನೆಯನ್ನು ನಂಬುವುದು, ಮತ್ತು ಸ್ವಲ್ಪ ಭಿನ್ನಾಭಿಪ್ರಾಯವೂ ಆರೋಗ್ಯಕರವಾಗಬಹುದು ಎಂದು ಒಪ್ಪಿಕೊಳ್ಳುವುದು.",
    "vrishchik": "ವೃಶ್ಚಿಕ ಕುಜನ ಅಧಿಪತ್ಯದ ಸ್ಥಿರ ಜಲತತ್ತ್ವ ರಾಶಿ. ವೃಶ್ಚಿಕ ರಾಶಿಯಲ್ಲಿ ಚಂದ್ರನಿರುವವರು ಸಾಮಾನ್ಯವಾಗಿ ತೀವ್ರ ಸ್ವಭಾವದವರು, ಸೂಕ್ಷ್ಮಗ್ರಾಹಿಗಳು, ದೃಢನಿಶ್ಚಯವುಳ್ಳವರು ಮತ್ತು ಆಳವಾಗಿ ನಿಷ್ಠರು; ಅವರ ಭಾವನೆಗಳು ಮೇಲ್ಮೈಯಿಂದ ಬಹಳ ಕೆಳಗೆ ಹರಿಯುತ್ತವೆ. ಹೊರನೋಟದಿಂದ ಅವರು ತೃಪ್ತರಾಗುವುದಿಲ್ಲ, ನಿಜವಾಗಿ ಏನು ನಡೆಯುತ್ತಿದೆ ಎಂದು ಅರಿಯಲು ಬಯಸುತ್ತಾರೆ. ಒಮ್ಮೆ ಒಬ್ಬ ವ್ಯಕ್ತಿಗೆ, ಧ್ಯೇಯಕ್ಕೆ ಅಥವಾ ಗುರಿಗೆ ಬದ್ಧರಾದರೆ, ಅಪರೂಪವಾಗಿ ಕೈಬಿಡುತ್ತಾರೆ. ಸಂಶೋಧನೆ, ತನಿಖೆ, ವೈದ್ಯಕೀಯ, ಮನೋವಿಜ್ಞಾನ, ಹಣಕಾಸು ಮತ್ತು ಸಂಕಷ್ಟ ನಿರ್ವಹಣೆಯ ಕೆಲಸ ಸಾಮಾನ್ಯವಾಗಿ ಅವರಿಗೆ ಹೊಂದುತ್ತವೆ. ಅವರ ಬೆಳವಣಿಗೆ ನಂಬಿಕೆ ಮತ್ತು ಕ್ಷಮೆಯಲ್ಲಿದೆ: ಇತರರನ್ನು ತಮ್ಮ ಮನಸ್ಸಿನೊಳಗೆ ಬರಗೊಡುವುದು, ಮತ್ತು ಹಳೆಯ ಭಾವನೆಗಳನ್ನು ಹಿಡಿದಿಟ್ಟುಕೊಳ್ಳುವ ಬದಲು ಅವು ರೂಪಾಂತರಗೊಳ್ಳಲು ಬಿಡುವುದು.",
    "dhanu": "ಧನು ಗುರುವಿನ ಅಧಿಪತ್ಯದ ದ್ವಿಸ್ವಭಾವ ಅಗ್ನಿತತ್ತ್ವ ರಾಶಿ; ಇದರ ಸಂಕೇತ ಬಿಲ್ಲುಗಾರ. ಧನು ರಾಶಿಯಲ್ಲಿ ಚಂದ್ರನಿರುವವರು ಸಾಮಾನ್ಯವಾಗಿ ಆಶಾವಾದಿಗಳು, ಪ್ರಾಮಾಣಿಕರು, ಉದಾರಿಗಳು ಮತ್ತು ತಾತ್ತ್ವಿಕ ಮನೋಭಾವದವರು; ಕಲಿಕೆ, ಪ್ರಯಾಣ ಮತ್ತು ಸ್ವಾತಂತ್ರ್ಯ ಅವರಿಗೆ ಪ್ರಿಯ. ಜೀವನದಲ್ಲಿ ಅರ್ಥವನ್ನು ಹುಡುಕುತ್ತಾರೆ ಮತ್ತು ಕಲಿತದ್ದನ್ನು ಹಂಚಿಕೊಳ್ಳುವುದರಲ್ಲಿ ಆನಂದಿಸುತ್ತಾರೆ. ಭಾವನಾತ್ಮಕವಾಗಿ ಅವರು ಮುಕ್ತರು ಮತ್ತು ಹರ್ಷಚಿತ್ತರು; ಬೆಳೆಯಲು ಅವರಿಗೆ ಅವಕಾಶ ಬೇಕು. ಬೋಧನೆ, ಕಾನೂನು, ಧರ್ಮ ಮತ್ತು ತತ್ತ್ವಶಾಸ್ತ್ರ, ಪ್ರಕಾಶನ, ಪ್ರಯಾಣ ಮತ್ತು ಕ್ರೀಡೆ ಸಾಮಾನ್ಯವಾಗಿ ಅವರಿಗೆ ಹೊಂದುತ್ತವೆ. ಅವರ ಬೆಳವಣಿಗೆ ಕೈಗೊಂಡದ್ದನ್ನು ಪೂರ್ಣಗೊಳಿಸುವುದರಲ್ಲಿದೆ — ದೊಡ್ಡ ಆಲೋಚನೆಗಳಿಗೂ ದೂರದ ದಿಗಂತಗಳಿಗೂ ಕೊಡುವಷ್ಟೇ ಗಮನವನ್ನು ದೈನಂದಿನ ಜೀವನದ ವಿವರಗಳಿಗೂ ಕೊಡುವುದು.",
    "makar": "ಮಕರ ಶನಿಯ ಅಧಿಪತ್ಯದ ಚರ ಭೂತತ್ತ್ವ ರಾಶಿ. ಮಕರ ರಾಶಿಯಲ್ಲಿ ಚಂದ್ರನಿರುವವರು ಸಾಮಾನ್ಯವಾಗಿ ಜವಾಬ್ದಾರಿಯುತರು, ಶಿಸ್ತುಬದ್ಧರು, ವ್ಯವಹಾರಜ್ಞರು ಮತ್ತು ತಾಳ್ಮೆಯ, ದೀರ್ಘಾವಧಿಯ ರೀತಿಯಲ್ಲಿ ಮಹತ್ವಾಕಾಂಕ್ಷಿಗಳು. ಕರ್ತವ್ಯವನ್ನು ಗಂಭೀರವಾಗಿ ಪರಿಗಣಿಸುತ್ತಾರೆ, ಸ್ಥಿರವಾಗಿ ದುಡಿಯುತ್ತಾರೆ ಮತ್ತು ಕಾಲಕ್ರಮೇಣ ಗೌರವ ಗಳಿಸುತ್ತಾರೆ. ಭಾವನಾತ್ಮಕವಾಗಿ ಅವರು ಸಂಕೋಚ ಸ್ವಭಾವದವರಂತೆ ಕಾಣಬಹುದು, ಆದರೆ ವಿಶ್ವಾಸಾರ್ಹತೆ ಮತ್ತು ಮೌನ ಬೆಂಬಲದ ಮೂಲಕ ಪ್ರೀತಿ ತೋರುತ್ತಾರೆ. ಆಡಳಿತ, ನಿರ್ವಹಣೆ, ಎಂಜಿನಿಯರಿಂಗ್, ಸರ್ಕಾರಿ ಸೇವೆ, ಹಣಕಾಸು ಮತ್ತು ಪರಿಶ್ರಮಕ್ಕೆ ಫಲ ನೀಡುವ ಯಾವುದೇ ಕ್ಷೇತ್ರ ಸಾಮಾನ್ಯವಾಗಿ ಅವರಿಗೆ ಹೊಂದುತ್ತದೆ. ಅವರ ಬೆಳವಣಿಗೆ ಆತ್ಮೀಯತೆ ಮತ್ತು ವಿಶ್ರಾಂತಿಯಲ್ಲಿದೆ — ದಾರಿಯುದ್ದಕ್ಕೂ ಸಂತೋಷಕ್ಕೆ ಅವಕಾಶ ಕೊಡುವುದು, ಮತ್ತು ತಮ್ಮ ಮೌಲ್ಯವನ್ನು ಕೇವಲ ಸಾಧನೆಯಿಂದ ಅಳೆಯಲಾಗುವುದಿಲ್ಲ ಎಂದು ನೆನಪಿಡುವುದು.",
    "kumbh": "ಕುಂಭ ಶನಿಯ ಅಧಿಪತ್ಯದ ಸ್ಥಿರ ವಾಯುತತ್ತ್ವ ರಾಶಿ; ಇದರ ಸಂಕೇತ ಎಲ್ಲರಿಗಾಗಿ ಜ್ಞಾನವನ್ನು ಸುರಿಯುವ ಕುಂಭಧಾರಿ. ಕುಂಭ ರಾಶಿಯಲ್ಲಿ ಚಂದ್ರನಿರುವವರು ಸಾಮಾನ್ಯವಾಗಿ ಸ್ವತಂತ್ರರು, ಮಾನವೀಯರು, ಹೊಸತನದವರು ಮತ್ತು ಸ್ನೇಹಿತರಿಗೂ ಆದರ್ಶಗಳಿಗೂ ನಿಷ್ಠರು. ವಿಶಾಲ ಸಮುದಾಯದ ಬಗ್ಗೆ ಯೋಚಿಸುತ್ತಾರೆ ಮತ್ತು ಹೊಸ ಆಲೋಚನೆಗಳು, ವಿಜ್ಞಾನ ಮತ್ತು ಸುಧಾರಣೆ ಅವರಿಗೆ ಇಷ್ಟ. ಭಾವನಾತ್ಮಕವಾಗಿ ಅವರು ಸ್ನೇಹ ಮತ್ತು ಸ್ವಾತಂತ್ರ್ಯಕ್ಕೆ ಬೆಲೆ ಕೊಡುತ್ತಾರೆ, ಮತ್ತು ತತ್ತ್ವ ಹಾಗೂ ಕಾರ್ಯದ ಮೂಲಕ ಕಾಳಜಿ ತೋರುತ್ತಾರೆ. ವಿಜ್ಞಾನ, ತಂತ್ರಜ್ಞಾನ, ಸಮಾಜಕಾರ್ಯ, ಸಂಶೋಧನೆ, ಶಿಕ್ಷಣ ಮತ್ತು ಸಮುದಾಯ ಸಂಘಟನೆಗಳು ಸಾಮಾನ್ಯವಾಗಿ ಅವರಿಗೆ ಹೊಂದುತ್ತವೆ. ಅವರ ಬೆಳವಣಿಗೆ ಆಪ್ತತೆಯಲ್ಲಿದೆ — ಇಡೀ ಮಾನವಕುಲದಂತೆಯೇ ವ್ಯಕ್ತಿಗಳಿಗೂ ತಮ್ಮ ಆತ್ಮೀಯತೆಯನ್ನು ತೋರುವುದು.",
    "meen": "ಮೀನ ಗುರುವಿನ ಅಧಿಪತ್ಯದ ದ್ವಿಸ್ವಭಾವ ಜಲತತ್ತ್ವ ರಾಶಿ, ಹನ್ನೆರಡು ರಾಶಿಗಳಲ್ಲಿ ಕೊನೆಯದು. ಮೀನ ರಾಶಿಯಲ್ಲಿ ಚಂದ್ರನಿರುವವರು ಸಾಮಾನ್ಯವಾಗಿ ಕರುಣಾಮಯಿಗಳು, ಕಲ್ಪನಾಶೀಲರು, ಸೌಮ್ಯರು ಮತ್ತು ಆಧ್ಯಾತ್ಮಿಕ ಒಲವುಳ್ಳವರು; ಇತರರ ಭಾವನೆಗಳ ಬಗ್ಗೆ ಆಳವಾದ ಸಂವೇದನೆ ಅವರಲ್ಲಿರುತ್ತದೆ. ಸುಲಭವಾಗಿ ಕ್ಷಮಿಸುತ್ತಾರೆ, ಕೇಳದೆಯೇ ಸಹಾಯ ಮಾಡುತ್ತಾರೆ, ಮತ್ತು ಸಂಗೀತ, ಕಲೆ ಹಾಗೂ ಭಕ್ತಿಯಿಂದ ಭಾವುಕರಾಗುತ್ತಾರೆ. ಭಾವನಾತ್ಮಕವಾಗಿ ಅವರು ತೆರೆದ ಹೃದಯದವರು ಮತ್ತು ಅಂತರ್ಬೋಧೆಯುಳ್ಳವರು. ಚಿಕಿತ್ಸೆ, ಆಪ್ತಸಮಾಲೋಚನೆ, ಕಲೆಗಳು, ಸಂಗೀತ, ದಾನಧರ್ಮ, ಬೋಧನೆ ಮತ್ತು ಆಧ್ಯಾತ್ಮಿಕ ಕಾರ್ಯ ಸಾಮಾನ್ಯವಾಗಿ ಅವರಿಗೆ ಹೊಂದುತ್ತವೆ. ಅವರ ಬೆಳವಣಿಗೆ ಆರೋಗ್ಯಕರ ಮಿತಿಗಳಲ್ಲಿದೆ — ತಮ್ಮನ್ನು ಕಳೆದುಕೊಳ್ಳದೆ ಇತರರನ್ನು ನೋಡಿಕೊಳ್ಳುವುದು, ಮತ್ತು ತಮ್ಮ ಸಮೃದ್ಧ ಕಲ್ಪನೆಯನ್ನು ಪ್ರಾಯೋಗಿಕ ಕಾರ್ಯವಾಗಿ ಪರಿವರ್ತಿಸುವುದು.",
}.items():
    RASHI_TRAITS[_k]["kn"] = _v

# Telugu
for _k, _v in {
    "mesh": "మేషం మొదటి రాశి — కుజుడు అధిపతిగా ఉన్న చర అగ్ని తత్వ రాశి. మేష రాశిలో చంద్రుడు ఉన్నవారు తరచుగా శక్తివంతులు, సూటిగా ఉండేవారు, ధైర్యవంతులు, వేగంగా కార్యరంగంలోకి దిగేవారు — సవాళ్లను ఆస్వాదిస్తూ ముందుండి నడిపించడానికి ఇష్టపడే సహజమైన ఆరంభకులు. తమ భావాల విషయంలో నిజాయితీగా ఉంటారు, ఎదురుదెబ్బల నుంచి త్వరగా కోలుకుంటారు. వారి భావోద్వేగ జీవితం ఆప్యాయంగా, సహజంగా ఉంటుంది; వెళ్లిన ప్రతిచోటికీ ఉత్సాహాన్ని తీసుకువెళ్తారు. చొరవకు ఫలితమిచ్చే పనులు — క్రీడలు, సాయుధ దళాలు, ఇంజినీరింగ్, సొంత వ్యాపారం, శస్త్రచికిత్స — తరచుగా వారికి సరిపోతాయి. ఓర్పులో, పనిచేసే ముందు వినడంలో వారి ఎదుగుదల ఉంది; అప్పుడు వారి ధైర్యానికి ఇతరుల పట్ల శ్రద్ధ కూడా తోడవుతుంది.",
    "vrishabh": "వృషభం శుక్రుడు అధిపతిగా ఉన్న స్థిర భూ తత్వ రాశి; చంద్రుడు ఇక్కడ ఉచ్చ స్థితిలో ఉంటాడు. వృషభ రాశిలో చంద్రుడు ఉన్నవారు తరచుగా ప్రశాంతులు, ఓర్పు కలవారు, విశ్వాసపాత్రులు, నిలకడ గలవారు; సౌకర్యం, మంచి ఆహారం, సంగీతం, అందమైన వస్తువులు అంటే వారికి ఇష్టం. వారు నెమ్మదిగా కానీ ఖచ్చితంగా నిర్మిస్తారు, వారు నిర్మించినది సాధారణంగా నిలిచి ఉంటుంది. భావోద్వేగపరంగా వారు నమ్మదగినవారు, ఆప్యాయత కలవారు; నాటకీయత కంటే భద్రతను ఇష్టపడతారు. ఆర్థిక రంగం, వ్యవసాయం, కళలు, ఆహారం, డిజైన్, పట్టుదలకు ఫలితమిచ్చే ఏ పనైనా తరచుగా వారికి సరిపోతుంది. సరళత్వంలో వారి ఎదుగుదల ఉంది — మార్పు వచ్చినప్పుడు దాన్ని స్వాగతించడం, వస్తువులనూ అభిప్రాయాలనూ కొంచెం సడలించి పట్టుకోవడం.",
    "mithun": "మిథునం బుధుడు అధిపతిగా ఉన్న ద్విస్వభావ వాయు తత్వ రాశి. మిథున రాశిలో చంద్రుడు ఉన్నవారు తరచుగా కుతూహలం, చమత్కారం, మాటకారితనం కలవారు, త్వరగా నేర్చుకునేవారు; వారికి ఎన్నో ఆసక్తులు ఉంటాయి, ఆలోచనలనూ మనుషులనూ కలిపే ప్రతిభ ఉంటుంది. సంభాషణ, చదువు, ప్రయాణం, మనసును చురుకుగా ఉంచే ఏదైనా వారికి ఆనందం. భావోద్వేగపరంగా వారికి వైవిధ్యం కావాలి, మనసు విప్పి మాట్లాడగల స్నేహితుడిలాంటి భాగస్వామి కావాలి. రచన, బోధన, మీడియా, అమ్మకాలు, సాంకేతికత, వ్యాపారం తరచుగా వారికి సరిపోతాయి. లోతులో, ఏకాగ్రతలో వారి ఎదుగుదల ఉంది — కొన్ని పనులను ఎంచుకుని వాటిని పూర్తి చేయడం — అలాగే ఆలోచనలకు ఇచ్చే శ్రద్ధను తమ భావాలకూ ఇవ్వడం.",
    "kark": "కర్కాటకం చంద్రుడే అధిపతిగా ఉన్న చర జల తత్వ రాశి, కనుక ఇక్కడ చంద్రుడు స్వక్షేత్రంలో ఉంటాడు. కర్కాటక రాశిలో చంద్రుడు ఉన్నవారు తరచుగా శ్రద్ధ చూపేవారు, సున్నితమైనవారు, అంతర్బుద్ధి కలవారు, కుటుంబానికీ ఇంటికీ అంకితమైనవారు. పొందిన మేలును గుర్తుంచుకుంటారు, ప్రేమించినవారిని కాపాడతారు, ఎక్కడ నివసించినా ఆప్యాయతను సృష్టిస్తారు. వారి మనోభావాలు అలల్లా మారవచ్చు, కానీ వారి విశ్వాసం లోతైనది. నర్సింగ్, బోధన, ఆతిథ్యం, ఆహారం, స్థిరాస్తి, కౌన్సెలింగ్, ప్రజా సేవ తరచుగా వారికి సరిపోతాయి. తమ సొంత బలాన్ని నమ్మడంలో, పాత గాయాలను వదిలిపెట్టడంలో, ప్రతిగా ఇతరులు తమను చూసుకోనివ్వడంలో వారి ఎదుగుదల ఉంది.",
    "simha": "సింహం సూర్యుడు అధిపతిగా ఉన్న స్థిర అగ్ని తత్వ రాశి. సింహ రాశిలో చంద్రుడు ఉన్నవారు తరచుగా ఉదారులు, హుందాతనం, ఆత్మవిశ్వాసం, ఆప్యాయత నిండిన హృదయం కలవారు; సహజమైన నాయకత్వ భావం, గుర్తింపు పట్ల ఇష్టం ఉంటాయి. తమను నమ్మినవారికి విశ్వాసపాత్రులు, కుటుంబాన్నీ స్నేహితులనూ కాపాడతారు. భావోద్వేగపరంగా వారు ఆత్మగౌరవం కలవారు, మనసు విప్పి ఉండేవారు; ప్రశంస లభించినప్పుడు వెలిగిపోతారు. నాయకత్వం, పరిపాలన, రాజకీయాలు, ప్రదర్శన కళలు, బోధన, ప్రభుత్వ సేవ తరచుగా వారికి సరిపోతాయి. వినయంలో వారి ఎదుగుదల ఉంది — వేదికను ఇతరులతో పంచుకోవడం, చప్పట్ల నుంచి కాక తమలోంచే ఆత్మవిశ్వాసాన్ని పొందడం.",
    "kanya": "కన్య బుధుడు అధిపతిగా ఉన్న ద్విస్వభావ భూ తత్వ రాశి. కన్యా రాశిలో చంద్రుడు ఉన్నవారు తరచుగా ఆచరణాత్మకులు, విశ్లేషణ నైపుణ్యం కలవారు, నిరాడంబరులు, సాయపడేవారు; వివరాలపై దృష్టి, పనులు సరిగ్గా జరగాలనే కోరిక ఉంటాయి. సేవ ద్వారా తమ శ్రద్ధను చూపుతారు — బాగుచేయడం, క్రమపరచడం, ఇతరులు పట్టించుకోని చిన్న విషయాలను చూసుకోవడం. భావోద్వేగపరంగా వారు కాస్త మితభాషులుగా ఉండవచ్చు, కానీ ఎంతో నమ్మదగినవారు. వైద్యం, అకౌంటింగ్, పరిశోధన, సంపాదకత్వం, పోషకాహార రంగం, బోధన, ఏ సూక్ష్మమైన నైపుణ్యమైనా తరచుగా వారికి సరిపోతుంది. తమను తాము అంగీకరించడంలో వారి ఎదుగుదల ఉంది: ఇతరుల అవసరాల పట్ల చూపే ఓర్పుతోనే తమ లోపాల పట్లా దయగా ఉండటం.",
    "tula": "తుల శుక్రుడు అధిపతిగా ఉన్న చర వాయు తత్వ రాశి; దీని చిహ్నం త్రాసు. తులా రాశిలో చంద్రుడు ఉన్నవారు తరచుగా హుందాగా, న్యాయబుద్ధితో, కలుపుగోలుగా, దౌత్యనైపుణ్యంతో ఉంటారు; అందం పట్లా న్యాయం పట్లా బలమైన అభిరుచి ఉంటుంది. సంబంధాలలో సామరస్యానికి విలువ ఇస్తారు, ఏ ప్రశ్నకైనా రెండు వైపులా చూడగలరు. భావోద్వేగపరంగా వారికి భాగస్వామ్యం అవసరం, చుట్టూ అంతా సమతుల్యంగా ఉన్నప్పుడు వారు అత్యంత ప్రశాంతంగా ఉంటారు. న్యాయ రంగం, దౌత్యం, డిజైన్, ఫ్యాషన్, కళలు, కౌన్సెలింగ్, వ్యాపార భాగస్వామ్యాలు తరచుగా వారికి సరిపోతాయి. నిర్ణయాత్మకతలో వారి ఎదుగుదల ఉంది — తమ సొంత విచక్షణను నమ్మడం, కొంత భిన్నాభిప్రాయం కూడా ఆరోగ్యకరమేనని అంగీకరించడం.",
    "vrishchik": "వృశ్చికం కుజుడు అధిపతిగా ఉన్న స్థిర జల తత్వ రాశి. వృశ్చిక రాశిలో చంద్రుడు ఉన్నవారు తరచుగా తీవ్రమైన భావాలు, సూక్ష్మదృష్టి, పట్టుదల, లోతైన విశ్వాసం కలవారు; వారి భావాలు ఉపరితలానికి ఎంతో లోతున ప్రవహిస్తాయి. పైపై రూపాలతో తృప్తి పడరు, అసలు ఏం జరుగుతోందో అర్థం చేసుకోవాలనుకుంటారు. ఒకసారి కట్టుబడితే — ఒక వ్యక్తికి, ఒక ఆశయానికి లేదా ఒక లక్ష్యానికి — అరుదుగా వదిలిపెడతారు. పరిశోధన, దర్యాప్తు, వైద్యం, మనస్తత్వశాస్త్రం, ఆర్థిక రంగం, సంక్షోభ సమయాల్లో చేసే పనులు తరచుగా వారికి సరిపోతాయి. నమ్మకంలో, క్షమలో వారి ఎదుగుదల ఉంది: ఇతరులను దగ్గరకు రానివ్వడం, పాత భావాలను పట్టి ఉంచకుండా పరివర్తన చెందనివ్వడం.",
    "dhanu": "ధనుస్సు గురువు అధిపతిగా ఉన్న ద్విస్వభావ అగ్ని తత్వ రాశి; దీని చిహ్నం విలుకాడు. ధనుస్సు రాశిలో చంద్రుడు ఉన్నవారు తరచుగా ఆశావాదులు, నిజాయితీపరులు, ఉదారులు, తాత్విక దృష్టి కలవారు; జ్ఞానం, ప్రయాణం, స్వేచ్ఛ అంటే వారికి ప్రేమ. జీవితంలో అర్థాన్ని వెతుకుతారు, నేర్చుకున్నదాన్ని పంచుకోవడం ఆనందిస్తారు. భావోద్వేగపరంగా వారు మనసు విప్పి, సంతోషంగా ఉంటారు; ఎదగడానికి వారికి చోటు కావాలి. బోధన, న్యాయం, ధర్మం మరియు తత్వశాస్త్రం, ప్రచురణ, ప్రయాణం, క్రీడలు తరచుగా వారికి సరిపోతాయి. పనులను చివరి వరకు పూర్తి చేయడంలో వారి ఎదుగుదల ఉంది — పెద్ద ఆలోచనలకూ సుదూర క్షితిజాలకూ ఇచ్చే శ్రద్ధనే రోజువారీ జీవితంలోని వివరాలకూ ఇవ్వడం.",
    "makar": "మకరం శని అధిపతిగా ఉన్న చర భూ తత్వ రాశి. మకర రాశిలో చంద్రుడు ఉన్నవారు తరచుగా బాధ్యతాయుతులు, క్రమశిక్షణ కలవారు, ఆచరణాత్మకులు; ఓర్పుతో, దీర్ఘకాల దృష్టితో ఆశయాలను సాధించేవారు. కర్తవ్యాన్ని గంభీరంగా తీసుకుంటారు, నిలకడగా శ్రమిస్తారు, కాలక్రమంలో గౌరవాన్ని సంపాదిస్తారు. భావోద్వేగపరంగా వారు మితభాషులుగా కనిపించవచ్చు, కానీ నమ్మకంగా ఉండటం ద్వారా, నిశ్శబ్దంగా అండగా నిలవడం ద్వారా తమ ప్రేమను చూపుతారు. పరిపాలన, నిర్వహణ, ఇంజినీరింగ్, ప్రభుత్వ సేవ, ఆర్థిక రంగం, పట్టుదలకు ఫలితమిచ్చే ఏ రంగమైనా తరచుగా వారికి సరిపోతుంది. ఆప్యాయతలో, విశ్రాంతిలో వారి ఎదుగుదల ఉంది — దారిలో ఆనందాన్ని కూడా అనుభవించడం, తమ విలువ కేవలం విజయాలతోనే కొలవబడదని గుర్తుంచుకోవడం.",
    "kumbh": "కుంభం శని అధిపతిగా ఉన్న స్థిర వాయు తత్వ రాశి; దీని చిహ్నం అందరి కోసం జ్ఞానాన్ని కుమ్మరించే కుంభధారి. కుంభ రాశిలో చంద్రుడు ఉన్నవారు తరచుగా స్వతంత్రులు, మానవతావాదులు, కొత్తవి కనిపెట్టేవారు, స్నేహితులకూ ఆదర్శాలకూ విశ్వాసపాత్రులు. విశాల సమాజం గురించి ఆలోచిస్తారు; కొత్త ఆలోచనలు, విజ్ఞానశాస్త్రం, సంస్కరణలు వారికి ఇష్టం. భావోద్వేగపరంగా స్నేహానికీ స్వేచ్ఛకూ విలువ ఇస్తారు, సిద్ధాంతం ద్వారా, ఆచరణ ద్వారా తమ శ్రద్ధను చూపుతారు. విజ్ఞానశాస్త్రం, సాంకేతికత, సామాజిక సేవ, పరిశోధన, విద్య, సామాజిక సంస్థలు తరచుగా వారికి సరిపోతాయి. సాన్నిహిత్యంలో వారి ఎదుగుదల ఉంది — మొత్తం మానవాళి పట్లే కాక వ్యక్తుల పట్ల కూడా తమ ఆప్యాయతను వ్యక్తపరచడం.",
    "meen": "మీనం గురువు అధిపతిగా ఉన్న ద్విస్వభావ జల తత్వ రాశి, పన్నెండు రాశులలో చివరిది. మీన రాశిలో చంద్రుడు ఉన్నవారు తరచుగా కరుణామయులు, ఊహాశక్తి కలవారు, సౌమ్యులు, ఆధ్యాత్మిక మొగ్గు కలవారు; ఇతరుల భావాల పట్ల లోతైన సున్నితత్వం ఉంటుంది. సులభంగా క్షమిస్తారు, అడగకుండానే సాయం చేస్తారు; సంగీతం, కళ, భక్తి వారి మనసును కదిలిస్తాయి. భావోద్వేగపరంగా వారు విశాల హృదయులు, అంతర్బుద్ధి కలవారు. స్వస్థత సేవ, కౌన్సెలింగ్, కళలు, సంగీతం, దాతృత్వం, బోధన, ఆధ్యాత్మిక కార్యాలు తరచుగా వారికి సరిపోతాయి. ఆరోగ్యకరమైన హద్దులలో వారి ఎదుగుదల ఉంది — తమను తాము కోల్పోకుండా ఇతరులను చూసుకోవడం, తమ గొప్ప ఊహాశక్తిని ఆచరణాత్మక కార్యంగా మార్చడం.",
}.items():
    RASHI_TRAITS[_k]["te"] = _v
