"""City and state names in the regional languages (DIVASTRO-123).

TRANSLATORS: this file is data. seo_cities.city_name / state_name / place read
it, so a /kn/panchang/mysuru page says "ಮೈಸೂರು" in its title, heading,
breadcrumb, JSON-LD and city index instead of "Mysuru". English and Hindi stay
in seo_cities.py (City.name, City.name_hi, STATE_HI) and never come from here.

CITIES[lang][slug] and STATES[lang][English state name]. The spelling is the
one the language's own newspapers and government sites use for the place
(ಬೆಂಗಳೂರು, హైదరాబాద్, சென்னை, തിരുവനന്തപുരം, কলকাতা, ଭୁବନେଶ୍ୱର); a North Indian city is
transliterated the way that language's press writes it. A city missing here
falls back to English. Slugs (URLs) never change.
"""

from __future__ import annotations

# Slug order: as seo_cities.CITIES.
CITIES: dict[str, dict[str, str]] = {
    "kn": {
        "new-delhi": "ನವದೆಹಲಿ", "mumbai": "ಮುಂಬೈ", "kolkata": "ಕೋಲ್ಕತ್ತಾ", "chennai": "ಚೆನ್ನೈ",
        "bengaluru": "ಬೆಂಗಳೂರು", "hyderabad": "ಹೈದರಾಬಾದ್", "ahmedabad": "ಅಹಮದಾಬಾದ್",
        "pune": "ಪುಣೆ", "jaipur": "ಜೈಪುರ", "lucknow": "ಲಖನೌ", "kanpur": "ಕಾನ್ಪುರ",
        "nagpur": "ನಾಗಪುರ", "indore": "ಇಂದೋರ್", "bhopal": "ಭೋಪಾಲ್", "patna": "ಪಟ್ನಾ",
        "varanasi": "ವಾರಾಣಸಿ", "prayagraj": "ಪ್ರಯಾಗರಾಜ್", "surat": "ಸೂರತ್", "vadodara": "ವಡೋದರಾ",
        "chandigarh": "ಚಂಡೀಗಢ", "amritsar": "ಅಮೃತಸರ", "dehradun": "ಡೆಹ್ರಾಡೂನ್",
        "haridwar": "ಹರಿದ್ವಾರ", "noida": "ನೋಯ್ಡಾ", "gurugram": "ಗುರುಗ್ರಾಮ",
        "bhubaneswar": "ಭುವನೇಶ್ವರ", "guwahati": "ಗುವಾಹಟಿ", "ranchi": "ರಾಂಚಿ", "kochi": "ಕೊಚ್ಚಿ",
        "visakhapatnam": "ವಿಶಾಖಪಟ್ಟಣ", "thane": "ಠಾಣೆ", "navi-mumbai": "ನವಿ ಮುಂಬೈ",
        "nashik": "ನಾಸಿಕ್", "chhatrapati-sambhajinagar": "ಛತ್ರಪತಿ ಸಂಭಾಜಿನಗರ",
        "solapur": "ಸೊಲ್ಲಾಪುರ", "kolhapur": "ಕೊಲ್ಹಾಪುರ", "amravati": "ಅಮರಾವತಿ",
        "shirdi": "ಶಿರಡಿ", "rajkot": "ರಾಜಕೋಟ್", "bhavnagar": "ಭಾವನಗರ", "jamnagar": "ಜಾಮನಗರ",
        "gandhinagar": "ಗಾಂಧಿನಗರ", "dwarka": "ದ್ವಾರಕಾ", "somnath": "ಸೋಮನಾಥ",
        "jodhpur": "ಜೋಧಪುರ", "udaipur": "ಉದಯಪುರ", "kota": "ಕೋಟಾ", "ajmer": "ಅಜ್ಮೀರ್",
        "bikaner": "ಬಿಕಾನೇರ್", "agra": "ಆಗ್ರಾ", "ghaziabad": "ಗಾಜಿಯಾಬಾದ್", "meerut": "ಮೀರತ್",
        "bareilly": "ಬರೇಲಿ", "aligarh": "ಅಲಿಗಢ", "moradabad": "ಮೊರಾದಾಬಾದ್",
        "gorakhpur": "ಗೋರಖಪುರ", "saharanpur": "ಸಹಾರನಪುರ", "ayodhya": "ಅಯೋಧ್ಯೆ",
        "mathura": "ಮಥುರಾ", "vrindavan": "ವೃಂದಾವನ", "jhansi": "ಝಾನ್ಸಿ", "faridabad": "ಫರೀದಾಬಾದ್",
        "kurukshetra": "ಕುರುಕ್ಷೇತ್ರ", "ludhiana": "ಲುಧಿಯಾನ", "jalandhar": "ಜಲಂಧರ್",
        "patiala": "ಪಟಿಯಾಲ", "rishikesh": "ಋಷಿಕೇಶ", "shimla": "ಶಿಮ್ಲಾ", "jammu": "ಜಮ್ಮು",
        "srinagar": "ಶ್ರೀನಗರ", "katra": "ಕಟ್ರಾ", "gwalior": "ಗ್ವಾಲಿಯರ್", "jabalpur": "ಜಬಲ್ಪುರ",
        "ujjain": "ಉಜ್ಜಯಿನಿ", "raipur": "ರಾಯಪುರ", "bhilai": "ಭಿಲಾಯಿ", "gaya": "ಗಯಾ",
        "bhagalpur": "ಭಾಗಲ್ಪುರ", "muzaffarpur": "ಮುಜಫ್ಫರಪುರ", "jamshedpur": "ಜಮ್ಶೆಡ್ಪುರ",
        "dhanbad": "ಧನಬಾದ್", "deoghar": "ದೇವಘರ್", "howrah": "ಹೌರಾ", "asansol": "ಅಸನ್ಸೋಲ್",
        "siliguri": "ಸಿಲಿಗುರಿ", "cuttack": "ಕಟಕ್", "puri": "ಪುರಿ", "coimbatore": "ಕೊಯಮತ್ತೂರು",
        "madurai": "ಮಧುರೈ", "tiruchirappalli": "ತಿರುಚಿರಾಪಳ್ಳಿ", "salem": "ಸೇಲಂ",
        "rameswaram": "ರಾಮೇಶ್ವರಂ", "thiruvananthapuram": "ತಿರುವನಂತಪುರಂ",
        "kozhikode": "ಕೋಳಿಕ್ಕೋಡ್", "thrissur": "ತ್ರಿಶೂರ್", "kollam": "ಕೊಲ್ಲಂ", "kannur": "ಕಣ್ಣೂರು",
        "malappuram": "ಮಲಪ್ಪುರಂ", "mysuru": "ಮೈಸೂರು", "mangaluru": "ಮಂಗಳೂರು",
        "hubballi": "ಹುಬ್ಬಳ್ಳಿ", "warangal": "ವರಂಗಲ್", "vijayawada": "ವಿಜಯವಾಡ",
        "tirupati": "ತಿರುಪತಿ", "guntur": "ಗುಂಟೂರು", "panaji": "ಪಣಜಿ", "shillong": "ಶಿಲ್ಲಾಂಗ್",
        "imphal": "ಇಂಫಾಲ್", "agartala": "ಅಗರ್ತಲಾ", "gangtok": "ಗ್ಯಾಂಗ್ಟಾಕ್", "aizawl": "ಐಜಾಲ್",
        "kohima": "ಕೊಹಿಮಾ", "itanagar": "ಇಟಾನಗರ", "puducherry": "ಪುದುಚೇರಿ",
    },
    "te": {
        "new-delhi": "న్యూఢిల్లీ", "mumbai": "ముంబై", "kolkata": "కోల్‌కతా", "chennai": "చెన్నై",
        "bengaluru": "బెంగళూరు", "hyderabad": "హైదరాబాద్", "ahmedabad": "అహ్మదాబాద్",
        "pune": "పుణె", "jaipur": "జైపూర్", "lucknow": "లక్నో", "kanpur": "కాన్పూర్",
        "nagpur": "నాగ్‌పూర్", "indore": "ఇండోర్", "bhopal": "భోపాల్", "patna": "పాట్నా",
        "varanasi": "వారణాసి", "prayagraj": "ప్రయాగ్‌రాజ్", "surat": "సూరత్", "vadodara": "వడోదర",
        "chandigarh": "చండీగఢ్", "amritsar": "అమృత్‌సర్", "dehradun": "డెహ్రాడూన్",
        "haridwar": "హరిద్వార్", "noida": "నోయిడా", "gurugram": "గురుగ్రామ్",
        "bhubaneswar": "భువనేశ్వర్", "guwahati": "గువాహటి", "ranchi": "రాంచీ", "kochi": "కొచ్చి",
        "visakhapatnam": "విశాఖపట్నం", "thane": "ఠాణే", "navi-mumbai": "నవీ ముంబై",
        "nashik": "నాసిక్", "chhatrapati-sambhajinagar": "ఛత్రపతి సంభాజీనగర్",
        "solapur": "షోలాపూర్", "kolhapur": "కొల్హాపూర్", "amravati": "అమరావతి",
        "shirdi": "షిర్డీ", "rajkot": "రాజ్‌కోట్", "bhavnagar": "భావ్‌నగర్",
        "jamnagar": "జామ్‌నగర్", "gandhinagar": "గాంధీనగర్", "dwarka": "ద్వారక",
        "somnath": "సోమనాథ్", "jodhpur": "జోధ్‌పూర్", "udaipur": "ఉదయ్‌పూర్", "kota": "కోటా",
        "ajmer": "అజ్మీర్", "bikaner": "బికనీర్", "agra": "ఆగ్రా", "ghaziabad": "ఘజియాబాద్",
        "meerut": "మీరట్", "bareilly": "బరేలీ", "aligarh": "అలీగఢ్", "moradabad": "మొరాదాబాద్",
        "gorakhpur": "గోరఖ్‌పూర్", "saharanpur": "సహారన్‌పూర్", "ayodhya": "అయోధ్య",
        "mathura": "మథుర", "vrindavan": "బృందావనం", "jhansi": "ఝాన్సీ",
        "faridabad": "ఫరీదాబాద్", "kurukshetra": "కురుక్షేత్ర", "ludhiana": "లూధియానా",
        "jalandhar": "జలంధర్", "patiala": "పటియాలా", "rishikesh": "రిషికేశ్", "shimla": "సిమ్లా",
        "jammu": "జమ్మూ", "srinagar": "శ్రీనగర్", "katra": "కట్రా", "gwalior": "గ్వాలియర్",
        "jabalpur": "జబల్‌పూర్", "ujjain": "ఉజ్జయిని", "raipur": "రాయ్‌పూర్", "bhilai": "భిలాయ్",
        "gaya": "గయ", "bhagalpur": "భాగల్‌పూర్", "muzaffarpur": "ముజఫర్‌పూర్",
        "jamshedpur": "జంషెడ్‌పూర్", "dhanbad": "ధన్‌బాద్", "deoghar": "దేవ్‌ఘర్",
        "howrah": "హౌరా", "asansol": "అసన్‌సోల్", "siliguri": "సిలిగురి", "cuttack": "కటక్",
        "puri": "పూరీ", "coimbatore": "కోయంబత్తూరు", "madurai": "మదురై",
        "tiruchirappalli": "తిరుచిరాపల్లి", "salem": "సేలం", "rameswaram": "రామేశ్వరం",
        "thiruvananthapuram": "తిరువనంతపురం", "kozhikode": "కోజికోడ్", "thrissur": "త్రిశూర్",
        "kollam": "కొల్లం", "kannur": "కన్నూర్", "malappuram": "మలప్పురం", "mysuru": "మైసూరు",
        "mangaluru": "మంగళూరు", "hubballi": "హుబ్బళ్లి", "warangal": "వరంగల్",
        "vijayawada": "విజయవాడ", "tirupati": "తిరుపతి", "guntur": "గుంటూరు", "panaji": "పణజి",
        "shillong": "షిల్లాంగ్", "imphal": "ఇంఫాల్", "agartala": "అగర్తలా",
        "gangtok": "గ్యాంగ్‌టక్", "aizawl": "ఐజ్వాల్", "kohima": "కొహిమా", "itanagar": "ఇటానగర్",
        "puducherry": "పుదుచ్చేరి",
    },
    "ta": {
        "new-delhi": "புது தில்லி", "mumbai": "மும்பை", "kolkata": "கொல்கத்தா",
        "chennai": "சென்னை", "bengaluru": "பெங்களூரு", "hyderabad": "ஹைதராபாத்",
        "ahmedabad": "அகமதாபாத்", "pune": "புனே", "jaipur": "ஜெய்ப்பூர்", "lucknow": "லக்னோ",
        "kanpur": "கான்பூர்", "nagpur": "நாக்பூர்", "indore": "இந்தூர்", "bhopal": "போபால்",
        "patna": "பட்னா", "varanasi": "வாரணாசி", "prayagraj": "பிரயாக்ராஜ்", "surat": "சூரத்",
        "vadodara": "வதோதரா", "chandigarh": "சண்டிகர்", "amritsar": "அமிர்தசரஸ்",
        "dehradun": "டேராடூன்", "haridwar": "ஹரித்வார்", "noida": "நொய்டா",
        "gurugram": "குருகிராம்", "bhubaneswar": "புவனேஸ்வர்", "guwahati": "குவாஹாட்டி",
        "ranchi": "ராஞ்சி", "kochi": "கொச்சி", "visakhapatnam": "விசாகப்பட்டினம்",
        "thane": "தானே", "navi-mumbai": "நவி மும்பை", "nashik": "நாசிக்",
        "chhatrapati-sambhajinagar": "சத்ரபதி சம்பாஜிநகர்", "solapur": "சோலாப்பூர்",
        "kolhapur": "கோலாப்பூர்", "amravati": "அமராவதி", "shirdi": "ஷிர்டி",
        "rajkot": "ராஜ்கோட்", "bhavnagar": "பாவ்நகர்", "jamnagar": "ஜாம்நகர்",
        "gandhinagar": "காந்திநகர்", "dwarka": "துவாரகை", "somnath": "சோம்நாத்",
        "jodhpur": "ஜோத்பூர்", "udaipur": "உதய்பூர்", "kota": "கோட்டா", "ajmer": "அஜ்மீர்",
        "bikaner": "பிகானேர்", "agra": "ஆக்ரா", "ghaziabad": "காசியாபாத்", "meerut": "மீரட்",
        "bareilly": "பரேலி", "aligarh": "அலிகர்", "moradabad": "மொராதாபாத்",
        "gorakhpur": "கோரக்பூர்", "saharanpur": "சகாரன்பூர்", "ayodhya": "அயோத்தி",
        "mathura": "மதுரா", "vrindavan": "பிருந்தாவனம்", "jhansi": "ஜான்சி",
        "faridabad": "பரீதாபாத்", "kurukshetra": "குருக்ஷேத்திரம்", "ludhiana": "லூதியானா",
        "jalandhar": "ஜலந்தர்", "patiala": "பட்டியாலா", "rishikesh": "ரிஷிகேஷ்",
        "shimla": "சிம்லா", "jammu": "ஜம்மு", "srinagar": "ஸ்ரீநகர்", "katra": "கட்ரா",
        "gwalior": "குவாலியர்", "jabalpur": "ஜபல்பூர்", "ujjain": "உஜ்ஜைன்",
        "raipur": "ராய்ப்பூர்", "bhilai": "பிலாய்", "gaya": "கயா", "bhagalpur": "பாகல்பூர்",
        "muzaffarpur": "முசாபர்பூர்", "jamshedpur": "ஜம்ஷெட்பூர்", "dhanbad": "தன்பாத்",
        "deoghar": "தேவ்கர்", "howrah": "ஹவுரா", "asansol": "அசன்சோல்", "siliguri": "சிலிகுரி",
        "cuttack": "கட்டக்", "puri": "பூரி", "coimbatore": "கோயம்புத்தூர்", "madurai": "மதுரை",
        "tiruchirappalli": "திருச்சிராப்பள்ளி", "salem": "சேலம்", "rameswaram": "ராமேஸ்வரம்",
        "thiruvananthapuram": "திருவனந்தபுரம்", "kozhikode": "கோழிக்கோடு",
        "thrissur": "திருச்சூர்", "kollam": "கொல்லம்", "kannur": "கண்ணூர்",
        "malappuram": "மலப்புரம்", "mysuru": "மைசூரு", "mangaluru": "மங்களூரு",
        "hubballi": "ஹுப்பள்ளி", "warangal": "வாரங்கல்", "vijayawada": "விஜயவாடா",
        "tirupati": "திருப்பதி", "guntur": "குண்டூர்", "panaji": "பனாஜி", "shillong": "ஷில்லாங்",
        "imphal": "இம்பால்", "agartala": "அகர்தலா", "gangtok": "கேங்டாக்", "aizawl": "ஐசால்",
        "kohima": "கோகிமா", "itanagar": "இட்டாநகர்", "puducherry": "புதுச்சேரி",
    },
    "ml": {
        "new-delhi": "ന്യൂഡൽഹി", "mumbai": "മുംബൈ", "kolkata": "കൊൽക്കത്ത", "chennai": "ചെന്നൈ",
        "bengaluru": "ബെംഗളൂരു", "hyderabad": "ഹൈദരാബാദ്", "ahmedabad": "അഹമ്മദാബാദ്",
        "pune": "പുണെ", "jaipur": "ജയ്പൂർ", "lucknow": "ലഖ്നൗ", "kanpur": "കാൺപൂർ",
        "nagpur": "നാഗ്പൂർ", "indore": "ഇൻഡോർ", "bhopal": "ഭോപ്പാൽ", "patna": "പട്ന",
        "varanasi": "വാരാണസി", "prayagraj": "പ്രയാഗ്‌രാജ്", "surat": "സൂറത്ത്",
        "vadodara": "വഡോദര", "chandigarh": "ചണ്ഡീഗഢ്", "amritsar": "അമൃത്സർ",
        "dehradun": "ഡെറാഡൂൺ", "haridwar": "ഹരിദ്വാർ", "noida": "നോയിഡ", "gurugram": "ഗുരുഗ്രാം",
        "bhubaneswar": "ഭുവനേശ്വർ", "guwahati": "ഗുവാഹത്തി", "ranchi": "റാഞ്ചി", "kochi": "കൊച്ചി",
        "visakhapatnam": "വിശാഖപട്ടണം", "thane": "താനെ", "navi-mumbai": "നവി മുംബൈ",
        "nashik": "നാസിക്", "chhatrapati-sambhajinagar": "ഛത്രപതി സംഭാജിനഗർ",
        "solapur": "സോലാപൂർ", "kolhapur": "കോലാപ്പൂർ", "amravati": "അമരാവതി", "shirdi": "ഷിർദി",
        "rajkot": "രാജ്കോട്ട്", "bhavnagar": "ഭാവ്നഗർ", "jamnagar": "ജാംനഗർ",
        "gandhinagar": "ഗാന്ധിനഗർ", "dwarka": "ദ്വാരക", "somnath": "സോമനാഥ്",
        "jodhpur": "ജോധ്പൂർ", "udaipur": "ഉദയ്പൂർ", "kota": "കോട്ട", "ajmer": "അജ്മീർ",
        "bikaner": "ബിക്കാനീർ", "agra": "ആഗ്ര", "ghaziabad": "ഗാസിയാബാദ്", "meerut": "മീററ്റ്",
        "bareilly": "ബറേലി", "aligarh": "അലിഗഢ്", "moradabad": "മൊറാദാബാദ്",
        "gorakhpur": "ഗോരഖ്പൂർ", "saharanpur": "സഹാറൻപൂർ", "ayodhya": "അയോധ്യ",
        "mathura": "മഥുര", "vrindavan": "വൃന്ദാവനം", "jhansi": "ഝാൻസി",
        "faridabad": "ഫരീദാബാദ്", "kurukshetra": "കുരുക്ഷേത്ര", "ludhiana": "ലുധിയാന",
        "jalandhar": "ജലന്ധർ", "patiala": "പട്യാല", "rishikesh": "ഋഷികേശ്", "shimla": "ഷിംല",
        "jammu": "ജമ്മു", "srinagar": "ശ്രീനഗർ", "katra": "കട്ര", "gwalior": "ഗ്വാളിയോർ",
        "jabalpur": "ജബൽപൂർ", "ujjain": "ഉജ്ജയിൻ", "raipur": "റായ്പൂർ", "bhilai": "ഭിലായ്",
        "gaya": "ഗയ", "bhagalpur": "ഭാഗൽപൂർ", "muzaffarpur": "മുസഫർപൂർ",
        "jamshedpur": "ജംഷഡ്പൂർ", "dhanbad": "ധൻബാദ്", "deoghar": "ദേവ്ഘർ", "howrah": "ഹൗറ",
        "asansol": "അസൻസോൾ", "siliguri": "സിലിഗുരി", "cuttack": "കട്ടക്ക്", "puri": "പുരി",
        "coimbatore": "കോയമ്പത്തൂർ", "madurai": "മധുര", "tiruchirappalli": "തിരുച്ചിറപ്പള്ളി",
        "salem": "സേലം", "rameswaram": "രാമേശ്വരം", "thiruvananthapuram": "തിരുവനന്തപുരം",
        "kozhikode": "കോഴിക്കോട്", "thrissur": "തൃശ്ശൂർ", "kollam": "കൊല്ലം", "kannur": "കണ്ണൂർ",
        "malappuram": "മലപ്പുറം", "mysuru": "മൈസൂരു", "mangaluru": "മംഗളൂരു",
        "hubballi": "ഹുബ്ബള്ളി", "warangal": "വാറങ്കൽ", "vijayawada": "വിജയവാഡ",
        "tirupati": "തിരുപ്പതി", "guntur": "ഗുണ്ടൂർ", "panaji": "പനാജി", "shillong": "ഷില്ലോങ്",
        "imphal": "ഇംഫാൽ", "agartala": "അഗർത്തല", "gangtok": "ഗാങ്ടോക്ക്", "aizawl": "ഐസോൾ",
        "kohima": "കൊഹിമ", "itanagar": "ഇറ്റാനഗർ", "puducherry": "പുതുച്ചേരി",
    },
    "bn": {
        "new-delhi": "নয়াদিল্লি", "mumbai": "মুম্বই", "kolkata": "কলকাতা", "chennai": "চেন্নাই",
        "bengaluru": "বেঙ্গালুরু", "hyderabad": "হায়দরাবাদ", "ahmedabad": "আমেদাবাদ",
        "pune": "পুনে", "jaipur": "জয়পুর", "lucknow": "লখনউ", "kanpur": "কানপুর",
        "nagpur": "নাগপুর", "indore": "ইন্দোর", "bhopal": "ভোপাল", "patna": "পটনা",
        "varanasi": "বারাণসী", "prayagraj": "প্রয়াগরাজ", "surat": "সুরাট", "vadodara": "বডোদরা",
        "chandigarh": "চণ্ডীগড়", "amritsar": "অমৃতসর", "dehradun": "দেরাদুন",
        "haridwar": "হরিদ্বার", "noida": "নয়ডা", "gurugram": "গুরুগ্রাম",
        "bhubaneswar": "ভুবনেশ্বর", "guwahati": "গুয়াহাটি", "ranchi": "রাঁচি", "kochi": "কোচি",
        "visakhapatnam": "বিশাখাপত্তনম", "thane": "থানে", "navi-mumbai": "নবী মুম্বই",
        "nashik": "নাসিক", "chhatrapati-sambhajinagar": "ছত্রপতি সম্ভাজীনগর",
        "solapur": "সোলাপুর", "kolhapur": "কোলহাপুর", "amravati": "অমরাবতী", "shirdi": "শিরডি",
        "rajkot": "রাজকোট", "bhavnagar": "ভাবনগর", "jamnagar": "জামনগর",
        "gandhinagar": "গান্ধীনগর", "dwarka": "দ্বারকা", "somnath": "সোমনাথ", "jodhpur": "যোধপুর",
        "udaipur": "উদয়পুর", "kota": "কোটা", "ajmer": "আজমির", "bikaner": "বিকানের",
        "agra": "আগ্রা", "ghaziabad": "গাজিয়াবাদ", "meerut": "মীরাট", "bareilly": "বরেলি",
        "aligarh": "আলিগড়", "moradabad": "মোরাদাবাদ", "gorakhpur": "গোরক্ষপুর",
        "saharanpur": "সাহারানপুর", "ayodhya": "অযোধ্যা", "mathura": "মথুরা",
        "vrindavan": "বৃন্দাবন", "jhansi": "ঝাঁসি", "faridabad": "ফরিদাবাদ",
        "kurukshetra": "কুরুক্ষেত্র", "ludhiana": "লুধিয়ানা", "jalandhar": "জলন্ধর",
        "patiala": "পাতিয়ালা", "rishikesh": "ঋষিকেশ", "shimla": "শিমলা", "jammu": "জম্মু",
        "srinagar": "শ্রীনগর", "katra": "কাটরা", "gwalior": "গোয়ালিয়র", "jabalpur": "জবলপুর",
        "ujjain": "উজ্জয়িনী", "raipur": "রায়পুর", "bhilai": "ভিলাই", "gaya": "গয়া",
        "bhagalpur": "ভাগলপুর", "muzaffarpur": "মুজফফরপুর", "jamshedpur": "জামশেদপুর",
        "dhanbad": "ধানবাদ", "deoghar": "দেওঘর", "howrah": "হাওড়া", "asansol": "আসানসোল",
        "siliguri": "শিলিগুড়ি", "cuttack": "কটক", "puri": "পুরী", "coimbatore": "কোয়েম্বাটুর",
        "madurai": "মাদুরাই", "tiruchirappalli": "তিরুচিরাপল্লি", "salem": "সালেম",
        "rameswaram": "রামেশ্বরম", "thiruvananthapuram": "তিরুবনন্তপুরম",
        "kozhikode": "কোঝিকোড়", "thrissur": "ত্রিশূর", "kollam": "কোল্লাম", "kannur": "কন্নুর",
        "malappuram": "মালাপ্পুরম", "mysuru": "মাইসুরু", "mangaluru": "ম্যাঙ্গালুরু",
        "hubballi": "হুব্বল্লি", "warangal": "ওয়ারাঙ্গল", "vijayawada": "বিজয়ওয়াড়া",
        "tirupati": "তিরুপতি", "guntur": "গুন্টুর", "panaji": "পানাজি", "shillong": "শিলং",
        "imphal": "ইম্ফল", "agartala": "আগরতলা", "gangtok": "গ্যাংটক", "aizawl": "আইজল",
        "kohima": "কোহিমা", "itanagar": "ইটানগর", "puducherry": "পুদুচেরি",
    },
    "or": {
        "new-delhi": "ନୂଆଦିଲ୍ଲୀ", "mumbai": "ମୁମ୍ବାଇ", "kolkata": "କୋଲକାତା", "chennai": "ଚେନ୍ନାଇ",
        "bengaluru": "ବେଙ୍ଗାଲୁରୁ", "hyderabad": "ହାଇଦ୍ରାବାଦ", "ahmedabad": "ଅହମଦାବାଦ",
        "pune": "ପୁଣେ", "jaipur": "ଜୟପୁର", "lucknow": "ଲକ୍ଷ୍ନୌ", "kanpur": "କାନପୁର",
        "nagpur": "ନାଗପୁର", "indore": "ଇନ୍ଦୋର", "bhopal": "ଭୋପାଳ", "patna": "ପାଟନା",
        "varanasi": "ବାରାଣସୀ", "prayagraj": "ପ୍ରୟାଗରାଜ", "surat": "ସୁରଟ", "vadodara": "ବଡୋଦରା",
        "chandigarh": "ଚଣ୍ଡୀଗଡ଼", "amritsar": "ଅମୃତସର", "dehradun": "ଦେହରାଦୁନ",
        "haridwar": "ହରିଦ୍ୱାର", "noida": "ନୋଏଡା", "gurugram": "ଗୁରୁଗ୍ରାମ",
        "bhubaneswar": "ଭୁବନେଶ୍ୱର", "guwahati": "ଗୁଆହାଟୀ", "ranchi": "ରାଞ୍ଚି", "kochi": "କୋଚି",
        "visakhapatnam": "ବିଶାଖାପାଟଣା", "thane": "ଠାଣେ", "navi-mumbai": "ନବୀ ମୁମ୍ବାଇ",
        "nashik": "ନାସିକ", "chhatrapati-sambhajinagar": "ଛତ୍ରପତି ସମ୍ଭାଜୀନଗର",
        "solapur": "ସୋଲାପୁର", "kolhapur": "କୋହ୍ଲାପୁର", "amravati": "ଅମରାବତୀ", "shirdi": "ଶିରଡି",
        "rajkot": "ରାଜକୋଟ", "bhavnagar": "ଭାବନଗର", "jamnagar": "ଜାମନଗର",
        "gandhinagar": "ଗାନ୍ଧୀନଗର", "dwarka": "ଦ୍ୱାରକା", "somnath": "ସୋମନାଥ", "jodhpur": "ଯୋଧପୁର",
        "udaipur": "ଉଦୟପୁର", "kota": "କୋଟା", "ajmer": "ଅଜମେର", "bikaner": "ବିକାନେର",
        "agra": "ଆଗ୍ରା", "ghaziabad": "ଗାଜିଆବାଦ", "meerut": "ମେରଠ", "bareilly": "ବରେଲି",
        "aligarh": "ଅଲିଗଡ଼", "moradabad": "ମୋରାଦାବାଦ", "gorakhpur": "ଗୋରଖପୁର",
        "saharanpur": "ସାହାରାନପୁର", "ayodhya": "ଅଯୋଧ୍ୟା", "mathura": "ମଥୁରା",
        "vrindavan": "ବୃନ୍ଦାବନ", "jhansi": "ଝାନ୍ସୀ", "faridabad": "ଫରିଦାବାଦ",
        "kurukshetra": "କୁରୁକ୍ଷେତ୍ର", "ludhiana": "ଲୁଧିଆନା", "jalandhar": "ଜଳନ୍ଧର",
        "patiala": "ପଟିଆଲା", "rishikesh": "ଋଷିକେଶ", "shimla": "ଶିମଲା", "jammu": "ଜାମ୍ମୁ",
        "srinagar": "ଶ୍ରୀନଗର", "katra": "କଟରା", "gwalior": "ଗ୍ୱାଲିଅର", "jabalpur": "ଜବଲପୁର",
        "ujjain": "ଉଜ୍ଜୟିନୀ", "raipur": "ରାୟପୁର", "bhilai": "ଭିଲାଇ", "gaya": "ଗୟା",
        "bhagalpur": "ଭାଗଲପୁର", "muzaffarpur": "ମୁଜଫରପୁର", "jamshedpur": "ଜାମସେଦପୁର",
        "dhanbad": "ଧନବାଦ", "deoghar": "ଦେଓଘର", "howrah": "ହାଓଡ଼ା", "asansol": "ଆସାନସୋଲ",
        "siliguri": "ଶିଲିଗୁଡ଼ି", "cuttack": "କଟକ", "puri": "ପୁରୀ", "coimbatore": "କୋଏମ୍ବାଟୁର",
        "madurai": "ମଦୁରାଇ", "tiruchirappalli": "ତିରୁଚିରାପଲ୍ଲୀ", "salem": "ସାଲେମ",
        "rameswaram": "ରାମେଶ୍ୱରମ", "thiruvananthapuram": "ତିରୁବନନ୍ତପୁରମ",
        "kozhikode": "କୋଝିକୋଡ଼", "thrissur": "ତ୍ରିଶୂର", "kollam": "କୋଲ୍ଲମ", "kannur": "କନ୍ନୁର",
        "malappuram": "ମଲପ୍ପୁରମ", "mysuru": "ମାଇସୁରୁ", "mangaluru": "ମାଙ୍ଗାଲୁରୁ",
        "hubballi": "ହୁବ୍ବଲ୍ଲି", "warangal": "ୱାରାଙ୍ଗଲ", "vijayawada": "ବିଜୟୱାଡ଼ା",
        "tirupati": "ତିରୁପତି", "guntur": "ଗୁଣ୍ଟୁର", "panaji": "ପଣଜୀ", "shillong": "ଶିଲଂ",
        "imphal": "ଇମ୍ଫାଲ", "agartala": "ଅଗରତଲା", "gangtok": "ଗାଙ୍ଗଟକ", "aizawl": "ଆଇଜଲ",
        "kohima": "କୋହିମା", "itanagar": "ଇଟାନଗର", "puducherry": "ପୁଡୁଚେରୀ",
    },
}

STATES: dict[str, dict[str, str]] = {
    "kn": {
        "Andhra Pradesh": "ಆಂಧ್ರ ಪ್ರದೇಶ", "Arunachal Pradesh": "ಅರುಣಾಚಲ ಪ್ರದೇಶ", "Assam": "ಅಸ್ಸಾಂ",
        "Bihar": "ಬಿಹಾರ", "Chandigarh": "ಚಂಡೀಗಢ", "Chhattisgarh": "ಛತ್ತೀಸ್‌ಗಢ", "Delhi": "ದೆಹಲಿ",
        "Goa": "ಗೋವಾ", "Gujarat": "ಗುಜರಾತ್", "Haryana": "ಹರಿಯಾಣ",
        "Himachal Pradesh": "ಹಿಮಾಚಲ ಪ್ರದೇಶ", "Jammu and Kashmir": "ಜಮ್ಮು ಮತ್ತು ಕಾಶ್ಮೀರ",
        "Jharkhand": "ಜಾರ್ಖಂಡ್", "Karnataka": "ಕರ್ನಾಟಕ", "Kerala": "ಕೇರಳ",
        "Madhya Pradesh": "ಮಧ್ಯ ಪ್ರದೇಶ", "Maharashtra": "ಮಹಾರಾಷ್ಟ್ರ", "Manipur": "ಮಣಿಪುರ",
        "Meghalaya": "ಮೇಘಾಲಯ", "Mizoram": "ಮಿಜೋರಾಂ", "Nagaland": "ನಾಗಾಲ್ಯಾಂಡ್", "Odisha": "ಒಡಿಶಾ",
        "Puducherry": "ಪುದುಚೇರಿ", "Punjab": "ಪಂಜಾಬ್", "Rajasthan": "ರಾಜಸ್ಥಾನ", "Sikkim": "ಸಿಕ್ಕಿಂ",
        "Tamil Nadu": "ತಮಿಳುನಾಡು", "Telangana": "ತೆಲಂಗಾಣ", "Tripura": "ತ್ರಿಪುರಾ",
        "Uttar Pradesh": "ಉತ್ತರ ಪ್ರದೇಶ", "Uttarakhand": "ಉತ್ತರಾಖಂಡ", "West Bengal": "ಪಶ್ಚಿಮ ಬಂಗಾಳ",
    },
    "te": {
        "Andhra Pradesh": "ఆంధ్రప్రదేశ్", "Arunachal Pradesh": "అరుణాచల్ ప్రదేశ్", "Assam": "అసోం",
        "Bihar": "బిహార్", "Chandigarh": "చండీగఢ్", "Chhattisgarh": "ఛత్తీస్‌గఢ్", "Delhi": "ఢిల్లీ",
        "Goa": "గోవా", "Gujarat": "గుజరాత్", "Haryana": "హరియాణా",
        "Himachal Pradesh": "హిమాచల్ ప్రదేశ్", "Jammu and Kashmir": "జమ్మూ కశ్మీర్",
        "Jharkhand": "ఝార్ఖండ్", "Karnataka": "కర్ణాటక", "Kerala": "కేరళ",
        "Madhya Pradesh": "మధ్యప్రదేశ్", "Maharashtra": "మహారాష్ట్ర", "Manipur": "మణిపూర్",
        "Meghalaya": "మేఘాలయ", "Mizoram": "మిజోరం", "Nagaland": "నాగాలాండ్", "Odisha": "ఒడిశా",
        "Puducherry": "పుదుచ్చేరి", "Punjab": "పంజాబ్", "Rajasthan": "రాజస్థాన్", "Sikkim": "సిక్కిం",
        "Tamil Nadu": "తమిళనాడు", "Telangana": "తెలంగాణ", "Tripura": "త్రిపుర",
        "Uttar Pradesh": "ఉత్తరప్రదేశ్", "Uttarakhand": "ఉత్తరాఖండ్", "West Bengal": "పశ్చిమ బెంగాల్",
    },
    "ta": {
        "Andhra Pradesh": "ஆந்திரப் பிரதேசம்", "Arunachal Pradesh": "அருணாச்சலப் பிரதேசம்",
        "Assam": "அசாம்", "Bihar": "பீகார்", "Chandigarh": "சண்டிகர்", "Chhattisgarh": "சத்தீஸ்கர்",
        "Delhi": "தில்லி", "Goa": "கோவா", "Gujarat": "குஜராத்", "Haryana": "அரியானா",
        "Himachal Pradesh": "இமாச்சலப் பிரதேசம்", "Jammu and Kashmir": "ஜம்மு காஷ்மீர்",
        "Jharkhand": "ஜார்க்கண்ட்", "Karnataka": "கர்நாடகா", "Kerala": "கேரளா",
        "Madhya Pradesh": "மத்தியப் பிரதேசம்", "Maharashtra": "மகாராஷ்டிரா", "Manipur": "மணிப்பூர்",
        "Meghalaya": "மேகாலயா", "Mizoram": "மிசோரம்", "Nagaland": "நாகாலாந்து", "Odisha": "ஒடிசா",
        "Puducherry": "புதுச்சேரி", "Punjab": "பஞ்சாப்", "Rajasthan": "ராஜஸ்தான்",
        "Sikkim": "சிக்கிம்", "Tamil Nadu": "தமிழ்நாடு", "Telangana": "தெலங்கானா",
        "Tripura": "திரிபுரா", "Uttar Pradesh": "உத்தரப் பிரதேசம்", "Uttarakhand": "உத்தராகண்ட்",
        "West Bengal": "மேற்கு வங்காளம்",
    },
    "ml": {
        "Andhra Pradesh": "ആന്ധ്രാപ്രദേശ്", "Arunachal Pradesh": "അരുണാചൽ പ്രദേശ്", "Assam": "അസം",
        "Bihar": "ബിഹാർ", "Chandigarh": "ചണ്ഡീഗഢ്", "Chhattisgarh": "ഛത്തീസ്ഗഢ്", "Delhi": "ഡൽഹി",
        "Goa": "ഗോവ", "Gujarat": "ഗുജറാത്ത്", "Haryana": "ഹരിയാന",
        "Himachal Pradesh": "ഹിമാചൽ പ്രദേശ്", "Jammu and Kashmir": "ജമ്മു കശ്മീർ",
        "Jharkhand": "ഝാർഖണ്ഡ്", "Karnataka": "കർണാടക", "Kerala": "കേരളം",
        "Madhya Pradesh": "മധ്യപ്രദേശ്", "Maharashtra": "മഹാരാഷ്ട്ര", "Manipur": "മണിപ്പൂർ",
        "Meghalaya": "മേഘാലയ", "Mizoram": "മിസോറം", "Nagaland": "നാഗാലാൻഡ്", "Odisha": "ഒഡീഷ",
        "Puducherry": "പുതുച്ചേരി", "Punjab": "പഞ്ചാബ്", "Rajasthan": "രാജസ്ഥാൻ", "Sikkim": "സിക്കിം",
        "Tamil Nadu": "തമിഴ്‌നാട്", "Telangana": "തെലങ്കാന", "Tripura": "ത്രിപുര",
        "Uttar Pradesh": "ഉത്തർപ്രദേശ്", "Uttarakhand": "ഉത്തരാഖണ്ഡ്", "West Bengal": "പശ്ചിമ ബംഗാൾ",
    },
    "bn": {
        "Andhra Pradesh": "অন্ধ্রপ্রদেশ", "Arunachal Pradesh": "অরুণাচল প্রদেশ", "Assam": "অসম",
        "Bihar": "বিহার", "Chandigarh": "চণ্ডীগড়", "Chhattisgarh": "ছত্তিশগড়", "Delhi": "দিল্লি",
        "Goa": "গোয়া", "Gujarat": "গুজরাট", "Haryana": "হরিয়ানা",
        "Himachal Pradesh": "হিমাচল প্রদেশ", "Jammu and Kashmir": "জম্মু ও কাশ্মীর",
        "Jharkhand": "ঝাড়খণ্ড", "Karnataka": "কর্ণাটক", "Kerala": "কেরল",
        "Madhya Pradesh": "মধ্যপ্রদেশ", "Maharashtra": "মহারাষ্ট্র", "Manipur": "মণিপুর",
        "Meghalaya": "মেঘালয়", "Mizoram": "মিজোরাম", "Nagaland": "নাগাল্যান্ড", "Odisha": "ওড়িশা",
        "Puducherry": "পুদুচেরি", "Punjab": "পাঞ্জাব", "Rajasthan": "রাজস্থান", "Sikkim": "সিকিম",
        "Tamil Nadu": "তামিলনাড়ু", "Telangana": "তেলেঙ্গানা", "Tripura": "ত্রিপুরা",
        "Uttar Pradesh": "উত্তরপ্রদেশ", "Uttarakhand": "উত্তরাখণ্ড", "West Bengal": "পশ্চিমবঙ্গ",
    },
    "or": {
        "Andhra Pradesh": "ଆନ୍ଧ୍ରପ୍ରଦେଶ", "Arunachal Pradesh": "ଅରୁଣାଚଳ ପ୍ରଦେଶ", "Assam": "ଆସାମ",
        "Bihar": "ବିହାର", "Chandigarh": "ଚଣ୍ଡୀଗଡ଼", "Chhattisgarh": "ଛତିଶଗଡ଼", "Delhi": "ଦିଲ୍ଲୀ",
        "Goa": "ଗୋଆ", "Gujarat": "ଗୁଜରାଟ", "Haryana": "ହରିୟାଣା",
        "Himachal Pradesh": "ହିମାଚଳ ପ୍ରଦେଶ", "Jammu and Kashmir": "ଜାମ୍ମୁ ଓ କଶ୍ମୀର",
        "Jharkhand": "ଝାଡ଼ଖଣ୍ଡ", "Karnataka": "କର୍ଣ୍ଣାଟକ", "Kerala": "କେରଳ",
        "Madhya Pradesh": "ମଧ୍ୟପ୍ରଦେଶ", "Maharashtra": "ମହାରାଷ୍ଟ୍ର", "Manipur": "ମଣିପୁର",
        "Meghalaya": "ମେଘାଳୟ", "Mizoram": "ମିଜୋରାମ", "Nagaland": "ନାଗାଲାଣ୍ଡ", "Odisha": "ଓଡ଼ିଶା",
        "Puducherry": "ପୁଡୁଚେରୀ", "Punjab": "ପଞ୍ଜାବ", "Rajasthan": "ରାଜସ୍ଥାନ", "Sikkim": "ସିକ୍କିମ",
        "Tamil Nadu": "ତାମିଲନାଡୁ", "Telangana": "ତେଲଙ୍ଗାନା", "Tripura": "ତ୍ରିପୁରା",
        "Uttar Pradesh": "ଉତ୍ତରପ୍ରଦେଶ", "Uttarakhand": "ଉତ୍ତରାଖଣ୍ଡ", "West Bengal": "ପଶ୍ଚିମବଙ୍ଗ",
    },
}
