"""initial schema

Revision ID: 258252979415
Revises: 
Create Date: 2026-08-16 18:21:20.638444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '258252979415'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coupons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.Enum('percent', 'flat', 'extra_credits', name='couponkind'), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('min_amount_paise', sa.Integer(), nullable=False),
    sa.Column('max_discount_paise', sa.Integer(), nullable=True),
    sa.Column('applies_to', sa.String(length=40), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('max_redemptions', sa.Integer(), nullable=True),
    sa.Column('max_per_user', sa.Integer(), nullable=False),
    sa.Column('times_redeemed', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_coupons'))
    )
    with op.batch_alter_table('coupons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_coupons_code'), ['code'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('picture', sa.String(length=400), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('provider_sub', sa.String(length=128), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('blocked', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('provider', 'provider_sub', name='uq_provider_identity')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_provider_sub'), ['provider_sub'], unique=False)

    op.create_table('webhook_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('event_id', sa.String(length=80), nullable=False),
    sa.Column('event_type', sa.String(length=60), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_webhook_events')),
    sa.UniqueConstraint('event_id', name=op.f('uq_webhook_events_event_id'))
    )
    op.create_table('birth_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('time', sa.String(length=5), nullable=False),
    sa.Column('time_known', sa.Boolean(), nullable=False),
    sa.Column('place', sa.String(length=200), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('zodiac', sa.String(length=12), nullable=False),
    sa.Column('ayanamsa', sa.String(length=24), nullable=False),
    sa.Column('house_system', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_birth_profiles_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_birth_profiles'))
    )
    with op.batch_alter_table('birth_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_birth_profiles_user_id'), ['user_id'], unique=False)

    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('amount_paise', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('created', 'awaiting_verification', 'paid', 'failed', 'refunded', 'rejected', name='orderstatus'), nullable=False),
    sa.Column('coupon_id', sa.Integer(), nullable=True),
    sa.Column('discount_paise', sa.Integer(), nullable=False),
    sa.Column('original_amount_paise', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('provider_order_id', sa.String(length=64), nullable=False),
    sa.Column('provider_payment_id', sa.String(length=64), nullable=True),
    sa.Column('fulfilment', sa.Enum('not_applicable', 'pending', 'in_progress', 'delivered', name='fulfilstatus'), nullable=False),
    sa.Column('fulfil_note', sa.Text(), nullable=False),
    sa.Column('delivered_path', sa.String(length=255), nullable=False),
    sa.Column('birth_id', sa.Integer(), nullable=True),
    sa.Column('utr', sa.String(length=32), nullable=True),
    sa.Column('utr_submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_by', sa.Integer(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verify_note', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['birth_id'], ['birth_profiles.id'], name=op.f('fk_orders_birth_id_birth_profiles')),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupons.id'], name=op.f('fk_orders_coupon_id_coupons')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_orders_user_id_users')),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], name=op.f('fk_orders_verified_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders')),
    sa.UniqueConstraint('provider', 'provider_payment_id', name='uq_provider_payment'),
    sa.UniqueConstraint('utr', name='uq_order_utr')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orders_provider_order_id'), ['provider_order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_sku'), ['sku'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_user_id'), ['user_id'], unique=False)

    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('birth_id', sa.Integer(), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('answer_engine', sa.Text(), nullable=False),
    sa.Column('topic', sa.String(length=40), nullable=False),
    sa.Column('verdict', sa.String(length=60), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('charged', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['birth_id'], ['birth_profiles.id'], name=op.f('fk_questions_birth_id_birth_profiles')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_questions_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_questions'))
    )
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_questions_user_id'), ['user_id'], unique=False)

    op.create_table('coupon_redemptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coupon_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('discount_paise', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupons.id'], name=op.f('fk_coupon_redemptions_coupon_id_coupons')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_coupon_redemptions_order_id_orders')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_coupon_redemptions_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_coupon_redemptions')),
    sa.UniqueConstraint('order_id', name='uq_redemption_order')
    )
    with op.batch_alter_table('coupon_redemptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_coupon_redemptions_coupon_id'), ['coupon_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_coupon_redemptions_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_coupon_redemptions_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_redemption_coupon_user', ['coupon_id', 'user_id'], unique=False)

    op.create_table('credit_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('signup_bonus', 'purchase', 'question', 'refund', 'admin_adjust', name='entrykind'), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_credit_entries_order_id_orders')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_credit_entries_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_credit_entries'))
    )
    with op.batch_alter_table('credit_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_credit_entries_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_credit_entries_user_id'))

    op.drop_table('credit_entries')
    with op.batch_alter_table('coupon_redemptions', schema=None) as batch_op:
        batch_op.drop_index('ix_redemption_coupon_user')
        batch_op.drop_index(batch_op.f('ix_coupon_redemptions_user_id'))
        batch_op.drop_index(batch_op.f('ix_coupon_redemptions_order_id'))
        batch_op.drop_index(batch_op.f('ix_coupon_redemptions_coupon_id'))

    op.drop_table('coupon_redemptions')
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_questions_user_id'))

    op.drop_table('questions')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_user_id'))
        batch_op.drop_index(batch_op.f('ix_orders_sku'))
        batch_op.drop_index(batch_op.f('ix_orders_provider_order_id'))

    op.drop_table('orders')
    with op.batch_alter_table('birth_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_birth_profiles_user_id'))

    op.drop_table('birth_profiles')
    op.drop_table('webhook_events')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_provider_sub'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('coupons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_coupons_code'))

    op.drop_table('coupons')
    # ### end Alembic commands ###
