"""add gender to birth_profiles

Revision ID: ca114b6a6cbb
Revises: 258252979415
Create Date: 2026-08-17 00:34:47.231898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca114b6a6cbb'
down_revision: Union[str, Sequence[str], None] = '258252979415'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Add the optional gender field to saved charts.

    server_default is essential and was NOT in the autogenerated version: the
    column is NOT NULL, so without a default this fails outright on any table
    that already holds rows. Every existing chart becomes '' — unstated — which
    is a valid value and exactly the right answer for a chart saved before the
    question was ever asked.
    """
    with op.batch_alter_table('birth_profiles', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('gender', sa.String(length=10), nullable=False,
                      server_default=''))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('birth_profiles', schema=None) as batch_op:
        batch_op.drop_column('gender')

    # ### end Alembic commands ###
